/**
 * Owner-facing strings for the analysis evidence chain.
 * Display only. Shaped like `copy` in sales-intelligence-copy.ts so these can be folded into it.
 * Nothing here may claim more than the stored run supports.
 */
export const evidenceChainCopy = {
  chain: {
    title: "Where this came from",
    intro: "Each claim is shown as a chain: the call it read, the evidence it kept, what the model said, what that changed in your work, and what you decided.",
    listLabel: "Model claims and their evidence",
    stepsLabel: "Chain of custody",
    steps: {
      source: "The call this read",
      evidence: "Evidence kept",
      claim: "What the model said",
      effect: "What it changed",
      decision: "Your decision",
    },
    show: (step: string) => `Show ${step.toLowerCase()}`,
    hide: (step: string) => `Hide ${step.toLowerCase()}`,
    claimsNone: "This analysis recorded no claims.",
    claimFallback: "Model claim",
    claimIndex: (position: number, total: number) => `Claim ${position} of ${total}`,
    openAlways: "Blocked outcomes and anything you retracted stay open.",
  },
  rows: {
    basis: "Where it came from",
    speaker: "Who said it",
    actionStatus: "What kind of action",
    clarity: "How clear it was",
    confidence: "Model confidence",
    tool: "How it was read",
    kept: "When it was kept",
    record: "Record",
    fields: "Fields read",
    followup: "Follow-up",
  },
  source: {
    oneConversation: "This analysis read one recorded conversation.",
    wholeNumber: "This analysis read the history on this Number, not one single call.",
    ranAt: (time: string) => `The model started at ${time}.`,
    finishedAt: (time: string) => `It finished at ${time}.`,
    notFinished: "It has not finished.",
    activityLink: "Open Number Activity",
    activityNote: "When the call happened, which way it went, and how it ended live on Number Activity.",
    transcriptVersion: (version: string) => `Transcript version ${version}.`,
    segments: (count: number) => (count === 1 ? "1 transcript line cited" : `${count} transcript lines cited`),
    modelUsed: (model: string, prompt: string) => `Model ${model}, prompt ${prompt}.`,
  },
  evidence: {
    none: "No retained evidence is cited for this claim.",
    cited: (count: number) => (count === 1 ? "1 kept item backs this claim." : `${count} kept items back this claim.`),
    open: "Open this item",
    close: "Close this item",
    transcript: "Call transcript",
    record: "Vantage record",
    unknownSource: "Recorded reference",
    readWith: (tool: string) => `Read with ${tool}`,
    keptAt: (time: string) => `Kept ${time}`,
    keptUnknown: "When it was kept is not recorded.",
    stored: "The original is still stored.",
    gone: "The original is no longer stored.",
    goneOn: (time: string) => `The original was removed ${time}.`,
    notInRun: "This item is not in the set this analysis kept.",
    quoteKept: "A quote was kept.",
    quoteNone: "No quote was kept.",
    recordRef: (type: string, id: string) => `${type} · ${id}`,
    showJson: "Show the recorded JSON",
    jsonNote: "This is the reference exactly as the model recorded it.",
    allTitle: "All evidence kept for this analysis",
    partial: "Only part of this item is shown.",
    retentionInProgress: "The original is being removed under the retention rules.",
    contentFailed: "Could not load this item.",
    firstPage: "Back to the first items",
    nextPage: "More kept items",
    startOfItem: "Back to the start of this item",
    nextSection: "More of this item",
  },
  claim: {
    basis: {
      said_on_call: "Heard on the call",
      vantage_record: "Read from a Vantage record",
      model_inference: "The model's own reading, not something said",
    },
    actor: {
      rep: "Said by a rep",
      customer: "Said by the customer",
      unknown: "Speaker unknown",
    },
    actionStatus: {
      requested: "The customer asked for it",
      promised: "Someone promised it",
      completed: "Claimed done",
      conditional: "Only if something else happens",
    },
    clarity: {
      clear: "Stated clearly",
      uncertain: "The model was not certain",
    },
    confidence: (value: string) => `Model confidence ${value}`,
    checksNote: "These check the claim's paperwork. They are not proof the claim is true.",
    checksLabel: {
      schema: "Shape",
      snapshots: "Evidence links",
      locator: "Quote",
      support: "Support",
    },
    schemaPass: "The claim matched the expected shape.",
    schemaFail: "The claim did not match the expected shape.",
    snapshotsPass: "Every cited item is in the set this analysis kept.",
    snapshotsFail: "At least one cited item is not in the set this analysis kept.",
    locator: {
      not_run: "The quote was not machine-checked.",
      located: "The quote was found in the transcript.",
      unlocated: "The quote could not be found in the transcript.",
      unknown: "The quote check is not recorded.",
    },
    support: {
      not_run: "Whether the evidence supports the claim was not machine-checked.",
      pass: "A check found the evidence supports the claim.",
      fail: "A check found the evidence does not support the claim.",
      unsure: "A check could not tell whether the evidence supports the claim.",
      unknown: "The support check is not recorded.",
    },
    headline: {
      unchecked: "Not machine-checked",
      checked: "Checks passed",
      problem: "A check did not pass",
    },
  },
  effect: {
    none: "This claim changed nothing in your work.",
    kind: {
      create_followup: "Added a follow-up",
      revise_followup: "Changed a follow-up",
      complete_followup: "Completed a follow-up",
      cancel_followup: "Cancelled a follow-up",
      assign: "Set who owns the work",
      set_contact_type: "Recorded how the call ended",
      mark_meaningful_contact: "Recorded a real conversation",
      pause_channel: "Paused a way of contacting",
      open_review: "Opened something for you to decide",
      open_number_review: "Opened this Number for you to decide",
      supersede: "Replaced an earlier claim",
    },
    status: {
      applied: "Applied to your work.",
      no_change: "Nothing changed. Your work already read this way.",
      blocked_owner: "Blocked. Your own correction wins.",
      blocked_identity: "Blocked. Which Lead this is was not settled.",
      blocked_closed: "Blocked. That work is closed.",
      blocked_restriction: "Blocked. Contacting this number is paused.",
      needs_review: "Left for you to decide.",
      stale: "Not applied. The work had already moved on.",
      unknown: "The outcome is not recorded.",
    },
    at: (time: string) => `Recorded ${time}`,
    reason: (reason: string) => `Reason recorded: ${reason}`,
    openWork: "Open this follow-up in Work",
    targetUnknown: "The follow-up it touched is not listed on this analysis.",
    untouched: "No follow-up is attached to this outcome.",
  },
  decision: {
    unreviewed: "You have not decided on this yet.",
    retracted: "You retracted this.",
    lockedRun: "Only the current analysis can be reviewed. This is an earlier one.",
    lookAgain: "Look at this again",
    lookAgainNote: "Asks for another analysis scoped to this claim. It uses the evidence already kept when that is still stored, and fresh context when it is not.",
    whatTheseDo: "What these do",
    decidedBy: (actor: string, time: string) => `Recorded by ${actor} at ${time}.`,
    whoWhere: "Who decided and when is listed under Review history below.",
    requestOnClaim: (time: string, status: string) => `You asked for another analysis on ${time} — ${status}.`,
  },
  rerun: {
    title: "Ask for another analysis",
    intro: "A new analysis does not delete this one. Both stay on record.",
    queued: "Processing may stay queued while AI is paused.",
    keptTitle: "Run again on the evidence already kept",
    keptNote: "Uses the evidence and prompt this analysis stored, plus only the corrections you tick.",
    keptUnavailable: "The kept evidence is gone, so running again on it is not available.",
    freshTitle: "Capture fresh context now",
    freshNote: "Reads this Number again as it stands today. It may see things this analysis never had.",
    needsOutput: "This analysis has no finished output to run again from.",
    scopedTo: (claim: string) => `Scoped to this claim: ${claim}`,
    requests: "Analyses you have asked for",
    requestsNone: "You have not asked for another analysis of this one.",
    requestLine: (mode: string, time: string, status: string) => `${mode} · asked ${time} · ${status}`,
  },
  run: {
    status: {
      queued: "Waiting to start.",
      running: "Running now.",
      submitted: "The model answered. The result is being applied.",
      completed: "Finished.",
      stale: "Replaced by a later analysis.",
      paused: "Paused.",
      failed: "Did not finish.",
      dead_letter: "Stopped after repeated failures. That is not a customer outcome.",
      unknown: "State not recorded.",
    },
    pickerLabel: "Choose an analysis",
    loading: "Loading analyses…",
    none: "No analysis has run on this Number yet.",
    newest: "Newest analyses",
    older: "Older analyses",
    detailFailed: "Couldn't load this analysis.",
    gone: "This analysis could not be opened. It may have been removed under the retention rules.",
    noOutput: "This analysis has no finished output, so there is nothing to read yet.",
    notFinishedYet: "This analysis has not finished, so there is nothing to read yet.",
    current: "Current analysis",
    earlier: "Earlier analysis",
    nextStep: "Suggested next step",
    nextStepWhy: (rationale: string) => `Why: ${rationale}`,
    instructions: "Your changes and what the model made of them",
    instructionsNone: "No changes of yours are recorded against this analysis.",
    instructionsTruncated: "Only the first 200 changes are shown.",
    instructionStale: "The model assessed an earlier version of this change.",
    historyTitle: "Review history",
    historyNote: "Every review decision, kept as it was recorded. Nothing here can be edited.",
    historyNone: "No review events are recorded.",
    historyNewest: "Newest review events",
    historyOlder: "Older review events",
    showJson: "Show the recorded JSON",
  },
  summaryLink: {
    fromRun: (time: string) => `This picture came from the analysis published at ${time}.`,
    noRun: "No analysis is recorded as the source of this picture.",
  },
} as const;

/**
 * Move assessment, the repaired analysis panel, the shared evidence viewer and Full output
 * (specification §8.1–8.4). Display words for server values only; scores are ordinal
 * evidence assessments out of 100, never percentages or booking probabilities.
 */
export const assessmentCopy = {
  tab: "Assessment",
  sections: {
    label: "Analysis sections",
    assessment: "Assessment",
    summary: "Summary & findings",
    evidence: "Evidence",
    output: "Full output",
  },
  score: { transaction_intent: "Transaction intent", move_likelihood: "Move likelihood" },
  scoreHelp: {
    transaction_intent: "How strongly the customer intends to buy moving services from Vantage for this move.",
    move_likelihood: "How firmly the customer intends to move, whichever company they choose.",
  },
  scoreNote: "Scores are ordinal evidence assessments out of 100. They are not percentages or booking probabilities.",
  scoreWord: { unknown: "Unknown", pending: "Pending", notApplicable: "Not applicable", notAssessed: "Not assessed", unavailable: "Unavailable" },
  availabilityScore: { pending: "Pending", not_assessed: "Not assessed", not_applicable: "Not applicable", purged: "Unavailable", failed: "Unavailable", unavailable: "Unavailable", unsupported: "Unavailable" },
  historical: (score: string) => `Historical score ${score}, kept for review only`,
  level: { unknown: "Unknown", none: "None", exploring: "Exploring", active: "Active", strong: "Strong", confirmed: "Confirmed" },
  confidence: { low: "Low confidence", medium: "Medium confidence", high: "High confidence" },
  confidenceUnstated: "Confidence not stated",
  availability: {
    not_assessed: "Not assessed", pending: "Pending", ready: "Assessed", insufficient_evidence: "Insufficient evidence", ambiguous_subject: "Ambiguous subject",
    not_applicable: "Not applicable", failed: "Failed", purged: "Purged", unsupported: "Unsupported version", unavailable: "Unavailable",
  },
  availabilityExplain: {
    not_assessed: "No Move assessment exists for this subject and none is queued. Summary and findings stay readable.",
    pending: "A Move assessment is queued or running. Nothing is shown until it is published.",
    insufficient_evidence: "The assessment ran, but the retained evidence was too thin for confident judgments. Unknown values stay Unknown.",
    ambiguous_subject: "The assessment could not tell which move or customer the evidence belongs to, so it made no judgment.",
    not_applicable: "This work is closed or has a terminal CRM disposition, so it has no actionable sales score.",
    failed: "The assessment did not finish. No score was produced. Other sections are unaffected.",
    purged: "This assessment was removed under the retention rules. Its content cannot be shown.",
    unsupported: "This assessment was stored in a version this reader does not support. Its content is not shown rather than guessed.",
    unavailable: "This assessment is temporarily unavailable, for example while retention removal is in progress.",
  },
  applicability: { active: "Active", closed: "Not applicable — closed work", not_applicable: "Not applicable — terminal CRM disposition" },
  inputMode: { summaries: "Conversation summaries", summaries_with_findings: "Summaries and retained findings", lead_only: "Lead fields only, no conversation" },
  freshness: { current: "Current", stale: "Stale", staleBecause: (reason: string) => `Stale: ${reason}` },
  notRecorded: "Not recorded",
  atLeast: (value: number) => `At least ${value}`,
  upTo: (value: number) => `Up to ${value}`,
  precision: (value: string) => `${value} precision`,
  unresolvedDate: "Date not resolved",
  viewLabel: {
    original_form_submission: "Original form submission",
    legacy_baseline: "Legacy baseline",
    granot_created: "Created in Granot",
    unknown: "Unknown origin",
  },
  views: {
    title: "Move details",
    intro: "Three separate views. Nothing here changes the Lead.",
    originalHint: "What the Lead said when it first arrived.",
    current: "Current Lead fields",
    currentHint: "The Lead record as it stands now.",
    customer: "Customer said",
    customerHint: "What the customer stated in conversations, with its evidence.",
    none: "Not available for this subject.",
    customerNone: "No move details were stated in the retained conversations.",
    capturedAt: (time: string) => `Captured ${time}`,
    changedAt: (time: string) => `Changed ${time}`,
  },
  rows: {
    pickup: "Pickup", delivery: "Delivery", moveDate: "Move date", moveSize: "Move size", granotMoveSize: "Granot move size", cubicFeet: "Cubic feet",
    origin: "Arrived through", evidenceStatus: "Evidence status", sourceSystem: "Last changed by", level: "Level", confidence: "Confidence",
    freshness: "Freshness", applicability: "Applies", generated: "Generated", contextAsOf: "Context as of", latestConversation: "Latest conversation",
    inputMode: "Read from", schema: "Schema", rubric: "Rubric", model: "Model", conversations: "Conversations used", findings: "Findings used",
    sourceCoverage: "Source coverage", inventoryCoverage: "Model inventory coverage", status: "Status",
  },
  observationField: {
    pickup_location: "Pickup", delivery_location: "Delivery", move_date: "Move date", move_size: "Move size",
    service: "Services", access: "Access", money: "Budget and prices",
  },
  observationStatus: { stated: "Stated", conditional: "Conditional", changed: "Changed later", retracted: "Retracted" },
  inventory: {
    title: "Inventory",
    columns: { item: "Item", quantity: "Quantity", room: "Room", dimensions: "Dimensions", handling: "Handling", status: "Status", evidence: "Evidence" },
    none: "No inventory items were mentioned.",
    limitations: "Limitations",
    coverageNote: "Model inventory coverage is what the conversations covered. Source coverage is how much of the subject's history was read. They are reported separately.",
  },
  inventoryCoverage: { none: "None mentioned", partial: "Partial", customer_says_complete: "Customer says complete" },
  sourceCoverage: { complete: "All conversations read", partial: "Some conversations read", none: "No conversations read" },
  itemStatus: { included: "Included", excluded: "Excluded", conditional: "Conditional" },
  conflicts: { title: "Conflicts", none: "No conflicts were recorded." },
  coverage: { title: "Coverage", selected: (selected: number, available: number) => `${selected} of ${available}` },
  conditions: "Conditions",
  rationale: "Why",
  versions: {
    label: "Assessment version",
    intro: "Each version keeps its own time and inputs. An assessment and an analysis run are chosen separately and were not generated together.",
    none: "No stored versions.",
  },
  currentVersion: "Current",
  earlierVersion: "Earlier",
  shadow: "Shadow",
  shadowNote: "Shadow assessment: stored for review and not published to the card.",
  schemaVersion: (version: string) => `schema ${version}`,
  loading: "Loading the assessment…",
  failed: "Couldn't load the assessment.",
  notFound: "This Outreach record has no readable assessment.",
  noSubject: "There is no Outreach record here, so there is no subject to assess. Summary and findings are still available for the Number.",
  viewEvidence: (count: number) => (count === 1 ? "View evidence (1)" : `View evidence (${count})`),
  noEvidence: "No evidence cited",
  viewFullOutput: "View full output",
  provenance: "Where this assessment came from",
  summary: {
    title: "Summary & findings",
    noNumber: "This subject has no Contact Number, so there are no call analyses. The assessment can still be read.",
    scope: "Scope",
    source: "Source",
    sectionsTitle: "Summary",
    narrative: "Stored narrative (kept as written)",
    saidTitle: "What was said on the call",
    findingsTitle: (count: number) => `Findings (${count})`,
    findingsNone: "This analysis recorded no findings.",
    chainToggle: "Evidence chain and review",
    suggested: "Suggested next step — not applied",
    applied: "Applied actions",
    appliedNone: "No action from this analysis was applied to your work.",
    presentationFailed: "The readable summary is unavailable from this server, so the stored output is shown as recorded.",
    unavailable: {
      unavailable: "The content of this analysis is not available right now.",
      purged: "This analysis was removed under the retention rules.",
      unsupported: "This analysis was stored in a version this reader does not support.",
    },
    advanced: "Ask for another analysis",
    runLabel: "Analysis run",
    by: (speaker: string) => `Said by ${speaker}`,
  },
  scope: { conversation: "Conversation analysis — one call", number: "Number analysis — across calls" },
  evidence: {
    title: "Evidence",
    assessmentSource: "Assessment evidence",
    runSource: "Analysis evidence",
    sourcesLabel: "Evidence source",
    focused: (label: string) => `Showing the evidence for ${label}.`,
    showAll: "Show all evidence",
    back: (section: string) => `Back to ${section}`,
    missingIds: (count: number) => (count === 1 ? "1 cited item is not in this evidence list." : `${count} cited items are not in this evidence list.`),
    none: "No evidence is listed.",
    loading: "Loading evidence…",
    failed: "Couldn't load evidence.",
    openRecord: "Open record",
    openRun: "Open that analysis",
    openSnapshot: "Open kept item",
    closeSnapshot: "Close kept item",
    summaryNote: "Summary text from a stored conversation summary. It is not a transcript quote.",
    noText: "No inline text for this source.",
    unavailableSection: {
      unavailable: "Evidence is not available right now.",
      purged: "This evidence was removed under the retention rules.",
      unsupported: "This evidence was stored in a version this reader does not support.",
    },
    needsSource: "There is no assessment or analysis selected, so there is no evidence to show.",
  },
  evidenceAvailability: { retained: "Retained", purged: "Purged", missing: "Missing", partial: "Partial" },
  evidenceKind: {
    summary_section: "Summary section", said_on_call: "Said on the call", move_evidence: "Move evidence", legacy_summary_text: "Stored summary text",
    legacy_summary_section: "Stored summary section", finding: "Finding", lead_current: "Current Lead field", lead_ingested: "Lead as it first arrived",
    official_state: "Official record", owner_correction: "Your correction", transcript_quote: "Transcript quote", analysis_record: "Vantage record read by the analysis",
  },
  textLabel: { summary: "Summary text", quote: "Transcript quote kept by the analysis", finding: "Finding claim", other: "Text" },
  locator: {
    summaryArtifact: (section: string, conversation: string | null) => `Captured conversation summary · ${section || "whole summary"}${conversation ? ` · conversation ${conversation}` : ""}`,
    legacyRun: (run: string, section: string) => `Stored analysis ${run} · summary section ${section}`,
    conversationSummary: (conversation: string, section: string) => `Conversation ${conversation} summary · ${section}`,
    finding: (finding: string, revision: number | null) => `Finding ${finding}${revision === null ? "" : ` · revision ${revision}`}`,
    lead: (model: string, id: string, ingested: boolean, field: string) => `${model} ${id} · ${ingested ? "as it first arrived" : "current"} · ${field}`,
    official: (model: string, id: string, field: string) => `${model} ${id} · ${field}`,
    ownerCorrection: (revision: number | null) => `Your correction${revision === null ? "" : ` · revision ${revision}`}`,
    transcript: (segments: number, version: string | null) => `Call transcript · ${segments === 1 ? "1 line" : `${segments} lines`}${version ? ` · version ${version}` : ""}`,
    record: (type: string, id: string, fields: string[]) => `${type} ${id}${fields.length ? ` · ${fields.join(", ")}` : ""}`,
  },
  output: {
    title: "Full output",
    intro: "The complete retained structured output. Opening or copying it never starts model processing.",
    choose: "Output",
    none: "No retained output is available here yet.",
    loading: "Loading the output…",
    failed: "Couldn't load this output.",
    modelOutput: "Exact model output",
    accepted: "Accepted, server-expanded result",
    modelOutputHelp: "The exact object the model returned, as retained.",
    acceptedHelp: "The accepted envelope after server validation, including server-added scores and citation metadata.",
    acceptedOnly: "Exact model object not retained; showing the accepted, server-expanded result.",
    representation: "Representation",
    readable: "Readable",
    json: "Structured JSON",
    viewLabel: "Output view",
    copy: "Copy output",
    copied: "Copied the complete output.",
    copyFailed: "Couldn't copy automatically. The complete output is selected below; copy it with your keyboard.",
    details: "Details",
    schema: "Schema version",
    prompt: "Prompt version",
    model: "Model version",
    digests: "Digests",
    partial: "Partial: the retained object is incomplete. Nothing was reconstructed.",
    unavailableArtifact: "Unavailable",
    nothingRetained: "Nothing is retained for this output.",
    emptyValue: "empty",
    nullValue: "null",
    items: (count: number) => (count === 1 ? "1 item" : `${count} items`),
  },
  outputKind: {
    move_assessment: "Move assessment output", conversation_summary: "Conversation summary output", findings: "Findings output", legacy_analysis: "Analysis output",
  },
  expand: "Expand",
  restore: "Restore",
  expandLabel: "Expand the panel to the full window",
  restoreLabel: "Restore the panel to its usual width",
} as const;
