/**
 * Owner-facing strings for the analysis evidence chain.
 * Display only. Shaped like `copy` in sales-intelligence-copy.ts so these can be folded into it.
 * Nothing here may claim more than the stored run supports.
 */
export const evidenceChainCopy = {
  chain: {
    title: "Where this came from",
    intro: "Each claim is shown as a chain: the call it read, the evidence it kept, what the model said, what that changed in your work, and what you decided.",
    listLabel: "Model claims and their evidence",
    stepsLabel: "Chain of custody",
    steps: {
      source: "The call this read",
      evidence: "Evidence kept",
      claim: "What the model said",
      effect: "What it changed",
      decision: "Your decision",
    },
    show: (step: string) => `Show ${step.toLowerCase()}`,
    hide: (step: string) => `Hide ${step.toLowerCase()}`,
    claimsNone: "This analysis recorded no claims.",
    claimFallback: "Model claim",
    claimIndex: (position: number, total: number) => `Claim ${position} of ${total}`,
    openAlways: "Blocked outcomes and anything you retracted stay open.",
  },
  rows: {
    basis: "Where it came from",
    speaker: "Who said it",
    actionStatus: "What kind of action",
    clarity: "How clear it was",
    confidence: "Model confidence",
    tool: "How it was read",
    kept: "When it was kept",
    record: "Record",
    fields: "Fields read",
    followup: "Follow-up",
  },
  source: {
    oneConversation: "This analysis read one recorded conversation.",
    wholeNumber: "This analysis read the history on this Number, not one single call.",
    ranAt: (time: string) => `The model started at ${time}.`,
    finishedAt: (time: string) => `It finished at ${time}.`,
    notFinished: "It has not finished.",
    activityLink: "Open Number Activity",
    activityNote: "When the call happened, which way it went, and how it ended live on Number Activity.",
    transcriptVersion: (version: string) => `Transcript version ${version}.`,
    segments: (count: number) => (count === 1 ? "1 transcript line cited" : `${count} transcript lines cited`),
    modelUsed: (model: string, prompt: string) => `Model ${model}, prompt ${prompt}.`,
  },
  evidence: {
    none: "No retained evidence is cited for this claim.",
    cited: (count: number) => (count === 1 ? "1 kept item backs this claim." : `${count} kept items back this claim.`),
    open: "Open this item",
    close: "Close this item",
    transcript: "Call transcript",
    record: "Vantage record",
    unknownSource: "Recorded reference",
    readWith: (tool: string) => `Read with ${tool}`,
    keptAt: (time: string) => `Kept ${time}`,
    keptUnknown: "When it was kept is not recorded.",
    stored: "The original is still stored.",
    gone: "The original is no longer stored.",
    goneOn: (time: string) => `The original was removed ${time}.`,
    notInRun: "This item is not in the set this analysis kept.",
    quoteKept: "A quote was kept.",
    quoteNone: "No quote was kept.",
    recordRef: (type: string, id: string) => `${type} · ${id}`,
    showJson: "Show the recorded JSON",
    jsonNote: "This is the reference exactly as the model recorded it.",
    allTitle: "All evidence kept for this analysis",
    partial: "Only part of this item is shown.",
    retentionInProgress: "The original is being removed under the retention rules.",
    contentFailed: "Could not load this item.",
    firstPage: "Back to the first items",
    nextPage: "More kept items",
    startOfItem: "Back to the start of this item",
    nextSection: "More of this item",
  },
  claim: {
    basis: {
      said_on_call: "Heard on the call",
      vantage_record: "Read from a Vantage record",
      model_inference: "The model's own reading, not something said",
    },
    actor: {
      rep: "Said by a rep",
      customer: "Said by the customer",
      unknown: "Speaker unknown",
    },
    actionStatus: {
      requested: "The customer asked for it",
      promised: "Someone promised it",
      completed: "Claimed done",
      conditional: "Only if something else happens",
    },
    clarity: {
      clear: "Stated clearly",
      uncertain: "The model was not certain",
    },
    confidence: (value: string) => `Model confidence ${value}`,
    checksNote: "These check the claim's paperwork. They are not proof the claim is true.",
    checksLabel: {
      schema: "Shape",
      snapshots: "Evidence links",
      locator: "Quote",
      support: "Support",
    },
    schemaPass: "The claim matched the expected shape.",
    schemaFail: "The claim did not match the expected shape.",
    snapshotsPass: "Every cited item is in the set this analysis kept.",
    snapshotsFail: "At least one cited item is not in the set this analysis kept.",
    locator: {
      not_run: "The quote was not machine-checked.",
      located: "The quote was found in the transcript.",
      unlocated: "The quote could not be found in the transcript.",
      unknown: "The quote check is not recorded.",
    },
    support: {
      not_run: "Whether the evidence supports the claim was not machine-checked.",
      pass: "A check found the evidence supports the claim.",
      fail: "A check found the evidence does not support the claim.",
      unsure: "A check could not tell whether the evidence supports the claim.",
      unknown: "The support check is not recorded.",
    },
    headline: {
      unchecked: "Not machine-checked",
      checked: "Checks passed",
      problem: "A check did not pass",
    },
  },
  effect: {
    none: "This claim changed nothing in your work.",
    kind: {
      create_followup: "Added a follow-up",
      revise_followup: "Changed a follow-up",
      complete_followup: "Completed a follow-up",
      cancel_followup: "Cancelled a follow-up",
      assign: "Set who owns the work",
      set_contact_type: "Recorded how the call ended",
      mark_meaningful_contact: "Recorded a real conversation",
      pause_channel: "Paused a way of contacting",
      open_review: "Opened something for you to decide",
      open_number_review: "Opened this Number for you to decide",
      supersede: "Replaced an earlier claim",
    },
    status: {
      applied: "Applied to your work.",
      no_change: "Nothing changed. Your work already read this way.",
      blocked_owner: "Blocked. Your own correction wins.",
      blocked_identity: "Blocked. Which Lead this is was not settled.",
      blocked_closed: "Blocked. That work is closed.",
      blocked_restriction: "Blocked. Contacting this number is paused.",
      needs_review: "Left for you to decide.",
      stale: "Not applied. The work had already moved on.",
      unknown: "The outcome is not recorded.",
    },
    at: (time: string) => `Recorded ${time}`,
    reason: (reason: string) => `Reason recorded: ${reason}`,
    openWork: "Open this follow-up in Work",
    targetUnknown: "The follow-up it touched is not listed on this analysis.",
    untouched: "No follow-up is attached to this outcome.",
  },
  decision: {
    unreviewed: "You have not decided on this yet.",
    retracted: "You retracted this.",
    lockedRun: "Only the current analysis can be reviewed. This is an earlier one.",
    lookAgain: "Look at this again",
    lookAgainNote: "Asks for another analysis scoped to this claim. It uses the evidence already kept when that is still stored, and fresh context when it is not.",
    whatTheseDo: "What these do",
    decidedBy: (actor: string, time: string) => `Recorded by ${actor} at ${time}.`,
    whoWhere: "Who decided and when is listed under Review history below.",
    requestOnClaim: (time: string, status: string) => `You asked for another analysis on ${time} — ${status}.`,
  },
  rerun: {
    title: "Ask for another analysis",
    intro: "A new analysis does not delete this one. Both stay on record.",
    queued: "Processing may stay queued while AI is paused.",
    keptTitle: "Run again on the evidence already kept",
    keptNote: "Uses the evidence and prompt this analysis stored, plus only the corrections you tick.",
    keptUnavailable: "The kept evidence is gone, so running again on it is not available.",
    freshTitle: "Capture fresh context now",
    freshNote: "Reads this Number again as it stands today. It may see things this analysis never had.",
    needsOutput: "This analysis has no finished output to run again from.",
    scopedTo: (claim: string) => `Scoped to this claim: ${claim}`,
    requests: "Analyses you have asked for",
    requestsNone: "You have not asked for another analysis of this one.",
    requestLine: (mode: string, time: string, status: string) => `${mode} · asked ${time} · ${status}`,
  },
  run: {
    status: {
      queued: "Waiting to start.",
      running: "Running now.",
      submitted: "The model answered. The result is being applied.",
      completed: "Finished.",
      stale: "Replaced by a later analysis.",
      paused: "Paused.",
      failed: "Did not finish.",
      dead_letter: "Stopped after repeated failures. That is not a customer outcome.",
      unknown: "State not recorded.",
    },
    pickerLabel: "Choose an analysis",
    loading: "Loading analyses…",
    none: "No analysis has run on this Number yet.",
    newest: "Newest analyses",
    older: "Older analyses",
    detailFailed: "Couldn't load this analysis.",
    gone: "This analysis could not be opened. It may have been removed under the retention rules.",
    noOutput: "This analysis has no finished output, so there is nothing to read yet.",
    notFinishedYet: "This analysis has not finished, so there is nothing to read yet.",
    current: "Current analysis",
    earlier: "Earlier analysis",
    nextStep: "Suggested next step",
    nextStepWhy: (rationale: string) => `Why: ${rationale}`,
    instructions: "Your changes and what the model made of them",
    instructionsNone: "No changes of yours are recorded against this analysis.",
    instructionsTruncated: "Only the first 200 changes are shown.",
    instructionStale: "The model assessed an earlier version of this change.",
    historyTitle: "Review history",
    historyNote: "Every review decision, kept as it was recorded. Nothing here can be edited.",
    historyNone: "No review events are recorded.",
    historyNewest: "Newest review events",
    historyOlder: "Older review events",
    showJson: "Show the recorded JSON",
  },
  summaryLink: {
    fromRun: (time: string) => `This picture came from the analysis published at ${time}.`,
    noRun: "No analysis is recorded as the source of this picture.",
  },
} as const;
