/**
 * Owner-facing Sales Intelligence strings for the interim page: Numbers and RingCentral Accounts.
 * Display only — query params and server codes stay as they are. The Operations Registry Users tab and the
 * accept-invite page share the `ui2.users` / `ui2.acceptInvite` groups.
 */
export const copy = {
  page: {
    title: "Sales Intelligence",
    viewsLabel: "Sales Intelligence views",
    views: { numbers: "Numbers", reps: "RingCentral Accounts" },
    viewIntro: {
      numbers: "Every observed external number, with its calls, its attached Lead and that Lead's official status.",
      reps: "People in the stored RingCentral directory. Messaging a User never texts the customer.",
    },
  },
  /** The interim page for a Rep account (no Numbers browser, no reads). */
  repUnavailable: {
    title: "Sales Intelligence is being rebuilt",
    body: "It is not available for Rep accounts yet. Nothing here needs your action.",
    contact: "Ask the Owner if you need a call or Lead looked up.",
  },
  search: {
    placeholder: "Search phone, name or Job Number",
    label: "Search Numbers",
    hint: "Enter at least 4 digits to search by phone",
  },
  time: {
    notObserved: "Not observed",
    tz: "ET",
  },
  classification: {
    unknown: "Unclassified",
    customer: "Customer",
    company: "Our number",
    non_customer: "Not a customer",
  },
  classificationSoWhat: {
    unknown: "We have not classified this number yet. Unclassified is not a customer.",
    customer: "This looks like a customer number.",
    company: "This is one of our numbers, not a customer.",
    non_customer: "This number is not a customer.",
  },
  eligibility: {
    allowed: "Can contact",
    temporarily_blocked: "Paused",
    suppressed: "Do not call",
    unknown: "Contact status unknown",
  },
  eligibilitySoWhat: {
    allowed: "Calling this number is allowed right now.",
    temporarily_blocked: "A recorded restriction pauses calling or texting this number.",
    suppressed: "Do not call this number.",
    unknown: "We do not know yet whether we may call.",
  },
  contactType: {
    human_conversation: "Spoke with customer",
    voicemail: "Voicemail—speaker unknown",
    unknown: "Connected—contact unknown",
  },
  result: {
    missed: "Missed call",
    voicemail: "Voicemail",
    connected: "Connected",
    short: "Short call",
    transferred: "Transferred",
    no_answer: "No answer",
    busy: "Busy",
  },
  direction: { inbound: "Inbound", outbound: "Outbound", internal: "Internal" },
  attachment: {
    any: "Any",
    linked: "With attachments or candidates",
    unlinked: "Without attachments or candidates",
  },
  certainty: {
    exact: "Exact",
    likely: "Likely",
    unsure: "Unsure",
    owner_confirmed: "Confirmed by you",
    rejected: "Rejected",
  },
  attachmentState: {
    attached: "Attached",
    candidate: "Candidate",
    ambiguous: "Ambiguous",
  },
  restrictionState: {
    active: "Active",
    expired: "Expired",
    resolved: "Resolved",
  },
  /** The attached Lead's official status, in the server's precedence (Lead flags, then Booking and Cancellation). */
  official: {
    open_lead: "Open Lead",
    booked: "Booked",
    cancelled: "Cancelled",
    bad_lead: "Bad Lead",
    duplicate: "Duplicate Lead",
    no_sync: "Not synced",
  },
  fields: {
    classification: "Classification",
    leadMatch: "Lead match",
    activityFrom: "Activity from",
    activityTo: "Activity to",
    includeOurNumbers: "Include our numbers",
    lastActivity: "Last activity",
    unknown: "Unknown",
  },
  filters: {
    numbersTitle: "Filter numbers",
    numbersIntro: "Who the number is, whether a Lead is attached, and when it last had activity.",
    classificationHint: "Who this number is. Unclassified is not a customer.",
    leadMatchHint: "Attached Leads and suggested matches.",
    activityHint: "Last observed activity. Incomplete times are not sent.",
    includeOurHint: "Company lines stay hidden unless you include them.",
    hasRecording: "Has a provider recording",
    hasRecordingHint: "RingCentral reported at least one recording. The recording stays with RingCentral.",
    includeFormOnly: "Include form-only numbers",
    includeFormOnlyHint: "Numbers from a Form Lead that have no call yet.",
    close: "Close filters",
    appliedOne: "1 filter on",
    appliedMany: (n: number) => `${n} filters on`,
  },
  columns: {
    number: "Number",
    lead: "Lead",
    latestActivity: "Latest activity",
  },
  lead: {
    noLead: "No lead on file",
    calls: (n: number) => (n === 1 ? "1 call" : `${n.toLocaleString("en-US")} calls`),
    conversations: (n: number) => (n === 1 ? "1 conversation" : `${n.toLocaleString("en-US")} conversations`),
    inboundOutbound: (inbound: number, outbound: number) => `${inbound.toLocaleString("en-US")} in · ${outbound.toLocaleString("en-US")} out`,
  },
  actions: {
    open: "Open",
    filters: "Filters",
    clearFilters: "Clear filters",
    previous: "Previous",
    next: "Next",
    pages: "Pages",
    pageRange: (start: number, end: number) => `Showing ${start.toLocaleString("en-US")}–${end.toLocaleString("en-US")}`,
    retry: "Try again",
    cancel: "Cancel",
    closePanel: "Close panel",
    saving: "Saving…",
  },
  empty: {
    numbersNone: "No numbers match these filters.",
  },
  errors: {
    loadFailed: "Couldn't load this.",
    repsFailed: "Couldn't load RingCentral Accounts.",
  },
  sort: {
    label: "Sort by",
    direction: "Sort direction",
    switchTo: (next: string) => `switch to ${next}`,
  },
  provenance: {
    state: { attached_automatically: "Attached automatically" },
    soWhat: { attached_automatically: "The evidence was unambiguous, so this attached without you. You can still reject it." },
    decidedAt: (time: string) => `Decided ${time}`,
  },
  commandExplain: {
    confirm_attachment: "You are saying this Number belongs to this Lead. The official Lead, Booking, and Cancellation do not change.",
    reject_attachment: "You are saying this suggested match is wrong. Both records stay; the suggestion closes.",
    detach: "Removes the Number↔Lead link. Neither record is deleted.",
    find_lead: "Search is evidence to review. Searching does not attach.",
  },
  panel: {
    returnHere: "Return to Sales Intelligence",
  },
  numbers: {
    coverageLine: (asOf: string, through: string | null) => `As of ${asOf} · ${through ? `History known through ${through}` : "History completeness unknown"}`,
    gaps: (n: number) => (n === 1 ? "1 known gap in call history" : `${n.toLocaleString("en-US")} known gaps in call history`),
    formOnly: "From a Form Lead · no call yet",
    attachedLead: "Attached Lead",
    multipleLeads: "More than one Lead is attached. Review the matches.",
    noAttachedLead: "No Lead attached",
    leadGone: "The attached Lead is no longer on file.",
    openLead: "Open official Lead",
    openBooking: "Open Booking",
    openCancellation: "Open Cancellation",
    jobNo: (job: string) => `Job ${job}`,
    detailTitle: (e164: string) => `Number ${e164}`,
    detailTitleUnknown: "Number",
    tabs: { activity: "Calls and messages", matches: "Lead matches", details: "Details" },
    facts: {
      providerNames: "Names from RingCentral",
      noProviderName: "No caller name reported",
      firstObserved: "First observed",
      lastActivity: "Last activity",
      lastInbound: "Last inbound call",
      lastOutbound: "Last outbound call",
      lastConversation: "Last human conversation",
      calls: "Calls",
      conversations: "Human conversations",
      recordings: "Provider recordings",
      createdVia: "First seen from",
      createdViaWord: { call: "A call", form_lead: "A Form Lead" } as Record<string, string | undefined>,
      connections: "Lead matches recorded",
      connectionsLine: (attached: number, candidate: number, ambiguous: number, rejected: number) =>
        `${attached} attached · ${candidate} candidate · ${ambiguous} ambiguous · ${rejected} rejected`,
      recount: (stored: number, fresh: number) => `Stored count ${stored.toLocaleString("en-US")} · fresh recount ${fresh.toLocaleString("en-US")}`,
    },
    restrictions: {
      title: "Contact restrictions",
      none: "No contact restrictions recorded.",
      line: (channels: string, state: string, until: string | null) => `${channels} · ${state} · ${until ? `Until ${until}` : "No end date recorded"}`,
      origin: { owner: "Recorded by you", intelligence: "Recorded by the retired analysis (kept as history)" } as Record<string, string | undefined>,
      readOnly: "Restrictions are read-only here for now.",
    },
    rebuild: {
      action: "Recount this Number",
      title: "Recount this Number",
      explain: "Recounts calls and Lead matches from the stored call records. It changes no call, Lead or Booking.",
      blocked: (codes: string) => `Not available: ${codes}`,
    },
    timeline: {
      empty: "No calls or Lead messages observed in available history.",
      loadOlder: "Load older activity",
      failed: "Couldn't load calls and messages.",
      call: (direction: string) => `${direction} call`,
      leadMessage: "Message to the Lead",
      duration: "Duration",
      rep: "Rep",
      repStatus: {
        unreviewed: "Extension not yet reviewed",
        excluded_role: "Not a sales extension",
        no_extension: "No extension on this call",
      } as Record<string, string | undefined>,
      extension: (n: string) => `ext. ${n}`,
      legs: "Call legs",
      legsMore: (n: number) => `${n} more ${n === 1 ? "leg" : "legs"} not shown`,
      recordings: (n: number) => (n === 1 ? "1 provider recording" : `${n} provider recordings`),
      provisional: "Still settling with RingCentral",
      observedLate: (time: string) => `Observed ${time}`,
      messageStatus: (status: string) => `Status: ${status}`,
      sentAt: (time: string) => `Sent ${time}`,
      deliveredAt: (time: string) => `Delivered ${time}`,
    },
  },
  reps: {
    title: "RingCentral Accounts",
    excludedOwner: "The owner extension is omitted. Message a current directory User from this list; it never goes to the customer.",
    metricsUnavailable: "Call metrics stay unavailable until a reviewed identity exists. You can still message a current directory User from this list.",
    none: "No RingCentral Users besides the owner are stored for this page.",
    noAgent: "No attached Agent",
    message: "Message",
    messagePlaceholder: "Write the message to send.",
    reviewChannels: "This review records pager on the link. SMS-to-rep is included only when the stored directory snapshot has exactly one DID. Team Messaging person ids stay unresolved. This establishes reviewed identity; it sends no message.",
    channelsPager: "Channels to record: pager.",
    channelsPagerSms: "Channels to record: pager and SMS-to-rep (exactly one stored DID).",
  },
  messageRep: {
    title: "Message",
    directoryOnly: "This message goes to the selected RingCentral User. It is internal review context and never goes to the customer.",
    channel: "Channel",
    body: "Message",
    send: "Send",
    noChannel: "none from stored evidence",
    rejected: "The server rejected this request:",
    checkEntries: "Check the User, channel, and message.",
    statusSent: "Sent. The provider accepted the message. That is not evidence the rep worked the customer.",
    statusFailed: "Failed. Submission did not begin or was rejected. Do not treat this as sent.",
    statusUnknown: "Unknown. Delivery could not be established. Retry uses the same request. Do not invent a new key.",
    statusPending: "Pending. Authorized intent only; delivery is not established.",
    statusFallback: "Sent via pager fallback. The provider accepted the fallback. That is not evidence of customer work.",
  },
  ui1: {
    prim: {
      loadFailed: "Couldn't load this.",
      tryAgain: "Try again",
      errorCode: "Error code",
      loading: "Loading…",
      refreshing: "Refreshing",
      live: {
        connecting: "Connecting…",
        live: "Live",
        reconnecting: "Reconnecting…",
        offline: "Offline",
        updated: (t: string) => `Updated ${t}`,
        refresh: "Refresh",
        refreshLabel: "Refresh everything on this page",
        title: "Live updates",
        note: "Live means new calls are arriving. It does not mean history is complete.",
        historyThrough: (t: string) => `History known through ${t}`,
        historyUnknown: "History coverage not known yet",
        healthUnknown: "Capture status not known yet.",
        healthWord: { ok: "Healthy", attention: "Needs attention", broken: "Broken" },
        healthSentence: {
          ok: "Calls are being captured normally.",
          attention: "Some calls may be missing or late. Check capture health on Numbers before trusting counts.",
          broken: "Call capture has stopped. Recent calls are missing until it's repaired.",
        },
        captureStatus: "Capture",
      },
      routeTabsLabel: "Sections",
    },
    coverage: {
      title: "Capture health",
      status: {
        ok: "Call capture is healthy.",
        attention: "Call capture needs attention.",
        broken: "Call capture is broken. Calls may be missing until it's repaired.",
      } as Record<string, string | undefined>,
      statusOther: (status: string) => `Call capture status: ${status}.`, // draft: a status value the copy doesn't know
      reason: {
        webhook_down: () => "The RingCentral webhook isn't delivering.",
        webhook_degraded: () => "The RingCentral webhook has been silent for 30 staffed minutes while calls were logged.",
        quarantine: (n: number) => (n === 1 ? "1 Call Log record is quarantined." : `${n.toLocaleString("en-US")} Call Log records are quarantined.`),
        quarantine_over_24h: () => "A Call Log record has been quarantined for more than 24 hours.",
        pending_finalization: (n: number) =>
          n === 1 ? "1 call started more than 10 minutes ago hasn't ended." : `${n.toLocaleString("en-US")} calls started more than 10 minutes ago haven't ended.`,
      } as Record<string, ((n: number) => string) | undefined>,
      reasonsLabel: "Reasons", // draft: the reason list's accessible name
      pendingExplain: "Calls in progress for more than 10 minutes. A long live call counts here until it ends.",
      knownThrough: "History known through",
      knownUnknown: "History coverage unknown",
      callLogTitle: "Call Log", // draft: sub-heading
      syncMode: (mode: string) => `Call Log sync: ${mode}`,
      syncModeWord: { off: "off", shadow: "shadow", on: "on" } as Record<string, string | undefined>,
      quarantine: (n: number) => `Quarantined: ${n.toLocaleString("en-US")}`,
      quarantineOldest: "oldest",
      lastSweep: (n: number) => (n === 1 ? "Last sweep recovered 1 call" : `Last sweep recovered ${n.toLocaleString("en-US")} calls`),
      neverSwept: "Never swept",
      webhookTitle: "Webhook", // draft: sub-heading
      webhook: {
        state: { healthy: "Webhook healthy", degraded: "Webhook degraded", down: "Webhook down", off: "Webhook off" } as Record<string, string | undefined>,
        stateOther: (state: string) => `Webhook ${state}`, // draft
        subscription: (suffix: string) => `subscription …${suffix}`,
        lastReceipt: "last receipt",
        noReceipt: "no receipt yet", // draft: `last_receipt_at: null`
        receipts1h: (n: number) => (n === 1 ? "1 receipt in the last hour" : `${n.toLocaleString("en-US")} receipts in the last hour`),
        renewalError: (error: string) => `last renewal error: ${error}`,
        subscriptionMissing: "The renewal job can't recognise its own subscription, so it reports it missing. Capture itself is working.",
      },
      callsTitle: "Calls now", // draft: sub-heading
      inProgress: (n: number) => (n === 1 ? "1 call in progress" : `${n.toLocaleString("en-US")} calls in progress`),
      pendingFinalization: (n: number) => `${n.toLocaleString("en-US")} pending finalization`,
      unmappedNumbers: (n: number) => (n === 1 ? "1 inbound company number not mapped" : `${n.toLocaleString("en-US")} inbound company numbers not mapped`),
      unmappedUsers: (n: number) => (n === 1 ? "1 directory User without a reviewed Agent" : `${n.toLocaleString("en-US")} directory Users without a reviewed Agent`),
      directorySync: "directory synced",
      directoryMissing: "no stored directory",
    },
  },
  ui2: {
    /** The Rep frame: brand subtitle and sign out. */
    shell: {
      title: "Sales Intelligence",
      signedInAs: (email: string) => `Signed in as ${email}`,
      signOut: "Sign out",
    },
    /** UI2-USERS (UI-2 §8): the Owner's Users tab in the Operations Registry. */
    users: {
      tab: "Users",
      title: "Users",
      intro: "Who can sign in to the admin, and what they can reach. Reps can sign in, but Sales Intelligence is being rebuilt and is not available to Rep accounts yet.",
      columns: { email: "Email", role: "Role", agent: "Agent", active: "Status", invite: "Invite", actions: "Actions" },
      role: { owner: "Owner", admin: "Admin", rep: "Rep" } as Record<string, string>,
      roleHint: { owner: "Everything, including users.", admin: "Operations pages; no Sales Intelligence.", rep: "Can sign in; Sales Intelligence is not available to Rep accounts yet." } as Record<string, string>,
      active: "Active",
      inactive: "Deactivated",
      noAgent: "—",
      unknownAgent: "Agent not found",
      invite: {
        none: "No invite",
        pending: (t: string) => `Invite expires ${t}`,
        accepted: "Invite accepted",
        expired: "Invite expired",
        revoked: "Invite cancelled",
      },
      actions: { add: "Add user", edit: "Edit", setPassword: "Set password", deactivate: "Deactivate", invite: "Send invite", more: "More actions" },
      form: {
        addTitle: "Add a user",
        editTitle: (email: string) => `Edit ${email}`,
        email: "Email",
        role: "Role",
        agent: "Agent",
        agentHint: "Required for a rep. Only active Agents not linked to another active rep are listed.",
        agentPlaceholder: "Choose an Agent",
        noAgentsFree: "Every active Agent is already linked to an active rep.",
        access: "How they sign in",
        accessPassword: "Set a password now",
        accessInvite: "Send an invite link",
        password: "Password",
        passwordPolicy: "At least 10 characters, up to 72 bytes.",
        activeLabel: "Active",
        save: "Save",
        create: "Add user",
        cancel: "Cancel",
      },
      setPassword: {
        title: (email: string) => `Set a password for ${email}`,
        body: "This signs them out everywhere. Tell them the new password yourself.",
        confirm: "Set password",
        done: (email: string) => `Password set for ${email}. They were signed out everywhere.`,
      },
      deactivate: {
        title: (email: string) => `Deactivate ${email}?`,
        body: "They're signed out at their next request and can't sign in again until you reactivate them in Edit.",
        confirm: "Deactivate",
        done: (email: string) => `${email} is deactivated.`,
      },
      inviteResult: {
        sent: (email: string, t: string) => `Invite emailed to ${email}. It expires ${t}.`,
        notEmailed: (reason: string) => `Not emailed: ${reason}`,
        reason: {
          not_configured: "no mail sender is set up. Copy the link and send it yourself.",
          failed: "the mail sender refused it. Copy the link and send it yourself.",
          unreachable: "the mail sender couldn't be reached. Copy the link and send it yourself.",
        } as Record<string, string>,
        expires: (t: string) => `The link expires ${t}.`,
        copy: "Copy link",
        copied: "Copied",
        linkLabel: "Invite link",
      },
      errors: {
        agent_required: "A rep needs a linked Agent.",
        agent_taken: "That Agent is already linked to another active rep.",
        agent_inactive: "That Agent is inactive. Choose an active Agent.",
        email_taken: "A user with this email already exists.",
        last_owner: "This is the last active Owner. Add another Owner before you change or deactivate this one.",
        invalid_input: "Check the fields and try again.",
        forbidden: "Only the Owner can manage users.",
        not_found: "This user no longer exists. Refresh the list.",
        unauthorized: "Your session ended. Sign in again.",
        user_inactive: "This user is deactivated. Reactivate them in Edit first.",
        generic: "Couldn't save this. Try again.",
        not_configured: "Invite links aren't set up on this admin yet (ADMIN_PUBLIC_BASE_URL). Set a password instead.",
        agent_check_unavailable: "Couldn't check the Agent right now. Try again in a minute.",
        agent_not_allowed: "Only a rep is linked to an Agent.",
        user_changed: "Someone else changed this user. Refresh the list and try again.",
      } as Record<string, string>,
      fieldErrors: { email: "Enter a valid email.", password: "At least 10 characters, up to 72 bytes.", agent: "Choose an Agent for a rep." } as Record<string, string>,
      empty: "No users yet.",
      loadError: "Couldn't load users.",
      errorCode: "Error code",
      tryAgain: "Try again",
      actionsFor: (email: string) => `Actions for ${email}`,
      created: (email: string) => `${email} added.`,
      saved: (email: string) => `Saved ${email}.`,
      inviteAfterCreate: (sentence: string) => `The user was added, but the invite wasn't sent: ${sentence}`,
      agentsLoadError: "Couldn't load the Agent list.",
      agentInactive: (name: string) => `${name} (inactive)`,
      inviteResultTitle: "Invite link",
      done: "Done",
      tableLabel: "Admin users",
    },
    /** UI2-USERS: the public accept-invite page (`/accept-invite#token=…`). */
    acceptInvite: {
      title: "Set your password",
      intro: "Choose a password for your Vantage admin account.",
      password: "Password",
      confirm: "Password again",
      policy: "At least 10 characters, up to 72 bytes.",
      submit: "Set password",
      submitting: "Setting…",
      success: "Password set. Sign in with your email and new password.",
      signIn: "Go to sign in",
      states: {
        malformed: "This invite link isn't complete. Open the link from your invite again, or ask the Owner for a new one.",
        invalid: "This invite link was already used or has expired. Ask the Owner for a new one.",
        weak: "Use at least 10 characters, up to 72 bytes.",
        mismatch: "The two passwords don't match.",
        generic: "Couldn't set your password. Try again.",
      },
    },
  },
} as const;
