/**
 * Owner-facing Sales Intelligence strings.
 * Display only — query params and server codes stay as they are.
 */
export const BANDS = {
  1: "Promised callbacks overdue",
  2: "No call yet after form submission",
  3: "Missed calls with no callback",
  4: "Follow-ups due",
  5: "Being worked, but no next step",
  6: "Open work nobody owns",
  7: "Going cold",
} as const;

export const copy = {
  page: {
    title: "Sales Intelligence",
    searchPlaceholder: "Search phone, name, or Job Number",
    searchHint: "Phone searches need at least 4 digits",
    viewsLabel: "Sales Intelligence views",
    views: { attention: "Needs attention", numbers: "Numbers", reps: "Reps" },
    countsDistinct: "These counts are distinct subjects, not a sum of reasons.",
    pendingProjection: "Attention is being prepared. Counts are not yet available.",
    detailTitle: "Number / Outreach detail",
    messagingUnavailable: "Rep messaging is unavailable in this preview.",
  },
  live: {
    connecting: "Connecting…",
    live: "Live",
    reconnecting: "Reconnecting…",
    liveNote: "Live means new calls are arriving. It does not mean history is complete.",
  },
  coverage: {
    knownThrough: (time: string) => `History known through ${time}`,
    unknown: "History completeness unknown",
    asOf: (time: string) => `As of ${time}`,
  },
  bands: BANDS,
  needsReview: { title: "Needs review" },
  reasons: {
    promised_callback_overdue: "Promised callback is overdue",
    no_call_yet: "No call yet after form submission",
    missed_call_no_callback: "Missed call with no callback",
    followups_due: "Follow-up is due",
    no_next_step: "Being worked, but no next step",
    missing_responsibility: "Open work nobody owns",
    going_cold: "Going cold",
  },
  reviewCause: {
    identity: "Identity unclear",
    missing_date: "Due date needed",
    restriction: "Contact restriction",
    unclear_commitment: "Unclear commitment",
    missing_responsibility: "Rep identity or action responsibility missing",
    official_mismatch: "Possible missing Booking or payment",
    owner_conflict: "Model disagrees with Owner",
    closed_work_request: "New request on closed work",
    completion_target: "Suggested closure",
  },
  outreachState: {
    unworked: "Unworked",
    open: "Open",
    waiting_on_customer: "Waiting on customer",
    identity_review: "Needs identity",
    closed: "Closed",
  },
  classification: {
    unknown: "Unclassified",
    customer: "Customer",
    company: "Our number",
    non_customer: "Not a customer",
  },
  eligibility: {
    allowed: "Can contact",
    temporarily_blocked: "Paused",
    suppressed: "Do not call",
    unknown: "Contact status unknown",
  },
  contactType: {
    human_conversation: "Spoke with customer",
    voicemail: "Voicemail—speaker unknown",
    unknown: "Connected—contact unknown",
  },
  result: {
    missed: "Missed call",
    voicemail: "Voicemail",
    connected: "Connected",
    short: "Short call",
    transferred: "Transferred",
    no_answer: "No answer",
    busy: "Busy",
  },
  direction: { inbound: "Inbound", outbound: "Outbound", internal: "Internal" },
  followupKind: {
    call: "Call",
    text: "Text the customer",
    send_estimate: "Send estimate",
    check_availability: "Check availability",
    review: "Review",
    wait: "Wait",
    reconcile_identity: "Sort out which lead",
    other: "Other",
  },
  followupOrigin: {
    owner: "Set by you",
    rep_promise: "Rep promise",
    customer_request: "Customer request",
    customer_wait: "Customer wait",
    system_default: "System",
  },
  attachment: {
    any: "Any",
    linked: "With attachments or candidates",
    unlinked: "Without attachments or candidates",
  },
  signals: { overdue: "Overdue", noOwner: "No one owns this" },
  time: {
    notObserved: "Not observed",
    dueDateNeeded: "Due date needed",
    noDueRecorded: "No due date recorded",
    due: (t: string) => `Due ${t}`,
    snoozedUntil: (t: string) => `Snoozed until ${t}`,
    dueAndSnoozed: (due: string, until: string) => `Due ${due} · snoozed until ${until}`,
    ago: (wall: string) => `${wall} ago`,
    agoStaffed: (wall: string, staffed: string) => `${wall} ago (${staffed} staffed)`,
    tz: "ET",
  },
  fields: {
    band: "Band",
    allBands: "All bands",
    status: "Status",
    any: "Any",
    rep: "Rep",
    anyRep: "Any rep",
    classification: "Classification",
    leadMatch: "Lead match",
    activityFrom: "Activity from",
    activityTo: "Activity to",
    includeOurNumbers: "Include our numbers",
    lastMeaningfulContact: "Last meaningful contact",
    lastActivity: "Last activity",
    promisedBy: "Promised by",
    assignedTo: "Assigned to",
    outreachOwnedBy: "Outreach owned by",
    unassigned: "Unassigned",
    unknown: "Unknown",
  },
  filters: {
    attentionTitle: "Filter attention",
    attentionIntro: "Show one category, subjects that need your decision, a status, or a specific rep.",
    numbersTitle: "Filter numbers",
    numbersIntro: "Who the number is, whether a Lead is attached, and when it last had activity.",
    bandHint: "Each subject appears once, under its highest category.",
    needsReviewHint: "Only subjects waiting on your decision.",
    statusHint: "Current Outreach state.",
    repHint: "Promised by, assigned to, or Outreach owner.",
    classificationHint: "Who this number is. Unclassified is not a customer.",
    leadMatchHint: "Attached Leads and suggested matches.",
    activityHint: "Last observed activity. Incomplete times are not sent.",
    includeOurHint: "Company lines stay hidden unless you include them.",
    close: "Close filters",
    appliedOne: "1 filter on",
    appliedMany: (n: number) => `${n} filters on`,
  },
  columns: {
    number: "Number",
    lead: "Lead",
    latestActivity: "Latest activity",
  },
  lead: {
    noLead: "No lead on file",
    conversations: (n: number) => (n === 1 ? "1 conversation" : `${n} conversations`),
    interactions: (n: number) => (n === 1 ? "1 interaction" : `${n} interactions`),
  },
  numbers: {
    sortedByActivity: "Sorted by latest activity",
  },
  actions: {
    open: "Open",
    filters: "Filters",
    clearFilters: "Clear filters",
    loadMore: "Load more",
    firstPage: "First page",
    retry: "Try again",
    cancel: "Cancel",
    closePanel: "Close panel",
    search: "Search",
    save: "Save",
    saving: "Saving…",
    retrySame: "Retry same request",
  },
  empty: {
    attentionComplete: "Nothing needs attention right now",
    attentionGaps: "Nothing needs attention in what we can see",
    numbersNone: "No numbers match these filters",
    reviewsNone: "No review decisions recorded for this subject.",
    followupsNone: "No active follow-ups recorded.",
  },
  errors: {
    loadFailed: "Couldn't load this.",
    pageFailed: "Couldn't load more. What's shown is still current.",
    numbersFailed: "Couldn't load these numbers.",
    reviewsFailed: "Couldn't load review decisions.",
    repsFailed: "Couldn't load Rep links.",
    analysisFailed: "Couldn't load analysis history.",
    evidenceFailed: "Couldn't load evidence.",
  },
  panel: {
    runningSummary: "Running summary",
    runningSummaryEmpty: "No completed analysis available.",
    analysisTitle: "Analysis and Owner review",
    outreach: "Outreach",
    followups: "Follow-ups",
    completedFollowups: "Completed and cancelled follow-ups",
    originalEvidence: "Original evidence",
    locatorProvided: "AI-provided reference",
    locatorNotChecked: "Location not checked",
    suggestionNote: "Suggested next step — not a promise and not scheduled.",
    originalUnavailable: "Original evidence is unavailable",
    confirmedByYou: "Confirmed by you",
    correctedByYou: "Corrected by you",
    cannotDetermine: "Cannot determine",
    confirm: "Confirm",
    correct: "Correct",
    retract: "Retract",
    apply: "Apply",
    confirmAnalysis: "Confirm analysis",
    reanalyzeOriginal: "Re-analyze original evidence",
    reanalyzeCurrent: "Re-analyze current context",
  },
  commands: {
    mark_worked: "Mark as worked",
    assign: "Assign responsible rep",
    set_waiting: "Wait for customer",
    add_note: "Add note",
    close: "Close",
    reopen: "Reopen",
    create_followup: "Add next step",
    patch_followup: "Edit follow-up / assignment",
    complete_followup: "Complete follow-up",
    snooze_followup: "Snooze",
    cancel_followup: "Cancel follow-up",
  },
  analysisTitles: {
    confirm_run: "Confirm this analysis",
    confirm_finding: "Confirm this finding",
    correct_finding: "Correct this finding",
    retract_finding: "Retract this finding",
    apply_suggestion: "Apply suggestion",
    original_evidence: "Re-analyze original evidence",
    current_context: "Re-analyze current context",
  },
  reps: {
    title: "Reps",
    accountLabel: "RingCentral account ID",
    load: "Load stored Rep links",
    accountHint: "Enter the account whose stored directory you want to review. Account discovery is not supplied by the current API.",
    metricsUnavailable: "Rep metrics are unavailable. Reviewed identity is required for attribution. Messaging remains disabled.",
    none: "No Rep links recorded for this page.",
  },
} as const;

export type SiView = keyof typeof copy.page.views;
export type Band = keyof typeof BANDS;
