/**
 * Owner-visible strings of Setup → Lead costs and the feed's Lead cost sheet (doc 19). Glossary words only: Feed,
 * Lead source, Lead cost. Every string passes `lib/operations-registry/ownerLanguageDeck.ts`; no command names, no ids.
 */
export const LEAD_COSTS_COPY = {
  views: { grid: "Grid", fix: "Fix past leads", old: "Old rate book" },
  viewsLabel: "Lead costs views",

  grid: {
    title: "What each feed costs per lead",
    subtitle: "Type a new amount on any row, pick one start date, and save once. Leads already received keep the cost they have; use Fix past leads to change those.",
    columns: { company: "Company", feed: "Feed", channel: "Channel", current: "Current", since: "Since", next: "New amount" },
    channel: { form: "Web form", call: "Phone calls" },
    local: { local: "Local", long_distance: "Long distance" },
    missing: "Missing",
    missingHint: "No lead cost yet. A feed cannot go live without one.",
    recordedTwice: "Needs a look",
    recordedTwiceHint: "A $0.00 amount is recorded twice for this feed. Open its lead cost sheet to fix it.",
    notNeeded: "Not needed",
    sinceUnknown: "Not shown",
    inputLabel: (feed: string) => `New lead cost for ${feed}`,
    inputPlaceholder: "No change",
    offToggle: (count: number) => `Feeds that are off (${count})`,
    offHide: "Hide feeds that are off",
    empty: "No feeds yet. Add a lead source and its feeds first, then price them here.",
    loading: "Loading lead costs",
    readFailure: "Lead costs did not load.",
    noCompany: "Other lead source",
  },

  save: {
    dateLabel: "Starts on (New York date)",
    dateHint: "Applies to every row you changed. Leads before this date keep their cost.",
    reasonLabel: "Reason (optional)",
    button: (count: number) => (count > 0 ? `Save ${count} ${count === 1 ? "change" : "changes"}` : "Save"),
    nothingToSave: "Change an amount to save.",
    saving: "Saving",
    saved: "Lead costs saved.",
    savedFrom: (date: string) => `Lead costs saved. They apply to leads from ${date} on.`,
    invalidAmounts: (count: number) => `${count} ${count === 1 ? "amount is" : "amounts are"} not valid and will be skipped. Use $0 or more.`,
    staleRevision: "Someone changed a lead cost after you opened this page. The amounts were reloaded. Check them and save again.",
    stalePreview: "The lead cost changed after the preview. Preview again before you confirm.",
  },

  fix: {
    title: "Fix past leads",
    subtitle: "Re-price leads you already received. This rewrites the cost stored on each lead, which a new lead cost above never does.",
    notice: "Usual order: set the right lead cost first, then preview here, then confirm. Confirming locks in the preview; if the lead cost changes afterward, preview again. A job covers up to 366 days and 250 reviewed leads, so split a bigger fix into several.",
    feedLabel: "Feed",
    fromLabel: "From",
    untilLabel: "Until",
    reasonLabel: "Reason (optional)",
    preview: "Preview impact",
    previewing: "Previewing",
    confirm: "Confirm the fix",
    confirming: "Starting",
    cancel: "Cancel the job",
    repreview: "Preview again",
    started: "The fix started. This page follows it until it finishes.",
    cancelled: "The job was cancelled.",
    previewTitle: "Preview",
    matched: "Leads in the window",
    wouldChange: "Would change",
    wouldNoChange: "Already right",
    forms: "Web form leads",
    calls: "Phone call leads",
    sampleTitle: "A few examples",
    sampleLine: (kind: string, from: string, to: string, noChange: boolean) => `${kind} lead · ${from} to ${to}${noChange ? " · no change" : ""}`,
    leadKind: { form: "Web form", call: "Phone call" },
    jobTitle: "The fix",
    jobStatus: {
      pending: "Waiting to start",
      processing: "Running",
      completed: "Finished",
      failed: "Failed",
      cancelled: "Cancelled",
    },
    jobCounts: (changed: number, same: number, failed: number) => `Changed ${changed} · Already right ${same} · Failed ${failed}`,
    empty: "No feeds to fix yet.",
    readOnly: "You can look at this page. Only the owner can start a fix.",
  },

  old: {
    title: "Old rate book · read-only",
    subtitle: "Lead costs above are what the dashboard uses. This is the earlier list, kept for reference.",
    loading: "Loading the old rate book",
    readFailure: "The old rate book did not load.",
    empty: "The old rate book is empty.",
    columns: { company: "Company", slot: "Lead type", amount: "Amount" },
    slot: { forms: "Web forms", locals: "Local moves", inbounds: "Phone calls" },
  },

  sheet: {
    title: (source: string, feed: string) => `Lead cost · ${source} · ${feed}`,
    loading: "Loading this lead cost",
    readFailure: "This lead cost did not load.",
    current: "Current lead cost",
    since: (date: string) => `since ${date}`,
    sinceUnknown: "start date not shown",
    missing: "Missing. This feed cannot go live until it has a lead cost.",
    recordedTwice: "A $0.00 amount is recorded twice. Set a new amount below.",
    notNeeded: "Not needed for this feed.",
    newBlock: "New amount",
    amountLabel: "Amount per lead",
    dateLabel: "Starts on (New York date)",
    scopeLabel: "Which leads does this change?",
    scopeFromDate: "Starting from a date",
    scopeAll: "All leads, past and future",
    scopeAllHint: (start: string) => `Re-prices every lead from ${start} on.`,
    repriceNote: "Analytics, Today and the Outreach Desk re-price leads from this date as soon as you save.",
    reasonLabel: "Reason (optional)",
    save: "Save new lead cost",
    saving: "Saving",
    saved: "Lead cost saved.",
    nothingToSave: "Enter a different amount to save.",
    periodsBlock: "Periods",
    periodsSummary: "Every amount this feed has had, and the ways to change them",
    periodsNote: "These edits change the lead cost used for new leads only. Dates are New York dates. Leads already received keep their cost until you fix them.",
    past: "Past",
    now: "Now",
    later: "Later",
    none: "None",
    open: "open ended",
    periodLine: (amount: string, from: string, until: string | null) => `${amount} · from ${from}${until ? ` to ${until}` : " · open ended"}`,
    ops: {
      add_future: {
        label: "Add a new amount from a date",
        hint: "The amount now in force ends the day before, and the new amount runs from that date on.",
      },
      split: {
        label: "Split a period at a date",
        hint: "The earlier part keeps its amount. The later part gets the new amount and the same end.",
      },
      replace_schedule: {
        label: "Replace the whole schedule",
        hint: "Throws away every period above and installs the ones you list. Use only when a smaller change will not do.",
      },
      correct_period: {
        label: "Correct a past period",
        hint: "Changes the amount of one period without moving its dates. Leads already received are not touched; fix them afterward.",
      },
    },
    periodPicker: "Which period",
    periodPlaceholder: "Pick a period",
    effectiveDate: "Date",
    correctAmount: "Right amount",
    reasonCorrect: "Reason",
    rowFrom: "From",
    rowUntil: "Until (leave empty to stay open)",
    rowAmount: "Amount",
    addRow: "Add a period",
    removeRow: "Remove",
    run: "Apply",
    running: "Applying",
    applied: "The schedule was updated.",
    staleRevision: "This lead cost changed after you opened it. It was reloaded. Check it and apply again.",
    fixLink: "Fix past leads",
    fixHint: "Changing a lead cost does not change leads you already received.",
    readOnly: "You can look at this lead cost. Only the owner can change it.",
    close: "Close",
  },
} as const;
