import test from "node:test";
import assert from "node:assert/strict";
import { bandLabel, classificationLabel, contactTypeLabel, eligibilityLabel, formatAge, formatSuppliedAge, label, leadMatchSummary, reviewCauseCardLabel, reviewCauseLabel } from "../../components/sales-intelligence/lib/format";
import { copy } from "../../components/sales-intelligence/sales-intelligence-copy";
import { ownershipPhrase, ownerlessLabel } from "../../components/sales-intelligence/ownership";
import { parseSiPanel, parseSiView, SI_PANEL_TABS, SI_VIEW_TABS } from "../../components/sales-intelligence/sales-intelligence-tabs";

test("owner labels use design sentences for server attention codes", () => {
  assert.equal(label("promised_callback_overdue"), "Promised callback is overdue");
  assert.equal(label("no_call_yet"), "No call yet after form submission");
  assert.equal(label("followups_due"), "Follow-up is due");
  assert.equal(label("missing_responsibility"), "Open work nobody owns");
  assert.equal(reviewCauseLabel("missing_responsibility"), "Rep identity or action responsibility is missing");
  assert.equal(reviewCauseCardLabel("missing_responsibility"), "Missing owner");
  assert.equal(reviewCauseCardLabel("identity"), "Identity unclear");
  assert.equal(reviewCauseLabel("restriction"), "Calling is paused until you decide");
  assert.equal(label("restriction"), "Calling paused");
  assert.equal(bandLabel(2), "No call yet after form submission");
  assert.equal(label("identity_review"), "Needs identity");
  assert.equal(label("company"), "Our number");
  assert.equal(label("allowed"), "Can contact");
  assert.equal(label("human_conversation"), "Spoke with customer");
  assert.equal(classificationLabel("unknown"), "Unclassified");
  assert.equal(eligibilityLabel("unknown"), "Contact status unknown");
  assert.equal(contactTypeLabel("unknown"), "Connected—contact unknown");
  assert.equal(label("text"), "Text the customer");
});

test("supplied ages format wall and staffed durations without inventing clocks", () => {
  assert.equal(formatAge(45_000), "under 1m");
  assert.equal(formatAge(12 * 60_000), "12m");
  assert.equal(formatAge(3 * 60 * 60_000), "3h");
  assert.equal(formatSuppliedAge(3 * 60 * 60_000, 30 * 60_000), "3h ago (30m staffed)");
  assert.equal(copy.page.views.attention, "Outreach Intelligence");
  assert.equal(copy.page.searchPlaceholder.includes("opens Numbers"), true);
  assert.equal(copy.page.views.coverage, "Coverage");
  assert.equal(copy.page.views.reps, "RingCentral Accounts");
  assert.equal(copy.page.views.guide, "Guide");
  assert.equal(SI_VIEW_TABS.some((tab) => tab.key === "guide"), true);
  assert.equal(SI_PANEL_TABS.find((tab) => tab.key === "summary")?.label, "Running Summary");
  assert.equal(SI_PANEL_TABS.find((tab) => tab.key === "analysis")?.label, "Number Analysis");
  assert.equal(copy.panel.originalModelSummary, "Original model summary");
  assert.match(copy.panel.originalIsCurrent, /Running Summary tab/);
  assert.equal(copy.panel.runningSummary.includes("Job"), false);
  assert.equal(parseSiView("guide"), "guide");
  assert.equal(parseSiPanel("summary"), "summary");
  assert.equal(ownershipPhrase("assigned", null), "Unassigned");
  assert.equal(ownershipPhrase("owned", null), "Unassigned");
  assert.equal(ownershipPhrase("assigned", { id: "a".repeat(24), name: "Alex" }), "Assigned to Alex");
  assert.equal(ownerlessLabel(), "No one owns this");
  assert.equal(ownershipPhrase("assigned", null).includes("Assigned to Unassigned"), false);
  assert.equal(copy.reps.title, "RingCentral Accounts");
  assert.equal(copy.coverage.budgetExhausted, "Analysis paused—budget reached. Call history, follow-ups, and Owner actions still work.");
  assert.equal(copy.fields.leadMatch, "Lead match");
  assert.equal(copy.filters.numbersTitle, "Filter numbers");
  assert.equal(copy.classificationSoWhat.customer.includes("customer number"), true);
  assert.equal(copy.eligibilitySoWhat.suppressed.includes("Do not call"), true);
  assert.equal(copy.panel.pickOutreach.includes("Outreach"), true);
  assert.equal(copy.lead.noLead, "No lead on file");
  assert.equal(leadMatchSummary(0, 0), "No lead on file");
  assert.equal(leadMatchSummary(0, 1), "1 candidate");
  assert.equal(leadMatchSummary(2, 1), "2 attached · 1 candidate");
});
