export const REPORTING_COPY = {
  eyebrow: "Reporting",
  listTitle: "Reports",
  listHint:
    "Save a report, then create a Google Sheet from it. Preview and save do not write to Google.",
  createTitle: "Create New Report",
  createHint:
    "Choose the data, dates, sources, and a Google folder or tab. Save the report before you create the sheet.",
  editTitle: "Edit Report",
  editHint: "Saving creates a new version of this report. The Google Sheet is written only after you create the sheet.",
  detailHint: "This saved report is ready. Create the sheet to write a Google spreadsheet.",
  tabReports: "Reports",
  tabCreate: "Create New Report",
  tabSheets: "Sheets",
  allReports: "All reports",
  newReport: "Create New Report",
  editReport: "Edit report",
  saveReport: "Save Report Before Sheet Creation",
  savingReport: "Saving report…",
  previewSample: "Preview sample rows",
  previewing: "Previewing…",
  createSheet: "Create or Edit Sheet",
  reviewSheet: "Review sheet estimate",
  confirmSheet: "Confirm and create sheet",
  archiveReport: "Archive report",
  reportsTable: "Saved reports",
  reportsTableHint: "Open a report to create or update its Google Sheet.",
  emptyReports: "No reports yet. Create a new report to start.",
  recentSheets: "Recent sheet runs",
  recentSheetsHint: "Each run writes or updates a Google Sheet.",
  emptyRuns: "No sheet runs yet.",
  noRunsForReport: "This report has not created a sheet yet.",
  builderTitle: "Report setup",
  builderHint: "Pick what goes in the sheet. Column IDs and types stay fixed.",
  exampleSheetsTitle: "Example sheets",
  exampleSheetsHint:
    "Mock rows only. Open a panel to see the default columns that report type writes. This is not your data and does not write Google.",
  howTitle: "How a Google Sheet is created",
  howHint: "A Drive folder is not a spreadsheet. The sheet appears only after you create it.",
  stepDestination: "1. Sheet destination",
  stepDestinationBody: "Pick a Drive folder (new spreadsheet each run) or a managed tab to replace.",
  stepPreview: "2. Preview",
  stepPreviewBody: "Sample rows only. Does not write Google.",
  stepSave: "3. Save report",
  stepSaveBody: "Locks this report. Still no sheet.",
  stepSheet: "4. Create sheet",
  stepSheetBody: "This writes or updates the Google Sheet.",
  manageSheets: "Create or edit sheet destinations",
  connectGoogle: "Connect Google on the Sheets tab before you pick a destination.",
  destinationFolder:
    "This destination is a Drive folder. Vantage creates a new spreadsheet in that folder only after you create the sheet.",
  destinationTab:
    "This destination is a managed tab inside a workbook. Creating the sheet replaces that tab; it does not create a new file.",
  savedNotice: "Report saved. Create the sheet next, then confirm, to write Google.",
  savedNoticeSnapshot: " For a folder destination, the spreadsheet is created in that folder.",
  archivedNotice: "Report archived. Earlier versions stay available.",
  readOnly:
    "Read-only admin access. Only an owner can connect Google, manage sheet destinations, preview, save, archive, or create sheets.",
  currentVersion: "Saved report",
  versionHistory: "Saved versions",
  sheetHistory: "Sheet runs",
  createSheetCard: "Create or edit the Google Sheet",
  createSheetHint:
    "Saving the report did not write to Google. After you confirm, open the run for the workbook link.",
  latestSheet: "Latest sheet:",
  openWorkbook: "Open workbook",
  sheetsTitle: "Sheet destinations",
  sheetsHint:
    "A folder destination gets a new spreadsheet each time you create a sheet. A tab destination replaces one managed tab. This is not Reporting Sheets (the live operational projection).",
  googleTitle: "Owner Google connection",
  googleHint:
    "Reporting uses your Google account with limited Drive access. Connect here, then create a folder or tab destination.",
  runTitle: "Sheet run",
  backToReports: "All reports",
  nameLabel: "Report name",
  datasetLabel: "Report type",
  descriptionLabel: "Description",
  windowLabel: "Date window",
  timezoneLabel: "Timezone",
  sourcesLabel: "Sources",
  columnsLabel: "Columns",
  destinationLabel: "Sheet destination",
  createdLabel: "Saved",
  cancel: "Cancel",
  refresh: "Refresh",
} as const;

export const REPORTING_HREFS = {
  reports: "/reporting",
  create: "/reporting/new",
  sheets: "/reporting/destinations",
  report: (id: string) => `/reporting/${id}`,
  edit: (id: string) => `/reporting/${id}/edit`,
  destination: (id: string) => `/reporting/destinations/${id}`,
  run: (id: string) => `/reporting/runs/${id}`,
} as const;
