/** Owner-visible strings of the Leads workspace (doc 03). */
export const LEADS_COPY = {
  title: "Leads",
  subtitle: "Every lead from every source, newest first.",
  help: "Kind is where the lead came from: a web form or a phone call. Showing picks regular leads, duplicates of an earlier lead, or both. Search takes a job number, a phone number, an email or a name.",
  verify: "Verify in Master Sheet",
  verifyDone: "Done selecting",
  newLead: "New lead",
  newLeadTitle: "New lead",
  searchPlaceholder: "Job number, phone, name or email",
  sortLabel: "Sort",
  sortOptions: [
    { value: "received_desc", label: "Lead received, newest first" },
    { value: "received_asc", label: "Lead received, oldest first" },
    { value: "move_soonest", label: "Move date, soonest first" },
  ],
  kindLabel: "Kind",
  kindOptions: [
    { value: "all", label: "All" },
    { value: "form", label: "Form" },
    { value: "call", label: "Call" },
  ],
  statusLabel: "Status",
  statusOptions: [
    { value: "all", label: "All" },
    { value: "open", label: "Open" },
    { value: "booked", label: "Booked" },
    { value: "cancelled", label: "Cancelled" },
    { value: "bad", label: "Bad" },
  ],
  companyLabel: "Source company",
  sourceLabel: "Source",
  sourceAll: "Source: any",
  feedLabel: "Feed",
  feedAll: "Feed: all feeds",
  agentLabel: "Receiver agent",
  agentAll: "Receiver agent: any",
  agentUnassigned: "Unassigned",
  showLabel: "Showing",
  showOptions: [
    { value: "regular", label: "Showing: Regular" },
    { value: "duplicates", label: "Showing: Duplicates" },
    { value: "both", label: "Showing: Both" },
  ],
  showBothNote: "Showing both is not available until the server's unified leads list ships. This list shows regular leads.",
  moreFilters: "More filters",
  clearAll: "Clear all",
  dateOn: "Date range on",
  dateOptions: [
    { value: "timestamp", label: "Lead received" },
    { value: "move_date", label: "Move date" },
  ],
  dateFrom: "From",
  dateTo: "To",
  hiddenLabel: "Hidden from sheets",
  hiddenOptions: [
    { value: "any", label: "Hidden from sheets: any" },
    { value: "yes", label: "Hidden from sheets: yes" },
    { value: "no", label: "Hidden from sheets: no" },
  ],
  moveSizeLabel: "Move size (form leads)",
  moveSizeAny: "Move size: any",
  localLabel: "Local or long distance",
  localAny: "Local or long distance: any",
  feedServerNote: "Pick a feed to narrow on the server.",
  clientNarrowNote: "Bad and Unassigned narrow the loaded cards only; the counts above need the server's unified leads list.",
  summaryLeads: "Leads",
  summaryForm: "Form",
  summaryCall: "Call",
  summaryShowing: "Showing",
  summaryLoaded: (n: number) => `${n} loaded`,
  totalPending: "needs the server list",
  empty: "No leads match these filters",
  emptyHint: "Try a different search or clear the filters.",
  loadFailed: "Leads could not be read.",
  loadMore: "Loading more leads…",
  allLoaded: "All leads loaded",
  duplicatesNoticeTitle: "Duplicates are read-only",
  selectedCount: (n: number) => `${n} selected`,
  verifyUpTo: "Verify up to 25 at a time",
  selectAll: "Select all on this page",
  clearSelection: "Clear",
  verifying: "Verifying…",
  cardActions: {
    book: "Book",
    assign: "Assign",
    assignPlaceholder: "Assign…",
    more: "More actions",
    markBad: "Mark bad",
    hide: "Hide from sheets",
    unhide: "Show in sheets",
    timeline: "Job timeline",
    copyJob: "Copy job #",
    open: "Open lead",
  },
  card: {
    unassigned: "Unassigned",
    noEstimate: "no estimate yet",
    leadMessageSent: "Lead message sent",
    granotDiffers: "Granot contact differs",
    hidden: "Hidden from sheets",
    duplicate: "Duplicate",
    unnamed: "Unnamed lead",
    status: { open: "Open", booked: "Booked", cancelled: "Cancelled", bad: "Bad" },
  },
  density: "vantage-admin-leads-density",
} as const;
