/**
 * Owner-visible strings of Setup → Website (doc 19): the testimonials the main site can show, re-homed from the old
 * Testimonials page. Every string passes `lib/operations-registry/ownerLanguageDeck.ts`.
 */
export const WEBSITE_COPY = {
  listTitle: "Testimonials",
  listSubtitle: "Search BBB testimonials by reviewer, stars and review date. Looking here never changes what the main site shows. Open a row to read the full review.",
  searchPlaceholder: "Search reviewer name",
  searchMinimum: "Enter at least 2 characters to search.",
  reviewer: { label: "Reviewer", any: "Any reviewer", loading: "Loading reviewers" },
  stars: { label: "Stars", any: "Any stars" },
  rating: (n: number) => `${n} ${n === 1 ? "star" : "stars"}`,
  dates: { from: "Reviewed from", to: "Reviewed to" },
  sort: { label: "Sort by review date", newest: "Newest", oldest: "Oldest" },
  clear: "Clear filters",
  loading: "Loading testimonials",
  readFailure: "The testimonials did not load.",
  empty: "No testimonials match these filters.",
  columns: {
    reviewer: "Reviewer",
    date: "Review date",
    stars: "Stars",
    review: "Review",
    customer: "Customer",
    published: "Published",
    featured: "Featured",
  },
  yes: "Yes",
  no: "No",
  notLinked: "Not linked",
  linkedCustomer: "Linked customer",
  page: (page: number, pages: number | null, total: number | undefined) =>
    `Page ${page}${pages ? ` of ${pages}` : ""}${total !== undefined ? ` · ${total} testimonials` : ""}`,
  previous: "Previous",
  next: "Next",
  drawer: {
    fallbackTitle: "Testimonial",
    review: "Review",
    noText: "No review text recorded.",
    response: "Business response",
    responded: (when: string) => `Responded ${when}`,
    details: "Details",
    reviewer: "Reviewer",
    source: "Source",
    reviewDate: "Review date",
    stars: "Rating",
    customer: "Customer",
    status: "Status",
    published: "Published",
    unpublished: "Unpublished",
    featured: "Featured",
    notFeatured: "Not featured",
    none: "None",
  },
} as const;
