export const BOOKINGS_CONNECT_COPY = {
  storedLead: "Stored lead",
  noStoredLead: "No stored lead",
  referral: "Referral",
  emptyState: "This booking has no stored lead",
  connectALead: "Connect a lead",
  connectLead: "Connect lead",
  searchTitle: "Connect a lead",
  searchHint: "Search the website contact or the later Granot contact, or the job number or reference. The booking stays on this page.",
  searchLabel: "Search the website contact, the later Granot contact, job number, or reference",
  searchPlaceholder: "Website contact, Granot contact, job, or reference",
  contactCycle: {
    line: "Form submitted is what they typed on the website. Granot is the later card from the CRM when we have one.",
    callLine: "Called is the phone contact. Granot is the later card from the CRM when we have one.",
    changed: "Granot later changed this contact.",
  },
  reviewTitle: "Review this connection",
  overrideLabel: "Why this customer is the right one even though they came from a different lead source",
  overrideHint: "Write 10–500 characters. Same-source customers do not need this.",
  success: "Master Leads and Master Booked will update.",
  attachedLead: "This booking now has a stored lead.",
} as const;

/** Owner-visible strings of the All bookings workspace (doc 03). */
export const BOOKINGS_COPY = {
  title: "All bookings",
  subtitle: "Every booking, newest first. Cancelled bookings show with their cancellation.",
  help: "Status picks active bookings, cancelled bookings or both. Source is the feed the booking came from. Search takes a job number or a customer name.",
  newBooking: "New booking",
  searchPlaceholder: "Job number or customer name",
  sortOptions: [
    { value: "book_desc", label: "Book date, newest first" },
    { value: "book_asc", label: "Book date, oldest first" },
    { value: "binder_desc", label: "Binder, highest first" },
  ],
  statusLabel: "Status",
  statusOptions: [
    { value: "active", label: "Active" },
    { value: "cancelled", label: "Cancelled" },
    { value: "all", label: "All" },
  ],
  sourceLabel: "Source",
  sourceAll: "Source: any",
  agentLabel: "Agent",
  agentAll: "Agent: any",
  merchantLabel: "Merchant",
  merchantAll: "Merchant: any",
  dateFrom: "Booked from",
  dateTo: "Booked to",
  typeLabel: "Booking type",
  typeOptions: [
    { value: "any", label: "Booking type: any" },
    { value: "lead", label: "With lead" },
    { value: "leadless", label: "Leadless" },
    { value: "referral", label: "Referral" },
  ],
  localLabel: "Local or long distance",
  localAny: "Local or long distance: any",
  binderLabel: "Binder",
  binderOptions: [
    { value: "any", label: "Binder: any" },
    { value: "2k", label: "Binder: over $2k" },
    { value: "4k", label: "Binder: over $4k" },
  ],
  clearAll: "Clear all",
  typeNarrowNote: "Booking type narrows the loaded cards only. The count above is the server's count for the other filters.",
  summaryBookings: "Bookings",
  summaryBinder: "Binder total",
  summaryDeposits: "Deposits total",
  summaryCancelled: "Cancelled",
  totalsPending: "needs server totals",
  ofLoaded: "of loaded",
  empty: "No bookings match these filters",
  emptyHint: "Try a different search or clear the filters.",
  loadFailed: "Bookings could not be read.",
  loadMore: "Loading more bookings…",
  allLoaded: "All bookings loaded",
  actionFailed: "Booking update failed.",
  deleteFailed: "Delete failed.",
  density: "vantage-admin-bookings-density",
  card: {
    unnamed: "Unnamed booking",
    active: "Active",
    cancelled: "Cancelled",
    over2k: "Over $2k",
    over4k: "Over $4k",
    job: "Job",
    booked: "Booked",
    routeMissing: "Route not captured yet",
    binder: "Binder",
    deposit: "Deposit",
    merchant: "Merchant",
    refund: "Refund",
    split: "split",
    leadAttached: "Lead attached",
    form: "Form",
    call: "Call",
    leadless: "Leadless",
    referral: "Referral",
    masterBooked: "Master Booked",
    employeeForm: "Employee booking form",
    viewCancellation: "View cancellation",
    selectLabel: (name: string) => `Select ${name}`,
  },
  match: {
    jobNumber: "Matched by job number",
    granotLid: "Matched by Granot LID",
    contact: "Matched by contact details",
    phone: "Matched by phone",
  },
  actions: {
    recordCancellation: "Record cancellation",
    more: "More actions",
    openLead: "Open lead",
    timeline: "Job timeline",
    copyJob: "Copy job #",
    edit: "Edit",
  },
  cancellationTab: {
    title: "Cancellation",
    cancelDate: "Cancel date",
    reason: "Reason",
    refund: "Refund",
    notes: "Notes",
    cancelledBy: "Recorded by",
    merchant: "Merchant",
    open: "Open the cancellation",
    missing: "This booking is cancelled, but the cancellation did not come with it. Open the cancellations list to see it.",
  },
} as const;
