export const EXTENSION_COPY = {
  pageTitle: "Extension",
  pageHint:
    "Create logins for the Granot browser extension. These people are Extension Users, not Agents.",
  rolesTitle: "What each role can do",
  ownerRole:
    "Owner: can sync leads (Enrichment) and use search in the extension. Also has Binding Estimate Fee and Tariff Adjustment.",
  salesRole: "Sales: can use Binding Estimate Fee only.",
  customerServiceRole: "Customer Service: can use Tariff Adjustment only.",
  emailLabel: "Email",
  emailHint: "This is the login used in the browser extension.",
  passwordLabel: "Password",
  passwordHint: "At least 8 characters.",
  roleLabel: "Role",
  ownerOption: "Owner",
  salesOption: "Sales",
  customerServiceOption: "Customer Service",
  createButton: "Create Extension User",
  creatingButton: "Creating…",
  created: "Extension User created.",
  listTitle: "Extension Users",
  emptyList: "No Extension Users yet.",
  roleOwner: "Owner",
  roleSales: "Sales",
  roleCustomerService: "Customer Service",
  roleEmployee: "Employee",
  active: "Active",
  inactive: "Inactive",
} as const;
