/**
 * Owner-visible strings of the Systems tab (doc 11b). Words: Systems, Master Leads, Master Booked, Sheet Sync, Setup ›
 * Connections & health. No em-dashes; "·" separates. Every string passes `lib/operations-registry/ownerLanguageDeck.ts`.
 */
export const SYSTEMS_COPY = {
  title: "Your systems",
  subtitle: "Where everything lives, and how much room is left.",
  help: "Every site, sheet and service in one list, with links to open, install or copy. Below it, how full the database and the two Master Sheets are, and how long until each one is full at today's pace.",
  checked: (time: string) => `checked ${time}`,
  refresh: "Refresh",
  refreshing: "Refreshing…",
  refreshThrottled: "Checked less than a minute ago, so these are the same readings.",
  partnerHealth: "Partner health (Granot, RingCentral, Google Sheets) lives in Setup › Connections & health.",
  partnerHealthLink: "Open Connections & health",
  locations: {
    title: "Where things live",
    open: "Open",
    install: "Install",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Copy did not work. Select the link and copy it by hand.",
    code: "Code",
    host: "Vercel",
    store: "Store listing",
    logs: "Logs",
    openPath: (path: string) => `Open ${path}`,
    openLabel: (label: string) => `Open ${label}`,
    installLabel: (label: string) => `Install ${label} from the Chrome Web Store`,
    copyLabel: (label: string) => `Copy the ${label} link`,
    noLink: "No link yet.",
    readFailure: "The locations did not load.",
    edit: "Edit locations",
    editTitle: "Edit locations",
    editHint: "Change a label, link or note. Links must start with https://. Changes take effect right away and show in Setup › Change history.",
    fields: {
      label: "Label",
      url: "Main link",
      note: "Note",
      paths: "Paths (one per line, each starting with /)",
      code_url: "Code link",
      code_note: "Code note",
      host_url: "Host link",
      logs_url: "Logs link",
    },
    save: "Save locations",
    saving: "Saving…",
    cancel: "Cancel",
    saved: "Saved. The new links are live.",
    nothingChanged: "Nothing changed.",
    sheetsNote: "The two Master Sheet links come from the server's sheet settings and are not edited here.",
    lastEdited: (who: string, when: string) => `Last edited by ${who} · ${when}`,
  },
  capacity: {
    title: "Capacity",
    readFailure: "Capacity did not load.",
    status: { green: "Healthy", amber: "Needs a look", red: "Needs attention", unknown: "Not measured" },
    database: {
      title: "Database (MongoDB Atlas)",
      disk: "Disk",
      used: (used: string, total: string) => `${used} of ${total} used`,
      breakdown: (business: string, log: string, reclaimable: string, system: string) =>
        `Business data ${business} · Replication log ${log} (≈ ${reclaimable} reclaimable) · System ≈ ${system}`,
      until90: "Time until 90% full",
      untilFull: "Time until full",
      growing: (perDay: string) => `growing ≈ ${perDay}/day`,
      fromData: "using the data's growth while freed space is reused",
    },
    sheet: {
      biggestTab: "Biggest tab",
      tabRows: (name: string, rows: string, limit: string) => `${name} ${rows} of ${limit} rows`,
      workbook: "Workbook",
      cells: (used: string, cap: string) => `${used} of ${cap} cells`,
      rowsPerMonth: (n: string) => `+${n} rows / month`,
      cellsPerMonth: (n: string) => `+${n} cells / month`,
      untilNewWorkbook: "Time until a new workbook is needed",
      byRows: (name: string) => `${name} hits 40,000 rows`,
      byCells: "the workbook hits 5,000,000 cells",
      untilCellCap: "Time until Google's cell cap",
      lastCancellation: (date: string) => `Last cancellation row: ${date}`,
      noCancellation: "No cancellation row yet.",
    },
    sync: {
      label: "Sync",
      lastWrite: (when: string) => `last write ${when}`,
      noWrite: "no write yet",
      pending: (n: number) => `${n} pending`,
      failed: (n: number) => `${n} failed`,
      stuck: (n: number, since: string) => `${n} stuck since ${since}`,
      unavailable: "Sync state is not available right now.",
    },
    estimate: (points: number) => `estimate · ${points} of 7 days measured`,
    measured: (points: number) => `measured over ${points} days`,
    notMeasured: "Not measured",
  },
} as const;
