/**
 * Every owner/rep-visible string of the Sales Outreach Desk ("Lead outreach"). Display only: query keys, server codes
 * and DTO field names never appear on screen (snake_case identifiers are mapped here to words). Policy facts such as
 * required counts and schedule days always come from the server; nothing here states a cadence rule.
 */
import type { DeskView } from "./data/desk-url";

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const deskCopy = {
  brand: "Lead outreach",
  nav: {
    label: "Lead outreach",
    views: {
      team: "Team overview",
      my: "My work",
      activity: "Activity",
      settings: "Settings",
      numbers: "All Numbers",
      accounts: "Accounts",
    } satisfies Record<DeskView, string>,
    dailyOperations: "Daily Operations",
    adminDashboard: "Admin dashboard",
    more: "Elsewhere",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
  },
  titles: {
    team: "Team outreach",
    my: "My outreach",
    myInspecting: (name: string) => `${name} · outreach`,
    activity: "Activity",
    settings: "Settings",
    numbers: "All Numbers",
    accounts: "RingCentral Accounts",
  },
  roles: {
    owner: "Owner",
    manager: "Manager",
    rep: "Sales Representative",
  },
  identity: {
    menu: "Account menu",
    signOut: "Sign out",
    signingOut: "Signing out…",
  },
  notAllowed: {
    title: "This page isn't part of your desk",
    body: "Your account can't open this view.",
  },
  text: {
    pending: "Pending",
    unknown: "Unknown",
    unavailable: "Unavailable",
    never: "Never",
    today: "Today",
    yesterday: "Yesterday",
    justNow: "just now",
    minAgo: (n: number) => `${n} min ago`,
    hoursAgo: (n: number) => `${n} h ago`,
    daysAgo: (n: number) => `${plural(n, "day", "days")} ago`,
    minutes: (n: number) => plural(n, "minute", "minutes"),
    hours: (n: number) => plural(n, "hour", "hours"),
    days: (n: number) => plural(n, "day", "days"),
    day: (n: number) => `Day ${n}`,
    synced: "Synced",
    delayed: "Delayed",
    notConnected: "Not connected",
    goalReached: "Goal reached",
    overdue: "Overdue",
    overdueBy: (duration: string) => `${duration} overdue`,
    dueToday: "Due today",
    smsDueToday: "SMS due today",
    dueTomorrow: "Due tomorrow",
    dueOn: (date: string) => `Due ${date}`,
    scheduled: "Scheduled",
    done: "Done",
    sent: "Sent",
    blocked: "Blocked",
    notRequired: "Not required",
    callOverdue: "Call overdue",
    callOverdueBy: (duration: string) => `Call overdue by ${duration}`,
    smsOverdue: "SMS overdue",
    callAndSmsOverdue: "Call and SMS overdue",
    overdueWork: "Contact overdue",
    callDueToday: "Call due today",
    callAndSmsDue: "Call and SMS due today",
    contactBlocked: "Contact blocked",
    needsReview: "Needs review",
    // A channel whose status is `pending`: the evidence is uncertain (records still arriving), not a review.
    pendingTitle: "Waiting on RingCentral call or SMS records before this can be checked.",
    recordsPending: "Pending — checking call and SMS records",
    // A passed deadline RingCentral capture can't prove yet (`verification.state: unverified`): never "overdue".
    notYetVerified: "Due — not yet verified",
    notYetVerifiedFull: (knownThrough: string | null) =>
      knownThrough ? `Due — not yet verified (activity known through ${knownThrough})` : "Due — not yet verified (waiting for RingCentral capture)",
    notYetVerifiedTitle: (knownThrough: string | null) =>
      `This deadline has passed, but RingCentral capture ${knownThrough ? `only covers activity through ${knownThrough}` : "hasn't reported this period yet"}. It isn't counted as overdue until capture catches up.`,
    knownThrough: (time: string) => `known through ${time}`,
    awaitingCapture: "waiting for capture",
    callNotYetVerified: "Call due — not yet verified",
    smsNotYetVerified: "SMS due — not yet verified",
    callAndSmsNotYetVerified: "Call and SMS due — not yet verified",
    jobPending: "Job number pending",
    moveDatePassed: "Move date passed",
    noIssue: "On track",
    unassigned: "Unassigned",
    unknownRep: "Unknown rep",
  },
  unknownReasons: {
    cadence_disabled: "Cadence isn't running yet",
    cadence_shadow: "Cadence is in shadow mode",
    policy_unavailable: "Policy unavailable",
    coverage_incomplete: "Waiting for RingCentral capture coverage",
  } as Record<string, string>,
  goalStates: {
    goal: "",
    no_goal_today: "No goal today",
    not_on_roster: "Not on roster",
  } as Record<string, string>,
  workflows: {
    new: "New",
    quoted: "Quoted",
    discretion: (code: string | null) => (code ? `Priority ${code}` : "Rep discretion"),
    code: (code: string) => `Priority ${code}`,
    none: "No policy",
  },
  freshness: {
    label: "Data freshness",
    sources: { granot: "Moving software", calls: "RingCentral calls", sms: "RingCentral SMS" },
    updated: (source: string, age: string) => `${source} updated ${age}`,
    observed: (age: string) => `Moving software observed ${age}`,
    completeThrough: (source: string, at: string) => `${source} is complete through ${at}`,
    delayed: (source: string) => `${source} is delayed`,
    notConnected: (source: string) => `${source} is not connected`,
    unknown: (source: string) => `${source} status is unknown`,
    /** The chip tooltip with the server's reason in words: "RingCentral calls is delayed — no live call events …". */
    withReason: (base: string, reason: string) => `${base} — ${reason}`,
    /**
     * Server `freshness.calls/sms.reason` codes in words (lifecycle repair A3-fresh). A RingCentral error code or any
     * other code not listed here reads as `reasonFallback`; the code itself never reaches the screen.
     */
    reasons: {
      confirmation_stale: "RingCentral's call log hasn't confirmed recent calls in the last few minutes",
      coverage_behind: "call capture is running behind the clock",
      webhook_silent: "no live call events have arrived from RingCentral for a while",
      capture_behind: "capture is running behind the clock",
      no_capture_state: "capture hasn't run yet",
      rep_sms_capture_disabled: "rep SMS capture is switched off",
      no_mailbox_synced: "no rep SMS mailbox has synced yet",
      mailbox_without_coverage: "a rep SMS mailbox hasn't synced yet",
    } as Record<string, string>,
    reasonFallback: "RingCentral reported a sync problem",
  },
  live: {
    updated: "Desk updated",
    unavailable: "Live updates paused",
  },
  errors: {
    conflict: "This lead changed while you were editing. The latest version is loaded — check it and try again.",
    forbidden: "Your account can't make this change.",
    failed: (message: string | null) => (message ? `That didn't work: ${message}` : "That didn't work. Try again."),
  },
  unavailable: {
    title: "The Outreach Desk isn't available yet",
    desk_disabled: "The desk is switched off in Settings.",
    configuration_uninitialized: "The desk hasn't been set up yet.",
    configuration_unavailable: "The desk's configuration can't be read right now.",
    notLinked: "Your account isn't linked to a reviewed RingCentral sales extension yet. Ask the Owner to link it.",
    forbidden: "Your account can't open the Outreach Desk.",
    error: "The desk couldn't load. It will retry automatically.",
    ownerSettings: "Open Settings",
    retry: "Retry",
    notPermitted: "This page isn't part of your desk.",
    backToDesk: "Go to my desk",
  },
  /** A desk read that failed inside a view (team, goal, queue): said in place of a skeleton that would never resolve. */
  readErrors: {
    team: "Team goals and lead counts couldn't load.",
    goal: "This goal couldn't load.",
    queue: "The lead list couldn't load.",
    reps: "The rep list couldn't load.",
    unavailable: "This part of the desk is unavailable right now. It will retry automatically.",
    shape: "The server sent something this version of the desk doesn't understand yet. Reload the page; if it keeps happening, the desk needs an update.",
    forbidden: "Your account can't open this part of the desk.",
    failed: "Check your connection, then retry.",
    stale: (at: string) => `Couldn't refresh — showing data as of ${at}.`,
    retry: "Retry",
  },
  team: {
    toolbar: "Team filters",
    today: "Today",
    pickDay: "Business day",
    allReps: "All reps",
    unassigned: "Unassigned",
    allLeads: "All leads",
    new: "New",
    quoted: "Quoted",
    leadFilter: "Lead type",
    search: "Search job # or phone",
    cards: {
      outbound: "Outbound calls",
      repsAtGoal: "Reps at goal",
      overdue: "Overdue leads",
      quotedGaps: "Quoted leads with gaps",
      ofGoal: (pct: string) => `${pct} of goal`,
      ofReps: (pct: string) => `${pct} of reps`,
      partial: (n: number) => `${plural(n, "rep", "reps")} still pending`,
      otherOutbound: (n: string) => `Other outbound: ${n}`,
      unassigned: (n: string) => `${n} unassigned`,
      unassignedOverdue: (n: string, overdue: number) => `${n} unassigned · ${overdue} overdue`,
      distinctLeads: "Distinct leads with an overdue call or SMS",
      quotedLeads: "Quoted leads with an overdue call",
      noGoals: "No rep has a goal today",
    },
    goals: {
      title: "Daily call goals",
      subtitle: (scope: string) => `Outbound calls per rep · ${scope}`,
      scopeAll: "All outbound calls",
      scopeEligible: "New + quoted leads",
      scopeMixed: "scope differs by rep today",
      columns: { rep: "Sales rep", calls: "Calls today", progress: "Daily progress", remaining: "Calls remaining", overdue: "Overdue leads", action: "Action" },
      viewQueue: "View queue",
      overdueCount: (n: number) => `${n} overdue`,
      noneOverdue: "0 overdue",
      awaiting: (n: number) => `+${n} unconfirmed`,
      awaitingTitle: "Seen live but not yet in the RingCentral Call Log; not counted until confirmed.",
      callsOnly: (n: number) => `${plural(n, "call", "calls")}`,
      /**
       * A rep-day's call capture coverage (`coverage.state`): `complete` says nothing; `partial` = capture is behind the
       * clock, so a count can still grow; `unknown` = capture hasn't reported this day at all.
       */
      coverageStates: {
        partial: "Call capture catching up",
        partialTitle: (through: string | null) =>
          through
            ? `RingCentral call capture is complete through ${through}. Calls after that may still arrive, so these counts can still grow.`
            : "RingCentral call capture is behind, so these counts can still grow.",
        unknown: "Call capture not reported yet",
        unknownTitle: "RingCentral hasn't reported call capture for this day yet, so calls may be missing from these counts.",
      },
      /**
       * Both counts (lifecycle repair C1b): the headline under the configured scope, then the other scope as a secondary
       * figure — "97 outbound · 12 to enrolled Leads". A scope this desk has no words for reads neutrally.
       */
      scopeCount: {
        all_outbound: (n: string) => `${n} outbound`,
        eligible_new_quoted: (n: string) => `${n} to enrolled Leads`,
      } as Record<string, (n: string) => string>,
      scopeCountFallback: (n: string) => `${n} in the other count`,
      scopeCountsTitle: {
        all_outbound:
          "The goal counts every outbound call. “To enrolled Leads” are the calls that reached a lead on the desk while it was New or Quoted.",
        eligible_new_quoted:
          "The goal counts calls that reached a lead on the desk while it was New or Quoted. “Outbound” is every outbound call.",
      } as Record<string, string>,
      scopeCountsTitleFallback: "The second figure counts the same calls a different way; only the first counts toward the goal.",
      /**
       * “Other outbound” by reason (lifecycle repair C8, the contact events' association reasons). Lower case: they read
       * after a count ("51 lead not on the desk"). `eligible` never appears in a breakdown; listed so every reason has words.
       */
      otherReasons: {
        eligible: "reached an enrolled New or Quoted lead",
        no_lead: "no lead for the number",
        lead_not_enrolled: "lead not on the desk",
        lead_closed: "lead already closed",
        before_activation: "before the desk started on the lead",
        ambiguous: "more than one possible lead",
        not_new_quoted: "lead not New or Quoted",
        unknown: "recorded before reasons were kept",
      } as Record<string, string>,
      otherReasonFallback: "another reason",
      otherBreakdownTitle: "Other outbound by reason",
      otherBreakdownPending: "The reasons for these calls aren't recorded for this day yet.",
      otherBreakdownPart: (n: number, words: string) => `${n} ${words}`,
      otherBreakdownFoot: (parts: string) => `Other outbound by reason: ${parts}.`,
      noActivityTitle: "No calls recorded yet — RingCentral call capture is complete for this time, so this is a real 0.",
      footnote: "Call totals can exceed the goal. Progress bars cap at 100%.",
      otherFootnote: "“Other outbound” are calls that didn't reach an enrolled New or Quoted lead.",
      /** The footnote under the configured scope: whether Other outbound is part of the goal count. */
      otherFootnoteByScope: {
        all_outbound: "“Other outbound” are calls that didn't reach an enrolled New or Quoted lead; they still count toward the all-outbound goal.",
        eligible_new_quoted: "“Other outbound” are calls that didn't reach an enrolled New or Quoted lead; they don't count toward the goal.",
      } as Record<string, string>,
      empty: "No rep is on today's roster yet.",
      unavailable: "Goal tracking is switched off in Settings.",
      setGoal: "Attendance",
    },
    attention: {
      title: "Leads needing attention",
      columns: { job: "Job / phone", owner: "Owner", priority: "Priority", issue: "Issue", last: "Last outreach", action: "Action" },
      sort: "Sort",
      empty: "Nothing needs attention right now.",
      unavailable: "Lead cadence isn't running yet, so there's no attention list.",
      footnote: "Calls and SMS update automatically from RingCentral.",
      unassignedDrill: (n: string) => `${n} unassigned · view`,
      more: "Open full queue",
    },
    operations: {
      title: "Operations today",
      open: "Open Daily Operations",
      leads: "Leads",
      bookings: "Bookings",
      cancellations: "Cancellations",
      texts: "Texts sent",
      textsScope: "automated confirmations",
      unreconstructable: (n: number) => `${plural(n, "sent text", "sent texts")} without a recorded send time`,
      unavailable: "Daily Operations isn't available right now.",
    },
  },
  my: {
    goalTitle: "Today's outbound calls",
    goalTitleFor: (day: string) => `Outbound calls · ${day}`,
    toGoal: (n: number) => `${plural(n, "call", "calls")} to reach your goal`,
    goalMet: "Goal reached — keep going",
    waitingCapture: "Waiting for RingCentral call capture",
    noGoal: "No goal today",
    overdue: "overdue",
    overdueUnit: "leads",
    callsDue: "calls due",
    smsDue: "SMS due",
    metricUnavailable: "unavailable",
    awaiting: (n: number) => `${n} awaiting confirmation`,
    tabs: { all: "All leads", new: "New leads", quoted: "Quoted leads" },
    tabsLabel: "Lead type",
    work: { needs_contact: "Needs contact", all_active: "All active" },
    workLabel: "Work filter",
    search: "Search job # or phone",
    flow: "Copy job # → Open moving software → Contact lead",
    queueTitle: "Contact next",
    sorts: { urgency: "Overdue first", lead_received: "Lead received", last_interaction: "Last interaction" },
    sortLabel: "Sort queue",
    newest: "Newest first",
    oldest: "Oldest first",
    columns: { job: "Job / phone", age: "Lead age", last: "Last outreach", calls: "Calls today", sms: "SMS", copy: "Copy" },
    loadMore: "Load more",
    empty: "No leads match these filters.",
    emptyNeeds: "Nothing needs contact right now.",
    pendingCount: (n: number) => `${plural(n, "lead is", "leads are")} still being evaluated and not shown yet`,
    excludedUnknown: (n: number) => `${plural(n, "lead", "leads")} hidden because the move date is unknown`,
    queueUnavailable: "The queue isn't available until lead cadence is running.",
    cursorReset: "The list changed; showing the first page again.",
    selectHint: "Select a lead to see its details.",
    selectedNotInList: "The selected lead no longer matches these filters.",
    inspecting: (name: string) => `Viewing ${name}'s queue`,
    backToTeam: "Back to team",
    moveDate: "Move date",
    moveDates: { upcoming: "Upcoming", today: "Today", next7: "Next 7 days", past: "Past", unknown: "Unknown", any: "Any date", anyShort: "Any move date" },
  },
  lead: {
    region: "Selected lead",
    jobPending: "Job number pending",
    copy: "Copy job #",
    copied: "Copied",
    copyFailed: "Copy failed",
    copyDisabled: "No job number yet",
    newLead: "New lead",
    quotedLead: "Quoted lead",
    dayN: (n: number) => `Day ${n}`,
    /**
     * How the lead joined the desk (ADM-4), from `subject.enrollment`. The cohort id is never shown: `admission:<date>`
     * is the Owner's automatic-admission switch (olr B6), `owner-enroll-`/`owner-older-` the Settings one-click Enroll,
     * kind `intake` the new-lead gate.
     */
    enrollment: {
      admission: (day: string) => `Added automatically on ${day}, when it became eligible (automatic admission is on)`,
      owner: (day: string) => `Enrolled by the Owner on ${day}`,
      intake: (day: string) => `Added when it came in (${day})`,
      pilot: (day: string) => `Enrolled in the pilot on ${day}`,
      other: (day: string) => `Enrolled on ${day}`,
    },
    todayNeeds: (calls: string, sms: string) => `Today: ${calls} + ${sms}`,
    callsUnit: (n: number | null) => (n === null ? "calls pending" : `${n} ${n === 1 ? "call" : "calls"}`),
    smsUnit: (n: number | null) => (n === null ? "SMS pending" : `${n} SMS`),
    nextCallDue: "Next call due now",
    callOverdue: "Call overdue",
    callDueBy: (time: string) => `Call due by ${time}`,
    smsOverdue: "SMS overdue",
    smsDue: "SMS due today",
    callNotYetVerified: "Call due — not yet verified",
    smsNotYetVerified: "SMS due — not yet verified",
    knownThrough: (time: string) => `Activity known through ${time}`,
    waitingCapture: "Waiting for RingCentral capture",
    allDone:"Today's contact is done",
    spacing: "Space attempts across the day",
    recentActivity: "Recent activity",
    noActivity: "No calls or texts recorded yet.",
    automaticTitle: "Automatic tracking",
    automaticBody: "Contact this job in the moving software and RingCentral. Outreach updates here automatically.",
    policyTitle: "This lead's schedule",
    schedule: {
      title: "New lead schedule",
      firstDays: (required: number, optional: number) =>
        `Days 1–3: ${plural(required, "call", "calls")} required${optional ? `, ${optional} optional` : ""}`,
      slot: (from: number, to: number | null, perDay: number) =>
        `${to === null ? `Day ${from} on` : from === to ? `Day ${from}` : `Days ${from}–${to}`}: ${plural(perDay, "call", "calls")} a day`,
      sms: (initial: number[], repeatFrom: number, every: number) =>
        `SMS: ${initial.length ? `${initial.length === 1 ? "Day" : "Days"} ${initial.join(", ")}, then ` : ""}every ${plural(every, "day", "days")} from Day ${repeatFrom}`,
    },
    footnote: "Calls and SMS update automatically from RingCentral.",
    assignedTo: "Assigned to",
    reassign: "Reassign",
    assignLabel: "Assigned rep",
    saveAssign: "Save",
    quotedDate: "Quoted follow-up date",
    setQuoted: "Set date",
    callback: "Callback",
    scheduleCallback: "Schedule a callback",
    setCallback: "Set callback",
    cancelCallback: "Cancel callback",
    callbackAt: (when: string) => `Callback ${when}`,
    revoked: "This lead is no longer in your queue.",
    loading: "Loading lead…",
    close: "Close",
    events: {
      outbound_attempt: "Outbound call",
      inbound_answered: "Inbound call answered",
      inbound_missed: "Missed inbound call",
      sms_sent: "SMS sent",
      sms_failed: "SMS failed",
      sms_inbound: "SMS received",
      other: "Contact",
    } as Record<string, string>,
    verification: {
      confirmed: "",
      awaiting_confirmation: "awaiting confirmation",
      pending_identity: "rep pending",
      pending_association: "lead match pending",
      excluded: "not counted",
    } as Record<string, string>,
    explanation: {
      cadence_shadow: "Cadence is in shadow mode: no overdue labels yet.",
      priority_intake_default: "No priority from the moving software yet; treated as a new lead by default.",
      priority_accepted_observation: "Priority comes from the moving software.",
      priority_uncertain: "The priority is uncertain and waiting for review.",
      review: "Needs review",
      quoted_date: "Quoted follow-up date",
      callback: "Callback",
      restriction_call: "Calls are blocked by a contact restriction",
      restriction_sms: "SMS is blocked by a contact restriction",
      move_date_passed: "The move date has passed",
      move_date_unknown: "The move date is unknown",
      job_number_pending: "The job number isn't in the moving software yet",
      advisory_cooldown: "Several attempts went unanswered; consider spacing them out.",
      inherited_overdue: "Overdue work carried over from before the reassignment",
      engine_state: "Schedule state",
      projection_pending: "Still being evaluated",
      cadence_disabled: "Cadence isn't running yet",
      policy_unavailable: "Policy unavailable",
      stale_policy: "Policy changed; recalculating",
    } as Record<string, string>,
    /** `projection_state` values (the panel's headline and schedule lines). */
    projectionStates: {
      pending: "Still being evaluated",
      stale_policy: "Policy changed; recalculating",
      cadence_disabled: "Cadence isn't running yet",
      policy_unavailable: "Policy unavailable",
    } as Record<string, string>,
    /** `engine_state` values other than `active` (the server's `SubjectEngineState`). */
    engineStates: {
      closed: "This lead's schedule has ended",
      review: "The schedule is on hold until the review is resolved",
      no_routine_cadence: "This priority has no routine schedule",
      no_policy_configured: "No schedule is set up for this priority yet",
    } as Record<string, string>,
    /** "Needs review: <reason>"; an unknown reason reads as plain "Needs review" (logged in development). */
    needsReview: (reason: string | null) => (reason ? `Needs review: ${reason}` : "Needs review"),
    moreReviewReasons: (n: number) => `${plural(n, "more reason", "more reasons")} listed below`,
    /**
     * Subject `review_reasons` and enrollment review reasons, in words (lower case: they follow "Needs review: ").
     * Codes from the server's `subjectStatusOf`, `resolveDeskPolicy`, `evaluateDeskEligibility` and enrollment
     * `classify`, plus `no_contact_number` (lane C2c switch).
     */
    reviewReasons: {
      no_contact_number: "no phone number to call",
      ambiguous_identity: "identity ambiguous — another lead has this Job Number",
      received_time_missing: "the time this lead came in is missing",
      received_time_unreliable: "the time this lead came in isn't reliable",
      priority_needs_review: "no priority from the moving software yet",
      malformed_priority: "the priority from the moving software isn't a recognized code",
      unmapped_priority: "this priority code has no schedule set up",
      unsupported_intake_source: "the lead's source has no default schedule",
      policy_unavailable: "the schedule policy isn't set up",
      duplicate: "marked as a duplicate lead",
      unmatched_booking_anchor: "created from a booking that matched no lead",
      legacy_closed_reopening_required: "closed in the old Outreach; reopening needs a decision",
      number_only_unassociated: "phone number not linked to a lead",
      lead_not_found: "the lead record wasn't found",
    } as Record<string, string>,
  },
  activity: {
    title: "Activity",
    subtitle: "Read-only contact history for active leads, most recent first.",
    listTitle: "Recently contacted",
    empty: "No activity yet.",
    detailTitle: "Contact history",
    assignmentChanges: "Assignment changes",
    planHistory: "Follow-up plans",
    windowHistory: "Daily requirements",
    missedHidden: "Missed counts appear once cadence enforcement is on.",
  },
  settings: {
    title: "Settings",
    ownerSubtitle: "Desk controls, goals and roster, the desk configuration, contact restrictions and enrollment. Owner only.",
    managerSubtitle: "Attendance for today and upcoming days.",
    repSubtitle: "Your desk settings.",
    controls: "Desk controls",
    controlNames: {
      desk_enabled: "Desk on",
      goal_metrics_enabled: "Goal tracking",
      rep_sms_capture_enabled: "Rep SMS capture",
      cadence_shadow_enabled: "Cadence (shadow)",
      cadence_enforcement_enabled: "Cadence enforcement",
      intake_admission_enabled: "Admit new leads automatically",
    } as Record<string, string>,
    on: "On",
    off: "Off",
    roster: "Roster and daily goals",
    restrictions: "Contact restrictions",
    restrictionsHint: "Restrictions from the old intelligence stay active and blocking until you confirm or lift each one.",
    confirm: "Confirm",
    lift: "Lift",
    liftReason: "Reason for lifting",
    enrollment: "Enrollment",
    attendance: "Attendance",
    attendanceHint: "Record an absence or a partial day before it happens. Past days are Owner-only.",
    absence: "Absent (goal 0)",
    partialDay: "Partial day",
    goal: "Goal",
    save: "Save",
    saved: "Saved",
    repNote: "Your goal, schedule and assigned leads are set by the Owner or your manager.",
  },
  settingsExtra: {
    blockers: (n: number) => `${plural(n, "activation blocker", "activation blockers")} reported by the server`,
    policy: (policy: string | null, version: string | null, at: string | null) =>
      [policy ? `Policy ${policy}` : "No policy installed", version ? `configuration ${version}` : null, at ? `updated ${at}` : null].filter(Boolean).join(" · "),
    defaultGoal: "Default daily goal",
    workingDays: "Working days",
    closures: "Closures",
    noClosures: "No closures scheduled.",
    addClosure: "Add a closure date",
    remove: "Remove",
    channels: "Blocks",
    channel: { call: "Calls", sms: "SMS" } as Record<string, string>,
    origin: "Origin",
    originOwner: "Owner",
    originIntelligence: "Old intelligence",
    needsReview: "Needs review",
    reason: "Reason",
    until: "Until",
    noEnd: "No end date",
    noRestrictions: "No active contact restrictions.",
    enrollmentHint: "Leads that aren't on the desk yet. Enroll adds one lead; leads that need review can't be enrolled until the reason is resolved.",
    /** The three lists (ADM-4): server partitions `in_scope`, `older`, `review`. */
    enrollmentTabsLabel: "Enrollment lists",
    enrollmentTabs: { in_scope: "Ready to enroll", older: "Older", review: "Needs review" } as Record<string, string>,
    readyHint: (days: number | null, upcomingMoves: boolean) =>
      `Eligible and not on the desk yet: received ${days ? `in the last ${days} days` : "inside the backfill window"}${upcomingMoves ? ", or moving from today on" : ""}.`,
    olderHint: (days: number | null) => (days ? `Not enrolled — older than ${days} days, with no upcoming move.` : "Not enrolled — older."),
    reviewHint: "Read only. The desk can't set a schedule for these leads until the reason is resolved in the moving software or the configuration.",
    received: "Received",
    why: "Why",
    /** `in_scope` reasons (enrollment `classify`): why a lead is ready. */
    readyReasons: { received_window: "Received recently", upcoming_move: "Upcoming move", selected: "Selected" } as Record<string, string>,
    noOlder: "No older eligible leads.",
    noReady: "No leads are waiting to be enrolled.",
    noReview: "No leads need review.",
    loadMore: "Load more",
    loadingMore: "Loading…",
    shownOf: (shown: number) => `${plural(shown, "lead", "leads")} shown`,
    listRestarted: "The list changed while you were paging, so it was reloaded from the top.",
    enroll: "Enroll",
    notEligible: "This lead isn't eligible any more.",
    migrationPaused: "Enrollment is paused in the configuration (migration paused).",
    /** Apply `status` in words; an unknown status reads as the generic line. */
    enrolledStatus: {
      completed: "Enrolled — the lead is on the desk now.",
      running: "Enrollment started — the lead appears on the desk in a moment.",
      paused: "Enrollment is paused in the configuration.",
      lease_held: "Another enrollment is running. Try again in a minute.",
      failed: "Enrollment failed. Try again.",
    } as Record<string, string>,
    enrolledOther: "Enrollment sent.",
    /** `GET /enrollment/admissions` (olr B8): the day's new-lead intake. */
    admissions: {
      title: "New-lead intake",
      hint: "What happened to each new lead that wasn't on the desk yet, for one New York business day. Every refusal shows its reason.",
      day: "Business day",
      today: "Today",
      counts: {
        admitted_intake: "Added to the desk",
        admitted_review: "Added for review",
        admitted_expansion: "Added later (automatic admission)",
        deferred: "Waiting to be decided",
        not_admitted: "Not added",
      } as Record<string, string>,
      byReason: "Not added, by reason",
      recent: "Recent refusals, newest first",
      noRefusals: "No new lead was refused this day.",
      lead: "Lead",
      reason: "Reason",
      when: "When",
      leadModel: { FormLead: "Form lead", CallLead: "Call lead" } as Record<string, string>,
      asOf: (at: string, days: number) => `As of ${at}. Kept ${days} days.`,
      retentionExceeded: (days: number) => `Only the last ${days} days are kept. Choose a later day.`,
      futureDay: "That day hasn't happened yet.",
      otherReason: "another reason",
      reviewReason: (reason: string) => `needs review first: ${reason}`,
      /**
       * Refusal reasons (lower case; they follow "Not added: "). The server stores free text: the intake gate's codes,
       * `closed:<reason>`, `excluded:<reason>` and `review:<reason>` (the review part reads from `lead.reviewReasons`).
       */
      reasons: {
        intake_disabled: "automatic admission of new leads was off",
        created_before_intake: "created before automatic admission started",
        received_before_intake: "received before automatic admission started",
        historical_import: "imported from history, not a new lead",
        policy_unavailable: "the schedule policy isn't set up",
        closed_priority: "its priority closes it",
        unsupported_intake_source: "the lead's source has no default schedule",
        "closed:official_booking": "already booked",
        "closed:official_cancellation": "already cancelled",
        "closed:bad_lead": "marked as a bad lead",
        "excluded:duplicate": "marked as a duplicate lead",
        "excluded:unmatched_booking_anchor": "created from a booking that matched no lead",
        unknown: "no reason was recorded",
      } as Record<string, string>,
    },
    attendanceOwner: "Record an absence or a partial day. Owners may also correct past days.",
    chooseRep: "Choose a rep",
    date: "Date",
    kind: "Type",
  },
  /**
   * The Owner configuration editor (lifecycle repair ADM-5). Keys the server added after revision 5 are optional: an
   * absent key runs on the server's code default, shown as "Default (n)". Server codes never show raw.
   */
  configEditor: {
    save: "Save",
    saved: "Saved.",
    useDefault: "Leave blank for the default.",
    defaultValue: (n: number, unit: string) => `Default (${n} ${unit})`,
    setValue: (n: number, unit: string) => `Set to ${n} ${unit}`,
    range: (min: number, max: number) => `${min}–${max}`,
    invalid: (label: string, min: number, max: number) => `${label}: enter a whole number from ${min} to ${max}, or leave it blank for the default.`,
    refusedSummary: "The server didn't accept this change:",
    conflict: "The configuration changed while you were editing. The latest version is loaded — check it and try again.",
    units: { minutes: "min", seconds: "s", jobs: "jobs", passes: "pages", loops: "at once", leads: "leads" } as Record<string, string>,
    goalCounts: {
      title: "Goal counts",
      hint: "Which calls count toward each rep's daily goal. A change starts on a later day; days that have started keep their count.",
      scopes: {
        all_outbound: "Every outbound call",
        eligible_new_quoted: "Calls to enrolled New or Quoted leads",
      } as Record<string, string>,
      scopeFallback: "A count this admin doesn't know yet",
      none: "No schedule: every outbound call counts (the default).",
      today: (label: string) => `Today the goal counts: ${label}.`,
      todayDefault: "Today the goal counts every outbound call (the default).",
      columns: { from: "From", counts: "Counts", status: "Status" },
      states: { inEffect: "In effect", ended: "Replaced", upcoming: "Upcoming" },
      locked: "Started days can't change",
      from: "Starting on",
      counts: "Count",
      add: "Add",
      remove: "Remove",
      removeEntry: (day: string) => `Remove the count starting ${day}`,
    },
    capture: {
      title: "Capture timing",
      hint: "How long RingCentral call capture may lag before goal counts and freshness say so.",
    },
    drain: {
      title: "Lead re-evaluation",
      hint: "The every-minute run that re-checks leads whose cadence changed. Raise these when due leads wait more than a few minutes at 8 PM or midnight.",
    },
    migration: {
      title: "Lead-change intake",
      hint: "How much of the Granot lead-change feed each run reads, and how many lead decisions it re-checks.",
    },
    tunables: {
      call_settlement_allowance_minutes: {
        label: "Call settlement allowance",
        hint: "How long RingCentral may take to settle a finished call before capture counts as behind.",
      },
      today_coverage_tolerance_minutes: {
        label: "Today's coverage tolerance",
        hint: "How far capture may trail the clock before today's goal counts read “catching up”. Must be more than the settlement allowance plus 15 minutes.",
      },
      capture_freshness_tolerance_minutes: {
        label: "Capture freshness",
        hint: "Age of the newest confirmed call at which call capture stops reading as fresh.",
      },
      webhook_silence_minutes: {
        label: "Webhook silence",
        hint: "How long RingCentral may stay silent before call freshness warns about it.",
      },
      evaluate_drain_max_jobs: { label: "Re-checks per run", hint: "Most lead re-checks one run handles." },
      evaluate_drain_budget_seconds: { label: "Time per run", hint: "Time one run may spend before it stops for the next minute." },
      evaluate_drain_concurrency: { label: "Re-checks at once", hint: "Re-checks one run handles in parallel." },
      feed_budget_seconds: { label: "Time per run", hint: "Time one run may spend reading lead changes." },
      feed_max_passes_per_run: { label: "Pages per run", hint: "Pages of 100 lead changes one run may read when changes pile up." },
      decision_reconcile_per_run: { label: "Decision re-checks per run", hint: "Lead decisions re-checked per 5-minute run." },
    } as Record<string, { label: string; hint: string }>,
    intake: {
      title: "New lead defaults",
      hint: "How a lead without a Granot priority yet starts on the desk. While cadence runs, a change the cadence engine can't run is refused.",
      notInstalled: "Intake defaults aren't installed in this configuration yet.",
      sources: {
        website_form: "Website form",
        best_relocation: "Best Relocation",
        ringcentral_call: "RingCentral call",
        manual: "Entered manually",
        granot_created: "Created in Granot",
      } as Record<string, string>,
      rules: { new: "New (cadence starts)", review: "Needs review (no cadence)" } as Record<string, string>,
      ruleFallback: "A setting this admin doesn't know",
    },
    priorityMap: {
      title: "Granot priority map",
      hint: "How each Granot priority code places a lead on the desk. Read-only here.",
      notInstalled: "No priority map is installed in this configuration yet.",
      columns: { code: "Priority code", workflow: "Desk workflow", closes: "Closes as" },
      workflows: { new: "New", quoted: "Quoted", discretion: "Rep's discretion", closed: "Closed", none: "No cadence" } as Record<string, string>,
      closures: {
        granot_booked: "Booked in Granot",
        crm_bad_disposition: "Bad lead in Granot",
        crm_dead_disposition: "Dead lead in Granot",
      } as Record<string, string>,
      fallback: "Not known to this admin",
      unmapped: (workflow: string) => `Any other code: ${workflow}.`,
      official: (workflow: string) => `An official booking or cancellation: ${workflow}.`,
    },
    rules: {
      title: "Lead rules",
      hint: "Optional rules from the lifecycle repair. Each is off unless switched on here.",
      names: {
        expansion_admission: "Admit leads that become eligible later",
        no_contact_number: "No phone number → Needs review",
        call_association: "Credit the one active lead on a shared number",
      } as Record<string, string>,
      hints: {
        expansion_admission:
          "When an older lead's Granot priority or duplicate status brings it into the backfill window, it joins the desk automatically.",
        no_contact_number: "A lead with no number to call goes to Needs review, with no cadence, until a number is linked.",
        call_association:
          "When a number's lead is closed or not on the desk and exactly one active desk lead shares the number, its calls credit that lead. Changes how All Numbers attributes calls; an Owner decision.",
      } as Record<string, string>,
      other: "Set to a value this admin doesn't know; change it on the server.",
      needsBackfill: "Install the backfill scope (lookback days and upcoming moves) first.",
    },
    fields: {
      count_scope_schedule: "Goal counts",
      cadence: "Cadence policy",
      backfill: "Backfill scope",
      intake: (source: string) => `${source} default`,
      fallback: "this setting",
    },
    issues: {
      count_scope_not_prospective: "Days that have already started keep their count. Start the new count from tomorrow or later.",
      engine_policy_unavailable:
        "The cadence engine can't run with this setting while cadence is on. Keep the native lead sources on New, or switch cadence off first.",
      coverageBelowSettlement: "Today's coverage tolerance must be more than the call settlement allowance plus 15 minutes.",
      backfillRequired: "Install the backfill scope (lookback days and upcoming moves) before turning on this rule.",
      outOfRange: (field: string) => `${field} is outside the range the server accepts.`,
      notAccepted: (field: string) => `${field} has a value the server doesn't accept.`,
      failedCheck: (field: string) => `${field} doesn't pass the server's checks.`,
      unknownKey: "The server doesn't know a setting in this configuration. Reload Settings and try again.",
      refused: (field: string, code: string) => `The server refused ${field} (code ${code}).`,
    },
  },
  numbers: {
    subtitle: "Every outside number that called us or that we called, and who it is.",
    toolbar: "Number filters",
    cards: {
      waiting: "Waiting on us",
      waitingCaption: "Called, nobody answered, nobody called back",
      noneWaiting: "Nobody is waiting",
      all: "All numbers",
      allCaption: "Callers, numbers we called and form leads",
    },
    segments: { all: "All", waiting: "Waiting on us" },
    segmentLabel: "Show",
    search: "Search number, name or job #",
    listTitle: { all: "All numbers", waiting: "Waiting on us" },
    listSubtitle: { all: "Most recent activity first", waiting: "Longest wait first" },
    columns: { number: "Number", lead: "Lead", last: "Last call", calls: "Calls", waiting: "Waiting" },
    unknown: "Unknown",
    formLead: "Form lead",
    noCalls: "No calls yet",
    callsInOut: (inbound: number, outbound: number) => `${inbound} in · ${outbound} out`,
    missed: (n: number) => `${n} missed`,
    job: (job: string) => `Job ${job}`,
    noJob: "No job # yet",
    pinned: "Linked by you",
    loadMore: "Load more",
    showing: (shown: number, total: number) => `Showing ${shown} of ${total}`,
    empty: "No numbers yet.",
    emptyWaiting: "Nobody is waiting on us right now.",
    emptySearch: "No numbers match this search.",
    error: "All Numbers couldn't load.",
    retry: "Retry",
    results: { answered: "Answered", missed: "Missed", voicemail: "Voicemail", noAnswer: "No answer" },
    directions: { inbound: "Incoming call", outbound: "Outgoing call" },
    leadStates: { open: "Open", booked: "Booked", cancelled: "Cancelled" },
  },
  numberPanel: {
    region: "Selected number",
    close: "Close",
    loading: "Loading number…",
    notFound: "This number isn't available any more.",
    error: "This number couldn't load.",
    waitingFor: (duration: string) => `Waiting on us for ${duration}`,
    waitingSub: (when: string) => `Missed call ${when}. Nobody has called back yet.`,
    handled: "Not waiting on us",
    facts: { firstSeen: "First seen", lastActivity: "Last activity", calls: "Calls", missed: "Missed" },
    leadTitle: "Lead",
    unknownTitle: "Unknown",
    unknownBody: "No lead has this phone number. Link one if you know who it is.",
    openInDesk: "Open in desk",
    rep: (name: string) => `Rep: ${name}`,
    noRep: "No rep",
    received: (when: string) => `Received ${when}`,
    linkedByYou: "Linked by you",
    matchedByPhone: "Matched by phone",
    creditNote: "This lead gets the Outreach Desk credit for calls with this number.",
    otherLeads: "Other leads with this number",
    useThis: "Use this lead",
    excludedTitle: "Unlinked leads",
    linkAgain: "Link again",
    link: "Link to a lead",
    linkOther: "Link a different lead",
    unlink: "Unlink",
    unlinkHint: "Unlinked leads are never matched to this number again.",
    picker: {
      label: "Search leads by name, job # or phone",
      hint: "Type at least 2 characters.",
      empty: "No leads match.",
      searching: "Searching…",
      choose: "Link",
      cancel: "Cancel",
      current: "Linked now",
    },
    conflict: "This number changed while you were looking. The latest version is loaded — check it and try again.",
    linked: (name: string) => `Linked to ${name}.`,
    unlinked: (name: string) => `${name} unlinked.`,
    callsTitle: "Calls",
    noCalls: "No calls with this number yet.",
    moreCalls: "Only the latest 100 calls are shown.",
    recordings: (n: number) => `${n} ${n === 1 ? "recording" : "recordings"}`,
    on: (number: string) => `on ${number}`,
    from: (number: string) => `from ${number}`,
    seconds: (n: number) => `${n} s`,
    minutes: (m: number, s: number) => (s ? `${m} min ${s} s` : `${m} min`),
    unnamedLead: "Unnamed lead",
  },
  accounts: {
    subtitle: "RingCentral users and the Agent each one is connected to. A change takes effect right away.",
    directoryAt: (when: string) => `Directory updated ${when}`,
    noDirectory: "No directory snapshot yet",
    suggest: "Suggest matches",
    suggesting: "Suggesting…",
    suggestedNone: "No new matches found.",
    suggested: (n: number) => `${n} ${n === 1 ? "match" : "matches"} to review.`,
    cards: {
      connected: "Connected",
      connectedCaption: (n: number) => `of ${n} users`,
      notConnected: "Not connected",
      notConnectedCaption: "No Agent, so their calls count for nobody",
      suggestions: "Suggested matches",
      suggestionsCaption: "One click to connect",
    },
    listTitle: "RingCentral users",
    columns: { user: "User", direct: "Direct number", agent: "Agent", role: "Role", actions: "Actions" },
    ext: (n: string) => `Ext. ${n}`,
    noExt: "No extension",
    noDirect: "None",
    notConnected: "Not connected",
    notInDirectory: "Not in directory",
    connect: "Connect",
    change: "Change",
    disconnect: "Disconnect",
    message: "Message",
    connectSuggested: (name: string) => `Connect ${name}`,
    roles: {
      sales_rep: "Sales rep",
      service: "Service",
      manager: "Manager",
      dialer: "Dialer",
      shared: "Shared line",
      excluded: "Excluded",
    } as Record<string, string>,
    noRole: "—",
    editor: {
      title: (name: string) => `Connect ${name} to an Agent`,
      agent: "Agent",
      chooseAgent: "Choose an Agent",
      role: "Role",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      hint: "Calls on this extension count for the Agent from now on.",
    },
    confirm: {
      text: (agent: string, user: string) => `Disconnect ${agent} from ${user}? Calls on this extension stop counting for ${agent}.`,
      yes: "Disconnect",
      no: "Keep",
    },
    connected: (agent: string, user: string) => `${agent} is connected to ${user}.`,
    disconnected: (user: string) => `${user} is not connected now.`,
    conflict: "This account changed while you were editing. The latest version is loaded — check it and try again.",
    empty: "No RingCentral users in the directory yet.",
    error: "Accounts couldn't load.",
    retry: "Retry",
    unnamed: "Unnamed user",
  },
  message: {
    region: "Message a RingCentral user",
    title: (name: string) => `Message ${name}`,
    intro: "Your own note to this user inside RingCentral. It never goes to a customer.",
    channel: "Send by",
    channels: { pager: "Pager", team_messaging: "Team Messaging" } as Record<string, string>,
    body: "Message",
    placeholder: "Write a short note…",
    preview: "Preview",
    previewing: "Checking…",
    previewTitle: "They will get",
    edit: "Edit",
    send: "Send",
    sending: "Sending…",
    statuses: {
      sent: "Sent.",
      fallback_sent: "Sent by pager instead.",
      failed: "Not delivered. Try again later.",
      unknown_delivery: "Sent, but delivery isn't confirmed yet.",
      pending: "Sending…",
    } as Record<string, string>,
    noAccount: "This user can't be messaged yet.",
    close: "Close",
  },
  planStatus: {
    active: "active",
    fulfilled: "done",
    missed: "missed",
    cancelled: "cancelled",
    replaced: "replaced",
    blocked_reschedule: "needs a new time",
  } as Record<string, string>,
  windows: {
    date: "Day",
    calls: "Calls",
    sms: "SMS",
    cell: (completed: number, required: number, missed: number | null) =>
      `${completed} / ${required}${missed ? ` · ${missed} missed` : ""}`,
  },
} as const;

export type DeskCopy = typeof deskCopy;
