/**
 * Every owner/rep-visible string of the Sales Outreach Desk ("Lead outreach"). Display only: query keys, server codes
 * and DTO field names never appear on screen (snake_case identifiers are mapped here to words). Policy facts such as
 * required counts and schedule days always come from the server; nothing here states a cadence rule.
 */
import type { DeskView } from "./data/desk-url";

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const deskCopy = {
  brand: "Lead outreach",
  nav: {
    label: "Lead outreach",
    views: {
      team: "Team overview",
      my: "My work",
      activity: "Activity",
      settings: "Settings",
      numbers: "All Numbers",
      accounts: "Accounts",
    } satisfies Record<DeskView, string>,
    dailyOperations: "Daily Operations",
    adminDashboard: "Admin dashboard",
    more: "Elsewhere",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
  },
  titles: {
    team: "Team outreach",
    my: "My outreach",
    myInspecting: (name: string) => `${name} · outreach`,
    activity: "Activity",
    settings: "Settings",
    numbers: "All Numbers",
    accounts: "RingCentral Accounts",
  },
  roles: {
    owner: "Owner",
    manager: "Manager",
    rep: "Sales Representative",
  },
  identity: {
    menu: "Account menu",
    signOut: "Sign out",
    signingOut: "Signing out…",
  },
  notAllowed: {
    title: "This page isn't part of your desk",
    body: "Your account can't open this view.",
  },
  text: {
    pending: "Pending",
    unknown: "Unknown",
    unavailable: "Unavailable",
    never: "Never",
    today: "Today",
    yesterday: "Yesterday",
    justNow: "just now",
    minAgo: (n: number) => `${n} min ago`,
    hoursAgo: (n: number) => `${n} h ago`,
    daysAgo: (n: number) => `${plural(n, "day", "days")} ago`,
    minutes: (n: number) => plural(n, "minute", "minutes"),
    hours: (n: number) => plural(n, "hour", "hours"),
    days: (n: number) => plural(n, "day", "days"),
    day: (n: number) => `Day ${n}`,
    synced: "Synced",
    delayed: "Delayed",
    notConnected: "Not connected",
    goalReached: "Goal reached",
    overdue: "Overdue",
    overdueBy: (duration: string) => `${duration} overdue`,
    dueToday: "Due today",
    smsDueToday: "SMS due today",
    dueTomorrow: "Due tomorrow",
    dueOn: (date: string) => `Due ${date}`,
    scheduled: "Scheduled",
    done: "Done",
    sent: "Sent",
    blocked: "Blocked",
    notRequired: "Not required",
    callOverdue: "Call overdue",
    callOverdueBy: (duration: string) => `Call overdue by ${duration}`,
    smsOverdue: "SMS overdue",
    callAndSmsOverdue: "Call and SMS overdue",
    overdueWork: "Contact overdue",
    callDueToday: "Call due today",
    callAndSmsDue: "Call and SMS due today",
    contactBlocked: "Contact blocked",
    needsReview: "Needs review",
    jobPending: "Job number pending",
    moveDatePassed: "Move date passed",
    noIssue: "On track",
    unassigned: "Unassigned",
    unknownRep: "Unknown rep",
  },
  unknownReasons: {
    cadence_disabled: "Cadence isn't running yet",
    cadence_shadow: "Cadence is in shadow mode",
    policy_unavailable: "Policy unavailable",
    coverage_incomplete: "Waiting for RingCentral capture coverage",
  } as Record<string, string>,
  goalStates: {
    goal: "",
    no_goal_today: "No goal today",
    not_on_roster: "Not on roster",
  } as Record<string, string>,
  workflows: {
    new: "New",
    quoted: "Quoted",
    discretion: (code: string | null) => (code ? `Priority ${code}` : "Rep discretion"),
    code: (code: string) => `Priority ${code}`,
    none: "No policy",
  },
  freshness: {
    label: "Data freshness",
    sources: { granot: "Moving software", calls: "RingCentral calls", sms: "RingCentral SMS" },
    updated: (source: string, age: string) => `${source} updated ${age}`,
    observed: (age: string) => `Moving software observed ${age}`,
    completeThrough: (source: string, at: string) => `${source} is complete through ${at}`,
    delayed: (source: string) => `${source} is delayed`,
    notConnected: (source: string) => `${source} is not connected`,
    unknown: (source: string) => `${source} status is unknown`,
  },
  live: {
    updated: "Desk updated",
    unavailable: "Live updates paused",
  },
  errors: {
    conflict: "This lead changed while you were editing. The latest version is loaded — check it and try again.",
    forbidden: "Your account can't make this change.",
    failed: (message: string | null) => (message ? `That didn't work: ${message}` : "That didn't work. Try again."),
  },
  unavailable: {
    title: "The Outreach Desk isn't available yet",
    desk_disabled: "The desk is switched off in Settings.",
    configuration_uninitialized: "The desk hasn't been set up yet.",
    configuration_unavailable: "The desk's configuration can't be read right now.",
    notLinked: "Your account isn't linked to a reviewed RingCentral sales extension yet. Ask the Owner to link it.",
    forbidden: "Your account can't open the Outreach Desk.",
    error: "The desk couldn't load. It will retry automatically.",
    ownerSettings: "Open Settings",
    retry: "Retry",
    notPermitted: "This page isn't part of your desk.",
    backToDesk: "Go to my desk",
  },
  team: {
    toolbar: "Team filters",
    today: "Today",
    pickDay: "Business day",
    allReps: "All reps",
    unassigned: "Unassigned",
    allLeads: "All leads",
    new: "New",
    quoted: "Quoted",
    leadFilter: "Lead type",
    search: "Search job # or phone",
    cards: {
      outbound: "Outbound calls",
      repsAtGoal: "Reps at goal",
      overdue: "Overdue leads",
      quotedGaps: "Quoted leads with gaps",
      ofGoal: (pct: string) => `${pct} of goal`,
      ofReps: (pct: string) => `${pct} of reps`,
      partial: (n: number) => `${plural(n, "rep", "reps")} still pending`,
      otherOutbound: (n: string) => `Other outbound: ${n}`,
      unassigned: (n: string) => `${n} unassigned`,
      distinctLeads: "Distinct leads with an overdue call or SMS",
      quotedLeads: "Quoted leads with an overdue call",
      noGoals: "No rep has a goal today",
    },
    goals: {
      title: "Daily call goals",
      subtitle: (scope: string) => `Outbound calls per rep · ${scope}`,
      scopeAll: "All outbound calls",
      scopeEligible: "New + quoted leads",
      scopeMixed: "scope differs by rep today",
      columns: { rep: "Sales rep", calls: "Calls today", progress: "Daily progress", remaining: "Calls remaining", overdue: "Overdue leads", action: "Action" },
      viewQueue: "View queue",
      overdueCount: (n: number) => `${n} overdue`,
      noneOverdue: "0 overdue",
      awaiting: (n: number) => `+${n} unconfirmed`,
      awaitingTitle: "Seen live but not yet in the RingCentral Call Log; not counted until confirmed.",
      callsOnly: (n: number) => `${plural(n, "call", "calls")}`,
      coverage: "Call capture incomplete",
      footnote: "Call totals can exceed the goal. Progress bars cap at 100%.",
      otherFootnote: "“Other outbound” are calls to numbers with no eligible New or Quoted lead; they don't count toward the goal.",
      empty: "No rep is on today's roster yet.",
      unavailable: "Goal tracking is switched off in Settings.",
      setGoal: "Attendance",
    },
    attention: {
      title: "Leads needing attention",
      columns: { job: "Job / phone", owner: "Owner", priority: "Priority", issue: "Issue", last: "Last outreach", action: "Action" },
      sort: "Sort",
      empty: "Nothing needs attention right now.",
      unavailable: "Lead cadence isn't running yet, so there's no attention list.",
      footnote: "Calls and SMS update automatically from RingCentral.",
      unassignedDrill: (n: string) => `${n} unassigned · view`,
      more: "Open full queue",
    },
    operations: {
      title: "Operations today",
      open: "Open Daily Operations",
      leads: "Leads",
      bookings: "Bookings",
      cancellations: "Cancellations",
      texts: "Texts sent",
      textsScope: "automated confirmations",
      unreconstructable: (n: number) => `${plural(n, "sent text", "sent texts")} without a recorded send time`,
      unavailable: "Daily Operations isn't available right now.",
    },
  },
  my: {
    goalTitle: "Today's outbound calls",
    goalTitleFor: (day: string) => `Outbound calls · ${day}`,
    toGoal: (n: number) => `${plural(n, "call", "calls")} to reach your goal`,
    goalMet: "Goal reached — keep going",
    waitingCapture: "Waiting for RingCentral call capture",
    noGoal: "No goal today",
    overdue: "overdue",
    overdueUnit: "leads",
    callsDue: "calls due",
    smsDue: "SMS due",
    metricUnavailable: "unavailable",
    awaiting: (n: number) => `${n} awaiting confirmation`,
    tabs: { all: "All leads", new: "New leads", quoted: "Quoted leads" },
    tabsLabel: "Lead type",
    work: { needs_contact: "Needs contact", all_active: "All active" },
    workLabel: "Work filter",
    search: "Search job # or phone",
    flow: "Copy job # → Open moving software → Contact lead",
    queueTitle: "Contact next",
    sorts: { urgency: "Overdue first", lead_received: "Lead received", last_interaction: "Last interaction" },
    sortLabel: "Sort queue",
    newest: "Newest first",
    oldest: "Oldest first",
    columns: { job: "Job / phone", age: "Lead age", last: "Last outreach", calls: "Calls today", sms: "SMS", copy: "Copy" },
    loadMore: "Load more",
    empty: "No leads match these filters.",
    emptyNeeds: "Nothing needs contact right now.",
    pendingCount: (n: number) => `${plural(n, "lead is", "leads are")} still being evaluated and not shown yet`,
    excludedUnknown: (n: number) => `${plural(n, "lead", "leads")} hidden because the move date is unknown`,
    queueUnavailable: "The queue isn't available until lead cadence is running.",
    cursorReset: "The list changed; showing the first page again.",
    selectHint: "Select a lead to see its details.",
    selectedNotInList: "The selected lead no longer matches these filters.",
    inspecting: (name: string) => `Viewing ${name}'s queue`,
    backToTeam: "Back to team",
    moveDate: "Move date",
    moveDates: { upcoming: "Upcoming", today: "Today", next7: "Next 7 days", past: "Past", unknown: "Unknown", any: "Any date", anyShort: "Any move date" },
  },
  lead: {
    region: "Selected lead",
    jobPending: "Job number pending",
    copy: "Copy job #",
    copied: "Copied",
    copyFailed: "Copy failed",
    copyDisabled: "No job number yet",
    newLead: "New lead",
    quotedLead: "Quoted lead",
    dayN: (n: number) => `Day ${n}`,
    todayNeeds: (calls: string, sms: string) => `Today: ${calls} + ${sms}`,
    callsUnit: (n: number | null) => (n === null ? "calls pending" : `${n} ${n === 1 ? "call" : "calls"}`),
    smsUnit: (n: number | null) => (n === null ? "SMS pending" : `${n} SMS`),
    nextCallDue: "Next call due now",
    callOverdue: "Call overdue",
    callDueBy: (time: string) => `Call due by ${time}`,
    smsOverdue: "SMS overdue",
    smsDue: "SMS due today",
    allDone: "Today's contact is done",
    spacing: "Space attempts across the day",
    recentActivity: "Recent activity",
    noActivity: "No calls or texts recorded yet.",
    automaticTitle: "Automatic tracking",
    automaticBody: "Contact this job in the moving software and RingCentral. Outreach updates here automatically.",
    policyTitle: "This lead's schedule",
    schedule: {
      title: "New lead schedule",
      firstDays: (required: number, optional: number) =>
        `Days 1–3: ${plural(required, "call", "calls")} required${optional ? `, ${optional} optional` : ""}`,
      slot: (from: number, to: number | null, perDay: number) =>
        `${to === null ? `Day ${from} on` : from === to ? `Day ${from}` : `Days ${from}–${to}`}: ${plural(perDay, "call", "calls")} a day`,
      sms: (initial: number[], repeatFrom: number, every: number) =>
        `SMS: ${initial.length ? `${initial.length === 1 ? "Day" : "Days"} ${initial.join(", ")}, then ` : ""}every ${plural(every, "day", "days")} from Day ${repeatFrom}`,
    },
    footnote: "Calls and SMS update automatically from RingCentral.",
    assignedTo: "Assigned to",
    reassign: "Reassign",
    assignLabel: "Assigned rep",
    saveAssign: "Save",
    quotedDate: "Quoted follow-up date",
    setQuoted: "Set date",
    callback: "Callback",
    scheduleCallback: "Schedule a callback",
    setCallback: "Set callback",
    cancelCallback: "Cancel callback",
    callbackAt: (when: string) => `Callback ${when}`,
    revoked: "This lead is no longer in your queue.",
    loading: "Loading lead…",
    close: "Close",
    events: {
      outbound_attempt: "Outbound call",
      inbound_answered: "Inbound call answered",
      inbound_missed: "Missed inbound call",
      sms_sent: "SMS sent",
      sms_failed: "SMS failed",
      sms_inbound: "SMS received",
      other: "Contact",
    } as Record<string, string>,
    verification: {
      confirmed: "",
      awaiting_confirmation: "awaiting confirmation",
      pending_identity: "rep pending",
      pending_association: "lead match pending",
      excluded: "not counted",
    } as Record<string, string>,
    explanation: {
      cadence_shadow: "Cadence is in shadow mode: no overdue labels yet.",
      priority_intake_default: "No priority from the moving software yet; treated as a new lead by default.",
      priority_accepted_observation: "Priority comes from the moving software.",
      priority_uncertain: "The priority is uncertain and waiting for review.",
      review: "Needs review",
      quoted_date: "Quoted follow-up date",
      callback: "Callback",
      restriction_call: "Calls are blocked by a contact restriction",
      restriction_sms: "SMS is blocked by a contact restriction",
      move_date_passed: "The move date has passed",
      move_date_unknown: "The move date is unknown",
      job_number_pending: "The job number isn't in the moving software yet",
      advisory_cooldown: "Several attempts went unanswered; consider spacing them out.",
      inherited_overdue: "Overdue work carried over from before the reassignment",
      engine_state: "Schedule state",
      projection_pending: "Still being evaluated",
      cadence_disabled: "Cadence isn't running yet",
      policy_unavailable: "Policy unavailable",
      stale_policy: "Policy changed; recalculating",
    } as Record<string, string>,
  },
  activity: {
    title: "Activity",
    subtitle: "Read-only contact history for active leads, most recent first.",
    listTitle: "Recently contacted",
    empty: "No activity yet.",
    detailTitle: "Contact history",
    assignmentChanges: "Assignment changes",
    planHistory: "Follow-up plans",
    windowHistory: "Daily requirements",
    missedHidden: "Missed counts appear once cadence enforcement is on.",
  },
  settings: {
    title: "Settings",
    ownerSubtitle: "Desk controls, goals and roster, contact restrictions and enrollment. Owner only.",
    managerSubtitle: "Attendance for today and upcoming days.",
    repSubtitle: "Your desk settings.",
    controls: "Desk controls",
    controlNames: {
      desk_enabled: "Desk on",
      goal_metrics_enabled: "Goal tracking",
      rep_sms_capture_enabled: "Rep SMS capture",
      cadence_shadow_enabled: "Cadence (shadow)",
      cadence_enforcement_enabled: "Cadence enforcement",
      intake_admission_enabled: "Admit new leads automatically",
    } as Record<string, string>,
    on: "On",
    off: "Off",
    roster: "Roster and daily goals",
    restrictions: "Contact restrictions",
    restrictionsHint: "Restrictions from the old intelligence stay active and blocking until you confirm or lift each one.",
    confirm: "Confirm",
    lift: "Lift",
    liftReason: "Reason for lifting",
    enrollment: "Enrollment",
    attendance: "Attendance",
    attendanceHint: "Record an absence or a partial day before it happens. Past days are Owner-only.",
    absence: "Absent (goal 0)",
    partialDay: "Partial day",
    goal: "Goal",
    save: "Save",
    saved: "Saved",
    repNote: "Your goal, schedule and assigned leads are set by the Owner or your manager.",
  },
  settingsExtra: {
    blockers: (n: number) => `${plural(n, "activation blocker", "activation blockers")} reported by the server`,
    policy: (policy: string | null, version: string | null, at: string | null) =>
      [policy ? `Policy ${policy}` : "No policy installed", version ? `configuration ${version}` : null, at ? `updated ${at}` : null].filter(Boolean).join(" · "),
    defaultGoal: "Default daily goal",
    workingDays: "Working days",
    closures: "Closures",
    noClosures: "No closures scheduled.",
    addClosure: "Add a closure date",
    remove: "Remove",
    channels: "Blocks",
    channel: { call: "Calls", sms: "SMS" } as Record<string, string>,
    origin: "Origin",
    originOwner: "Owner",
    originIntelligence: "Old intelligence",
    needsReview: "Needs review",
    reason: "Reason",
    until: "Until",
    noEnd: "No end date",
    noRestrictions: "No active contact restrictions.",
    enrollmentHint: "Eligible leads outside the backfill window are listed here as “Not enrolled — older”. Enroll adds one lead to the desk.",
    olderHint: (days: number | null) => (days ? `Not enrolled — older than ${days} days, with no upcoming move.` : "Not enrolled — older."),
    received: "Received",
    noOlder: "No older eligible leads.",
    enroll: "Enroll",
    notEligible: "This lead isn't eligible any more.",
    migrationPaused: "Enrollment is paused in the configuration (migration paused).",
    enrolled: (status: string) => `Enrollment ${status}.`,
    attendanceOwner: "Record an absence or a partial day. Owners may also correct past days.",
    chooseRep: "Choose a rep",
    date: "Date",
    kind: "Type",
  },
  numbers: {
    subtitle: "Every outside number that called us or that we called, and who it is.",
    toolbar: "Number filters",
    cards: {
      waiting: "Waiting on us",
      waitingCaption: "Called, nobody answered, nobody called back",
      noneWaiting: "Nobody is waiting",
      all: "All numbers",
      allCaption: "Callers, numbers we called and form leads",
    },
    segments: { all: "All", waiting: "Waiting on us" },
    segmentLabel: "Show",
    search: "Search number, name or job #",
    listTitle: { all: "All numbers", waiting: "Waiting on us" },
    listSubtitle: { all: "Most recent activity first", waiting: "Longest wait first" },
    columns: { number: "Number", lead: "Lead", last: "Last call", calls: "Calls", waiting: "Waiting" },
    unknown: "Unknown",
    formLead: "Form lead",
    noCalls: "No calls yet",
    callsInOut: (inbound: number, outbound: number) => `${inbound} in · ${outbound} out`,
    missed: (n: number) => `${n} missed`,
    job: (job: string) => `Job ${job}`,
    noJob: "No job # yet",
    pinned: "Linked by you",
    loadMore: "Load more",
    showing: (shown: number, total: number) => `Showing ${shown} of ${total}`,
    empty: "No numbers yet.",
    emptyWaiting: "Nobody is waiting on us right now.",
    emptySearch: "No numbers match this search.",
    error: "All Numbers couldn't load.",
    retry: "Retry",
    results: { answered: "Answered", missed: "Missed", voicemail: "Voicemail", noAnswer: "No answer" },
    directions: { inbound: "Incoming call", outbound: "Outgoing call" },
    leadStates: { open: "Open", booked: "Booked", cancelled: "Cancelled" },
  },
  numberPanel: {
    region: "Selected number",
    close: "Close",
    loading: "Loading number…",
    notFound: "This number isn't available any more.",
    error: "This number couldn't load.",
    waitingFor: (duration: string) => `Waiting on us for ${duration}`,
    waitingSub: (when: string) => `Missed call ${when}. Nobody has called back yet.`,
    handled: "Not waiting on us",
    facts: { firstSeen: "First seen", lastActivity: "Last activity", calls: "Calls", missed: "Missed" },
    leadTitle: "Lead",
    unknownTitle: "Unknown",
    unknownBody: "No lead has this phone number. Link one if you know who it is.",
    openInDesk: "Open in desk",
    rep: (name: string) => `Rep: ${name}`,
    noRep: "No rep",
    received: (when: string) => `Received ${when}`,
    linkedByYou: "Linked by you",
    matchedByPhone: "Matched by phone",
    creditNote: "This lead gets the Outreach Desk credit for calls with this number.",
    otherLeads: "Other leads with this number",
    useThis: "Use this lead",
    excludedTitle: "Unlinked leads",
    linkAgain: "Link again",
    link: "Link to a lead",
    linkOther: "Link a different lead",
    unlink: "Unlink",
    unlinkHint: "Unlinked leads are never matched to this number again.",
    picker: {
      label: "Search leads by name, job # or phone",
      hint: "Type at least 2 characters.",
      empty: "No leads match.",
      searching: "Searching…",
      choose: "Link",
      cancel: "Cancel",
      current: "Linked now",
    },
    conflict: "This number changed while you were looking. The latest version is loaded — check it and try again.",
    linked: (name: string) => `Linked to ${name}.`,
    unlinked: (name: string) => `${name} unlinked.`,
    callsTitle: "Calls",
    noCalls: "No calls with this number yet.",
    moreCalls: "Only the latest 100 calls are shown.",
    recordings: (n: number) => `${n} ${n === 1 ? "recording" : "recordings"}`,
    on: (number: string) => `on ${number}`,
    from: (number: string) => `from ${number}`,
    seconds: (n: number) => `${n} s`,
    minutes: (m: number, s: number) => (s ? `${m} min ${s} s` : `${m} min`),
    unnamedLead: "Unnamed lead",
  },
  accounts: {
    subtitle: "RingCentral users and the Agent each one is connected to. A change takes effect right away.",
    directoryAt: (when: string) => `Directory updated ${when}`,
    noDirectory: "No directory snapshot yet",
    suggest: "Suggest matches",
    suggesting: "Suggesting…",
    suggestedNone: "No new matches found.",
    suggested: (n: number) => `${n} ${n === 1 ? "match" : "matches"} to review.`,
    cards: {
      connected: "Connected",
      connectedCaption: (n: number) => `of ${n} users`,
      notConnected: "Not connected",
      notConnectedCaption: "No Agent, so their calls count for nobody",
      suggestions: "Suggested matches",
      suggestionsCaption: "One click to connect",
    },
    listTitle: "RingCentral users",
    columns: { user: "User", direct: "Direct number", agent: "Agent", role: "Role", actions: "Actions" },
    ext: (n: string) => `Ext. ${n}`,
    noExt: "No extension",
    noDirect: "None",
    notConnected: "Not connected",
    notInDirectory: "Not in directory",
    connect: "Connect",
    change: "Change",
    disconnect: "Disconnect",
    message: "Message",
    connectSuggested: (name: string) => `Connect ${name}`,
    roles: {
      sales_rep: "Sales rep",
      service: "Service",
      manager: "Manager",
      dialer: "Dialer",
      shared: "Shared line",
      excluded: "Excluded",
    } as Record<string, string>,
    noRole: "—",
    editor: {
      title: (name: string) => `Connect ${name} to an Agent`,
      agent: "Agent",
      chooseAgent: "Choose an Agent",
      role: "Role",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      hint: "Calls on this extension count for the Agent from now on.",
    },
    confirm: {
      text: (agent: string, user: string) => `Disconnect ${agent} from ${user}? Calls on this extension stop counting for ${agent}.`,
      yes: "Disconnect",
      no: "Keep",
    },
    connected: (agent: string, user: string) => `${agent} is connected to ${user}.`,
    disconnected: (user: string) => `${user} is not connected now.`,
    conflict: "This account changed while you were editing. The latest version is loaded — check it and try again.",
    empty: "No RingCentral users in the directory yet.",
    error: "Accounts couldn't load.",
    retry: "Retry",
    unnamed: "Unnamed user",
  },
  message: {
    region: "Message a RingCentral user",
    title: (name: string) => `Message ${name}`,
    intro: "Your own note to this user inside RingCentral. It never goes to a customer.",
    channel: "Send by",
    channels: { pager: "Pager", team_messaging: "Team Messaging" } as Record<string, string>,
    body: "Message",
    placeholder: "Write a short note…",
    preview: "Preview",
    previewing: "Checking…",
    previewTitle: "They will get",
    edit: "Edit",
    send: "Send",
    sending: "Sending…",
    statuses: {
      sent: "Sent.",
      fallback_sent: "Sent by pager instead.",
      failed: "Not delivered. Try again later.",
      unknown_delivery: "Sent, but delivery isn't confirmed yet.",
      pending: "Sending…",
    } as Record<string, string>,
    noAccount: "This user can't be messaged yet.",
    close: "Close",
  },
  planStatus: {
    active: "active",
    fulfilled: "done",
    missed: "missed",
    cancelled: "cancelled",
    replaced: "replaced",
    blocked_reschedule: "needs a new time",
  } as Record<string, string>,
  windows: {
    date: "Day",
    calls: "Calls",
    sms: "SMS",
    cell: (completed: number, required: number, missed: number | null) =>
      `${completed} / ${required}${missed ? ` · ${missed} missed` : ""}`,
  },
} as const;

export type DeskCopy = typeof deskCopy;
