/**
 * Owner-visible strings of Setup → Carriers (doc 19 "Carriers"). Words: Moving Carrier, Granot Carrier Code.
 * Every string passes `lib/operations-registry/ownerLanguageDeck.ts`. No em-dashes; sentence case.
 */
export const CARRIERS_COPY = {
  addCarrier: "Add carrier",
  importCsv: "Import CSV",
  readOnlyNote: "You can look at the carrier list here. Adding, importing and editing carriers needs the owner role.",
  searchPlaceholder: "Search name, DOT, MC or Granot code",
  includeInactive: "Include inactive",
  listTitle: "Moving carriers",
  listSubtitle: "DOT and MC together identify a carrier. The Granot Carrier Code is the Forms View agent short name used for tariff work.",
  count: (shown: number, total: number) => (shown === total ? `${total} carriers` : `${shown} of ${total} carriers`),
  loading: "Loading moving carriers",
  readFailure: "The carrier list did not load.",
  empty: "No carriers yet.",
  emptyHint: "Add one, or import a CSV.",
  noMatch: "No carrier matches that search.",
  columns: { carrier: "Carrier", dot: "DOT", mc: "MC", code: "Granot Carrier Code", status: "Status", actions: "Actions" },
  noCode: "No code",
  active: "Active",
  inactive: "Inactive",
  deactivate: "Deactivate",
  reactivate: "Reactivate",
  edit: "Edit",
  view: "View",
  sheet: {
    createTitle: "Add a carrier",
    editTitle: "Edit carrier",
    viewTitle: "Carrier",
    name: "Carrier name",
    dot: "DOT",
    mc: "MC",
    code: "Granot Carrier Code",
    codeHint: "Optional. Letters and numbers, no spaces. Clearing it removes the code.",
    identityHint: "DOT and MC together identify this carrier. Two carriers cannot share the same pair.",
    statusLabel: "Status",
    activeChoice: "Active",
    activeHint: "Shown on the main site and used for tariff work.",
    inactiveChoice: "Inactive",
    inactiveHint: "Kept with its history, hidden from the active list.",
    required: "Carrier name, DOT and MC are required.",
    save: "Save changes",
    create: "Add carrier",
    saving: "Saving",
    cancel: "Cancel",
    createdFrom: (source: string) => `Created from ${source || "unknown"}`,
  },
  import: {
    title: "Import carriers from a CSV",
    intro: "The file needs Carrier Name, DOT and MC columns. A Granot Carrier Code column is optional.",
    stepFile: "Choose the file",
    stepMode: "Choose what the import does",
    stepCheck: "Check before you import",
    stepResult: "Result from the server",
    fileLabel: "Carrier CSV",
    noFile: "No file chosen yet.",
    fileRead: (name: string, rows: number) => `${name} · ${rows} ${rows === 1 ? "row" : "rows"}`,
    modeLabel: "Import mode",
    patchTitle: "Add and update from the file",
    patchHint: "Keep every carrier not in it.",
    replaceTitle: "Replace the active list",
    replaceHint: "Carriers missing from the file are deactivated.",
    waitingForList: "Loading the current carrier list to compare against.",
    emptyFile: "That file has no rows. Check that it is a CSV with a header row.",
    missingColumns: (names: string[]) => `The header has no ${names.join(", ")} column, so every row would be skipped.`,
    counts: {
      new: (n: number) => `${n} new`,
      updated: (n: number) => `${n} updated`,
      unchanged: (n: number) => `${n} unchanged`,
      wouldDeactivate: (n: number) => `${n} would be deactivated`,
      problems: (n: number) => `${n} ${n === 1 ? "row" : "rows"} with problems`,
    },
    problemsTitle: "Rows with problems",
    problemLine: (line: number, reason: string) => `Row ${line}: ${reason}`,
    moreProblems: (n: number) => `and ${n} more`,
    deactivateTitle: "Carriers that would be deactivated",
    updateReasons: { name: "new name", reactivated: "reactivated", granot_code: "new Granot code" },
    honest: "This preview is read in your browser. The server does the final check and may skip rows it rejects.",
    runPatch: "Import",
    runReplace: "Replace the active list",
    running: "Importing",
    confirmTitle: (n: number) => `This deactivates ${n} ${n === 1 ? "carrier" : "carriers"}.`,
    confirmBody: "They stay in the list with their history and can be reactivated one by one. Carriers in the file are kept or added.",
    confirmAction: (n: number) => `Deactivate ${n} and import`,
    confirmBack: "Go back",
    nothingToImport: "Nothing in this file can be imported.",
    resultMode: (mode: "patch" | "replace") => (mode === "replace" ? "Replace the active list" : "Add and update"),
    result: {
      created: (n: number) => `${n} created`,
      updated: (n: number) => `${n} updated`,
      deactivated: (n: number) => `${n} deactivated`,
      skipped: (n: number) => `${n} skipped`,
      rowErrors: "Rows the server skipped",
      rowError: (row: number, message: string) => `Row ${row}: ${message}`,
      importAnother: "Import another file",
      done: "Done",
    },
    failed: "The import did not run.",
    close: "Close",
  },
} as const;
