/** Money copy (doc 19 "Money"): Merchants that take deposits. No em-dashes. */

export const MERCHANTS_COPY = {
  merchants: "Merchants",
  includeInactive: "Include inactive",
  active: "Active",
  inactive: "Inactive",
  alsoKnownAs: (aliases: string) => `Also known as ${aliases}`,
  depositsRecorded: (n: number) => `${n} ${n === 1 ? "deposit recorded" : "deposits recorded"}`,
  depositsHint: "Open the card to see deposits recorded",
  empty: "No merchants yet.",
  readFailed: "Merchants couldn't load.",
  edit: "Edit",
  add: "Add merchant",
  addTitle: "Add a merchant",
  editTitle: (name: string) => `Merchant · ${name}`,
  name: "Merchant name",
  nameHint: "Renaming keeps the old name as an alias, so past deposits still match.",
  namePlaceholder: "New merchant",
  nameRequired: "Enter a name.",
  reason: "Reason (optional)",
  reasonPlaceholder: "Why you are changing this",
  create: "Add merchant",
  created: "Merchant added.",
  save: "Save",
  saved: "Merchant updated.",
  deactivate: "Deactivate",
  reactivate: "Reactivate",
  deactivated: "Merchant deactivated.",
  reactivated: "Merchant reactivated.",
  previewTitle: "Before you deactivate",
  previewTotal: (n: number) => `${n} ${n === 1 ? "record depends" : "records depend"} on this.`,
  previewNone: "Nothing depends on this.",
  previewFailed: "Couldn't check what depends on this.",
  confirmDeactivate: "Confirm deactivation",
  keepActive: "Keep active",
  deactivationReason: (reason: string) => `Deactivation reason: ${reason}`,
  saving: "Saving…",
  repPay: "Rep compensation is server work and arrives with Today → Money.",
  repPayLink: "Open Today → Money",
  readOnlyNote: "You can read the Merchants here. The Owner changes them.",
} as const;
