/**
 * Owner-visible words of Setup → Lead sources (doc 19). Glossary words only: Feed (never the engineering name),
 * Granot name, Inbound Number, Lead Cost. No em-dashes (use "·"), sentence case, every string passes
 * `lib/operations-registry/ownerLanguageDeck.ts` (`tests/setup-lead-sources.test.ts` renders the surfaces and checks).
 * Pure: no React, so `needs-you.ts` and the node test runner can import it.
 */

export type LeadSourceChannel = "form" | "call";
export type GranotArrivalValue = "watch_only" | "existing_only" | "create_if_missing";

/** The Owner's three words for what happens when a lead arrives under a Granot name. */
export const ARRIVAL_WORDS: Record<GranotArrivalValue, string> = {
  existing_only: "attach to a lead we have",
  create_if_missing: "create the lead if missing",
  watch_only: "just watch",
};

export const ARRIVAL_HINTS: Record<GranotArrivalValue, string> = {
  existing_only: "We attach it to a lead we already have. We never create one. Best for our own forms.",
  create_if_missing:
    "If we have no matching lead, we create one in this feed. This is the only choice that can text the customer.",
  watch_only: "We record it as evidence. Nothing is created or changed. Best for referral partners.",
};

/** The long labels the Granot name sheet's radios keep (the editor's tests pin the order). */
export const ARRIVAL_LABELS: Record<GranotArrivalValue, string> = {
  watch_only: "Watch only",
  existing_only: "Use an existing lead only",
  create_if_missing: "Use an existing lead, or create it if missing",
};

export const CHANNEL_WORDS: Record<LeadSourceChannel, string> = {
  form: "web form",
  call: "phone calls",
};

export const LS_COPY = {
  addButton: "Add a lead source",
  viewLabel: "Lead sources view",
  views: { sources: "By source", granot: "Granot names", numbers: "Inbound numbers" },
  loadFailed: "The lead sources did not load.",
  empty: "No lead sources yet. Add the first one with the button above.",
  needsYouTitle: (count: number) => (count === 1 ? "1 thing needs you" : `${count} things need you`),
  needsYouLabel: "Things that need you",
  open: "Open",
  on: "On",
  off: "Off",
  live: "Live",
  notLive: "Not live",
  feeds: (count: number) => (count === 1 ? "1 feed" : `${count} feeds`),
  noFeeds: "No feeds yet",
  defaultPill: "Default",
  defaultPillTitle: (channel: LeadSourceChannel) => `The default feed for ${CHANNEL_WORDS[channel]}`,
  local: "Local",
  longDistance: "Long distance",
  edit: "Edit",
  editSource: "Edit this source",
  addFeed: "Add a feed",
  readyAllLive: "all live",
  readyNotLive: (count: number) => `${count} not live`,
  readyCostMissing: "lead cost missing",
  readyNoFeeds: "no feeds yet",
  expand: "Show feeds",
  collapse: "Hide feeds",
  readinessTitle: "Turn it on",
  readinessHint: "Each step is an existing audited command. A blocked step names what it waits on.",
  readinessButton: "Turn it on",
  readinessRunning: "Turning it on",
  readinessNone: "Nothing left to turn on.",
  readinessWaiting: "Waiting on",
  readinessSuggested: "Suggested next step. This lead source works without it.",
  readinessDone: "Done",
  readinessReady: "Ready",
  readinessBlocked: "Blocked",
  readinessFailed: "Failed",
  readinessSuggestedPill: "Suggested",
  findingsNone: "Nothing to fix. This lead source looks clear.",
  granotLine: "Granot name",
  numberLine: "Inbound number",
  costLine: "Lead cost",
  noGranotName: "No Granot name lands here yet",
  noInboundNumber: "No inbound number yet",
  addGranotName: "Connect a Granot name",
  addNumber: "Add an inbound number",
  setLeadCost: "Set lead cost",
  costMissing: "Missing",
  costInvalid: "Invalid",
  costReady: "Set",
  costSince: (amount: string, since: string) => `${amount} since ${since}`,
  costInvalidReason: "The schedule has a gap or an overlap. Open it to fix the periods.",
  customerTextOn: "customer text on",
  wrongChannel: "Lands in a feed of the wrong kind",
  wrongMoveType: "Lands in the wrong local or long distance feed",
  landsNowhere: "Lands nowhere",
  verified: "RingCentral verified",
  notChecked: "RingCentral not checked",
  invalid: "RingCentral says invalid",
  filing: "Filing calls",
  stopped: "Stopped",
  notFiling: "Not filing",
  lastSeen: (when: string) => `last seen ${when}`,
  sheetTab: (name: string) => `Sheet tab: ${name}`,
  sheetNames: (names: string) => `Sheet names accepted: ${names}`,
  sendsToGranot: (label: string) => `What Vantage sends to Granot: ${label}`,
  landsIn: (source: string, feed: string) => `lands in: ${source} → ${feed}`,
  waitingOn: (what: string) => `Waiting on: ${what}`,
  closeSheet: "Close",
  save: "Save",
  saving: "Saving",
  saved: "Saved.",
  why: "Why are you making this change?",
  whyOptional: "Why are you making this change? (optional)",
  whyHint: "Written to the change history. At least 10 characters.",
  readOnlyNote: "You can look at this, but only the owner can change it.",
  flatGranotTitle: "Every Granot name",
  flatNumbersTitle: "Every inbound number",
  flatGranotEmpty: "No Granot names yet.",
  flatNumbersEmpty: "No inbound numbers yet.",
  newGranotName: "New Granot name",
  newNumber: "Add an inbound number",
  inSource: (source: string, feed: string) => `${source} · ${feed}`,
  notFiledYet: "Not filed under a feed yet",
} as const;

export const FEED_SHEET_COPY = {
  title: (name: string) => name,
  titleNew: "Add a feed",
  blockWhat: "What it is called",
  blockSpellings: "How leads are matched to it",
  blockDefault: "Default for its channel",
  blockOnOff: "On or off",
  showAs: "Show it as",
  showAsHint: "What you pick in filters and reports.",
  granotCalls: "What Granot calls it",
  granotCallsHint:
    "The exact label Vantage puts on every lead from this feed when it posts to Granot. It must not match another active feed of the same kind.",
  moveType: "Local or long distance",
  moveTypeNone: "Not split by move type",
  otherSpellings: "Other spellings",
  otherSpellingsHint: "Separate with commas. Used only when an incoming lead does not match exactly.",
  websites: "Website identifiers",
  websitesHint: "Separate with commas. The sites whose forms feed this one.",
  sheetTab: "Sheet tab name",
  sheetTabHint: "The tab in the Master Sheet that holds this feed's leads.",
  kind: "How the leads arrive",
  kindLocked: "The kind cannot change once the feed has been on.",
  kindForm: "Web form",
  kindCall: "Phone calls",
  makeDefault: (channel: LeadSourceChannel) => `Make default for ${CHANNEL_WORDS[channel]}`,
  isDefault: (channel: LeadSourceChannel) => `This is the default feed for ${CHANNEL_WORDS[channel]}.`,
  defaultOnTurnOn: "Turning a feed on makes it the default for its channel.",
  turnOn: "Turn this feed on",
  turnOff: "Turn this feed off",
  turnOffPreview: "See what turning it off affects",
  confirmOff: "Turn it off",
  cancel: "Cancel",
  previewTitle: "Turning this feed off affects",
  previewNone: "Nothing depends on this feed.",
  replacement: "Another feed becomes the default",
  replacementNone: "No other feed is on for this channel.",
  replacementPick: "Choose a feed",
  removeAutomatic: "No feed becomes the default; new leads for this channel will need a feed picked by hand",
  keysQuiet: (key: string, kind: string) => `Internal key ${key} · ${kind} · fixed after the feed is created`,
  addCreate: "Add feed",
  keyLabel: "Internal key",
  keyHint: "Lowercase letters, numbers and underscores. Fixed once the feed exists.",
  costLink: "Set the lead cost",
} as const;

export const SOURCE_SHEET_COPY = {
  title: (name: string) => name,
  blockWhat: "What it is called",
  blockSheet: "Master Sheet",
  blockOnOff: "On or off",
  name: "Name",
  nameHint: "The partner's real name, for our records. Customer texts still say Vantage Movers.",
  showAs: "Show it as",
  showAsHint: "What you will pick in filters and reports.",
  spellings: "Also accept these spellings",
  spellingsHint: "Separate with commas. Used only when an incoming lead does not match exactly.",
  sheetId: "Spreadsheet ID",
  sheetIdHint: "The Google Sheet this source's leads are read from.",
  mode: "How the sheet is used",
  modeImport: "Read leads from the sheet",
  modeWrite: "Write leads to the sheet too",
  turnOn: "Turn this lead source on",
  turnOff: "Turn this lead source off",
  previewTitle: "Turning this lead source off affects",
  confirmOff: "Turn it off",
  keyQuiet: (key: string) => `Internal key ${key} · fixed`,
  testTitle: "Test where a lead would land",
  testHint: "Fill in what a lead carries and see which feed it would be filed under.",
  testRun: "Test it",
  testResolved: (source: string, feed: string, how: string) => `It would land in ${source} · ${feed} (${how}).`,
  testNotFound: "Nothing matches. The lead would not be filed under a feed.",
  testAmbiguous: "More than one feed matches, so the lead would not be filed automatically.",
  testMatchExact: "exact match",
  testMatchDefault: "the default feed",
  testMatchFallback: "fallback spelling",
  testChannel: "How it arrives",
  testCompany: "Lead source key",
  testFeed: "Feed key",
  testLabel: "What Granot calls it",
  testSite: "Website",
  testAlias: "Other spelling",
} as const;

export const GRANOT_SHEET_COPY = {
  titleNew: "New Granot name",
  titleFallback: "Granot name",
  intro: "One Granot name lands in one lead source and one feed. Texts say Vantage Movers.",
  blockWhat: "What Granot calls it",
  blockWhere: "Where it lands",
  blockWhen: "When a lead arrives",
  blockText: "Customer text",
  blockLive: "Live or not live",
  nameLabel: "Name received from Granot",
  kindLegend: "What kind of source is this?",
  kindOur: "Our lead source",
  kindReferral: "Referral booking",
  kindWatch: "Watch only",
  whichSource: "Which lead source?",
  whichSourcePick: "Select a lead source",
  whichFeed: "Which feed does it connect to?",
  whichFeedPick: "Select a feed",
  splitToggle: "Different Feed for local and long-distance moves",
  localFeed: "Local feed",
  longFeed: "Long-distance feed",
  localPick: "Select local feed",
  longPick: "Select long-distance feed",
  arrivalLegend: "When a lead arrives",
  textOffNotCreating: "Customer text is off because this Granot name does not create Leads.",
  textTitle: "Text the customer",
  textState: (on: boolean) => `Customer text is ${on ? "on" : "off"}.`,
  textTemplateChanged:
    "Saving a new message turns texting off. You will turn it back on after reviewing the new message.",
  textWhy: "Why we may text this customer",
  textWhySubmitted: "They filled out a form that reached this lead source",
  textWhyExisting: "We have an active enquiry or existing business with them",
  textWhyNone: "Not recorded yet · texting stays off",
  textMessage: "Message",
  textMessageHint: "You can use {first_name}. Texts say Vantage Movers. Do not insert a partner name.",
  textLength: (n: number) => `${n} / 320 including the opt-out line`,
  textTurnOn: "Turn this text on",
  textSavedWith: "Saving this Granot name also saves the message and whether texting is on.",
  textNoSends: "No recent sends.",
  review: "Review",
  save: "Save",
  saveNew: "Save Granot name",
  liveTitle: "Use this Granot name in live processing",
  liveOn: "Use in live processing",
  liveOff: "Turn live processing off",
  liveWhy: "Why?",
  readOnly: "Read-only view.",
  normalized: (value: string) => `We will match this as \`${value}\`. Your entry had extra spacing.`,
  normalizedPreview: (value: string) => `Normalized preview: ${value || "none"}`,
  diagnostic: "Diagnostic",
  landsNowhereNote: "This Granot name lands nowhere yet. Choose where it lands first.",
  feedsOfSourceFirst: "Feeds of this lead source",
} as const;

export const NUMBER_SHEET_COPY = {
  titleNew: "Add an inbound number",
  title: (phone: string) => phone,
  blockNumber: "The number",
  blockCheck: "Check it against RingCentral",
  blockFeed: "Which call feed it files into",
  blockFiling: "Start or stop filing",
  blockHistory: "Where calls were filed",
  number: "Phone number",
  numberLocked: "The phone number is locked after the first time it is turned on. If it is wrong, add a new number instead of editing this one.",
  numberHint: "Like +18885551212. Changing it clears the RingCentral check.",
  nickname: "Number nickname",
  checkButton: "Check against RingCentral",
  queueFound: "RingCentral verified queue",
  queueNone: "Not checked yet",
  lastCheck: (check: string, seen: string, since?: string) =>
    `Last check: ${check} · Last observed: ${seen}${since ? ` · Effective assignment start: ${since}` : ""}`,
  never: "never",
  feedLabel: "Call feed",
  feedPick: "Select a call feed",
  feedDisabledHint: "Choose the call feed is disabled until this number is checked against RingCentral.",
  leadSourceFromFeed: (name: string) => `Lead source (from the feed): ${name}`,
  filedUnder: "Calls to this number are filed under",
  checklist: {
    one: (done: boolean) => `1. Save the number ${done ? "· done" : "· not yet"}`,
    two: (done: boolean) => `2. Prove it exists in RingCentral ${done ? "· done" : "· not yet"}`,
    three: (done: boolean, ready: boolean) =>
      `3. Choose the call feed ${done ? "· done" : ready ? "· ready" : "· waiting on a successful check"}`,
    four: "4. Turn on filing",
  },
  saveNumber: "Save the number",
  start: "Start filing calls",
  stop: "Stop filing new calls",
  confirmStop: "Stop filing",
  reassignTitle: "File new calls under a different feed",
  reassignHint:
    "New calls use the new feed immediately. Old calls and leads keep the lead source and feed they were filed under.",
  reassignNew: "New call feed",
  reassignWhy: "Why are you moving it? (optional)",
  reassignConfirm: "Move new calls",
  historyFrom: "From",
  historyUntil: "Until",
  historyLeadSource: "Lead source",
  historyFeed: "Feed",
  historyOpen: "Open",
  historyNone: "No history yet.",
  savedAsOn: "Saved as on",
  validationMessages: {
    valid: "Validation succeeded.",
    invalid: "Validation completed: the number is invalid.",
    unavailable: "Validation unavailable; the draft stays editable.",
    other: "Validation completed.",
  },
  created: "Draft number saved. It is not filing calls yet.",
  started: "Calls to this number are now filed under the feed you chose. The phone number is locked.",
  stopped: "Stopped. Calls already recorded and their leads keep their feed.",
  moved: "New calls now go to the new feed.",
  nicknameSaved: "Nickname saved.",
  whyOptional: "Why? (optional)",
} as const;

export const ADD_COPY = {
  title: "Add a lead source",
  intro: "Six screens, one question each. Nothing is on until the last one.",
  screens: ["Who", "How", "Granot", "Number", "Cost", "Turn on"],
  step: (n: number, label: string) => `${n}. ${label}`,
  back: "Back",
  next: "Continue",
  cancel: "Cancel",
  saveDraft: "Save as draft and continue",
  savingDraft: "Saving",
  skip: "Skip for now",
  // Screen 1
  q1: "Who sends you these leads?",
  nameLabel: "Lead source name",
  nameHint: "The partner's real name, for example Best Relocation. For our records. Customer texts still say Vantage Movers.",
  showAsLabel: "Show it as",
  showAsHint: "What you will pick in filters and reports. Defaults to the name above.",
  spellingsLabel: "Also accept these spellings",
  spellingsHint:
    "Used only when an incoming lead does not match exactly. Not shown anywhere and not used in reports.",
  spellingsPlaceholder: "Separate with commas",
  // Screen 2
  q2: "Where do these leads come from?",
  arrivalLabel: "How the leads arrive",
  arrivalForm: "Web forms",
  arrivalCall: "Inbound calls",
  arrivalBoth: "Both",
  arrivalDefaultNote: "If you pick nothing, the source gets one web form feed.",
  splitLegend: "Web forms",
  splitOne: "One form for everything",
  splitTwo: "Local and long distance separately",
  splitTwoHint: "Two feeds: one for local moves and one for long-distance moves.",
  splitTwoNote: "This saves the local feed first. The long-distance feed is added right after.",
  feedKindNote: "Once a feed has been on, its kind (web forms or inbound calls) cannot be changed.",
  feedNameForm: "Name the web form feed",
  feedNameCall: "Name the phone calls feed",
  feedNameLocal: "Name the local feed",
  feedNameLong: "Name the long-distance feed",
  feedNameHint: 'Defaults to "Web forms" or "Inbound calls".',
  granotSendsLabel: "What Vantage sends to Granot",
  granotSendsHint:
    "The exact label Vantage puts on every lead from this feed when it posts to Granot. This is also the spelling that appears in the Source Company column of your sheet. It must not match any other active feed of the same kind.",
  callGranotSendsLabel: "What Vantage sends to Granot for the call feed",
  // Screen 3
  q3: "Does Granot send you leads under a name for this source?",
  yes: "Yes",
  notYet: "Not yet",
  notYetNote:
    "Leads will still arrive through the form or the phone number. The lead source will show connect a Granot name as a next step.",
  granotNameLabel: "Name received from Granot",
  granotNameHint:
    "Type it exactly as Granot spells it. If it differs by even one character, leads under that name will not be recognized here.",
  arrivalLegend: "When a lead arrives",
  textLater: "Texting is set up after the Granot name is saved. We will bring you back to this on the next screen.",
  textLaterTitle: "Text the customer",
  textLaterOff: "Off by default.",
  landingLegend: "Where it lands",
  landingBoth: "Local and long distance, by the move type",
  landingLocalOnly: "Only the local feed",
  callGranotLabel: "Granot name for the call feed",
  callGranotHint: "Calls usually arrive under their own Granot name. Leave it empty to connect one later.",
  // Review
  reviewTitle: "You are creating",
  reviewLeadSource: "lead source",
  reviewFeed: "feed",
  reviewNoGranot: "No Granot name yet. Connect a Granot name later from the lead source.",
  reviewNothingLive: "Nothing is live yet. After saving you will:",
  reviewNeedsPreview: "Review comes from the server preview.",
  reviewKey: (key: string) => `Internal key: ${key}`,
  reviewFeedKey: (key: string) => `Feed key: ${key}`,
  reviewSendsToGranot: (label: string) => `What Vantage sends to Granot: ${label}`,
  reviewSheetColumn: (label: string) => `Sheet Source Company column: ${label}`,
  reviewWaiting: (what: string) => `waiting on ${what}`,
  reviewSuggested: "(suggested)",
  previewFailed: "The preview failed.",
  // Screen 4
  q4: "What phone number rings?",
  q4Hint: "The number and a nickname. Checking it asks RingCentral for the queue behind it.",
  numberLabel: "Phone number",
  nicknameLabel: "Number nickname",
  nicknameHint: "Only helps you recognize this number in Vantage. It does not decide where the call goes.",
  check: "Check against RingCentral",
  checking: "Checking",
  savedDraft: "Draft number saved",
  checkedOk: "Checked against RingCentral",
  checkedBad: "RingCentral could not confirm this number",
  queue: (name: string) => `Queue found: ${name}`,
  filedLater: "It is filed under the call feed when you turn it on (the last screen).",
  skipNumber: "Add a number later",
  // Screen 5
  q5: "What do you pay per lead?",
  q5Hint:
    "One amount per feed, effective today. Leave it blank and the feed will show as unpriced until you set it. A feed cannot go live without a lead cost.",
  amountFor: (feed: string) => `${feed}`,
  amountPlaceholder: "0.00",
  saveCosts: "Save lead costs and continue",
  savingCosts: "Saving",
  costBlankNote: "Blank means no lead cost yet. The next screen will say a feed with no cost cannot go live.",
  // Screen 6
  q6: "Turn it on",
  q6Hint: "The steps run in order. Each one reports done or blocked with the reason.",
  defaultQuestion: (channel: LeadSourceChannel) => `Which feed is the default for ${CHANNEL_WORDS[channel]}?`,
  defaultHint: "The last feed turned on becomes the default, so the one you choose is turned on last.",
  run: "Turn it on",
  running: "Turning it on",
  finish: "Finish",
  finishOpen: "Open this lead source",
  customerTextFollowUp: "Customer text is never turned on here. Open the Granot name when you are ready.",
  noSteps: "Nothing is left to turn on.",
  doneTitle: "Saved as a draft",
  doneBody: "The lead source is in the list. You can finish turning it on from its Turn it on block at any time.",
} as const;

/** Server dependency keys are engineering words; show them the way the Owner says them. */
export function ownerDependencyWords(key: string): string {
  return key
    .replace(/source_granularit(y|ies)/g, "feeds")
    .replace(/granularit(y|ies)/g, "feeds")
    .replace(/source_compan(y|ies)/g, "lead sources")
    .replace(/lifecycle/g, "live")
    .replace(/_/g, " ");
}

export const NEEDS_YOU_COPY = {
  costMissing: (source: string, feed: string) => `${source} · ${feed} has no lead cost`,
  costInvalid: (source: string, feed: string) => `${source} · ${feed} has a lead cost that needs fixing`,
  granotNowhere: (name: string) => `"${name}" was seen in Granot but lands nowhere`,
  numberNotFiling: (phone: string) => `${phone} is checked but not filing calls`,
  numberStopped: (phone: string) => `${phone} stopped filing calls`,
  callFeedNoNumber: (source: string, feed: string) => `${source} · ${feed} has no inbound number`,
  sourceOffLiveFeeds: (source: string) => `${source} is off but has feeds that are on`,
} as const;
