export const EXTENSION_COPY = {
  pageTitle: "Extension",
  pageHint:
    "Create, edit, and delete logins for the Granot browser extension. One person may hold Sales and Customer Service. These people are Extension Users, not Agents.",
  rolesTitle: "What each role can do",
  ownerRole:
    "Owner: can sync leads (Enrichment) and use search in the extension. Also has Binding Estimate Fee and Tariff Adjustment.",
  salesRole: "Sales: can use Binding Estimate Fee only.",
  customerServiceRole: "Customer Service: can use Tariff Adjustment only.",
  emailLabel: "Email",
  emailHint: "This is the login used in the browser extension.",
  passwordLabel: "Password",
  passwordHint: "At least 8 characters.",
  passwordEditHint: "Leave blank to keep the current password.",
  rolesLabel: "Roles",
  rolesRequired: "Choose at least one role.",
  ownerOption: "Owner",
  salesOption: "Sales",
  customerServiceOption: "Customer Service",
  createButton: "Create Extension User",
  creatingButton: "Creating…",
  created: "Extension User created.",
  editButton: "Edit",
  editTitle: "Edit Extension User",
  saveButton: "Save",
  savingButton: "Saving…",
  cancelButton: "Cancel",
  updated: "Extension User updated.",
  deleted: "Extension User deleted.",
  deleteButton: "Delete",
  deleteConfirmButton: "Delete",
  cancelDeleteButton: "Cancel",
  deleteConfirm: (email: string) =>
    `Delete ${email}? The extension session ends immediately.`,
  listTitle: "Extension Users",
  emptyList: "No Extension Users yet.",
  roleOwner: "Owner",
  roleSales: "Sales",
  roleCustomerService: "Customer Service",
  active: "Active",
  inactive: "Inactive",
} as const;
