/** People & access copy (doc 19). Owner words: Agent, Granot username, Dashboard login, Extension login, RingCentral. No em-dashes. */

export const PEOPLE_COPY = {
  addMenu: {
    label: "Add",
    agent: "Add Agent",
    agentHint: "A person on the roster, with or without a Granot username.",
    login: "Add dashboard login",
    loginHint: "Owner, Admin, Manager or Rep sign-in for this dashboard.",
    extension: "Add extension login",
    extensionHint: "Sign-in for the Granot browser extension: Owner, Sales or Customer Service.",
  },
  searchPlaceholder: "Search name, email, Granot username or extension",
  includeInactive: "Include inactive",
  count: (shown: number) => `${shown} ${shown === 1 ? "person" : "people"}`,
  empty: "No one matches this search.",
  emptyNone: "No people yet. Add the first one.",
  readFailed: "People couldn't load.",
  readOnlyNote: "You can read the roster here. Logins and RingCentral are managed by the Owner.",
  active: "Active",
  inactive: "Inactive",
  notLoaded: "not loaded",
  edit: "Edit",
  addPart: "Add",
  change: "Change",
  connect: "Connect",
  disconnect: "Disconnect",
  roleWord: { owner: "Owner", admin: "Admin", manager: "Manager", rep: "Sales rep" } as Record<string, string>,
  loginRoleWord: { owner: "Owner", admin: "Admin", manager: "Manager", rep: "Rep" } as Record<string, string>,
  lines: { roster: "Roster", desk: "Outreach Desk", dashboard: "Dashboard", extension: "Extension", ringcentral: "RingCentral", pay: "Pay" },
  desk: {
    on: "On the desk",
    off: "Not on the desk",
    unknown: "not loaded",
    reason: {
      granot: "automatic, has a Granot username",
      ringcentral: "automatic, connected to a RingCentral sales line",
      owner_on: "you turned it on",
      owner_off: "you turned it off",
      none: "automatic, no Granot username or RingCentral sales line yet",
      inactive: "inactive Agents are never on the desk",
    } as Record<string, string>,
    settingWord: { auto: "Automatic", on: "Always on", off: "Off" } as Record<string, string>,
  },
  roster: {
    granot: (username: string) => `Granot username ${username}`,
    noGranot: "No Granot username yet",
  },
  dashboard: {
    noLogin: "no login",
    lastSignIn: (when: string) => `last sign-in ${when}`,
    neverSignedIn: "never signed in",
    deactivated: "deactivated",
  },
  extension: { none: "no extension login", inactive: "inactive" },
  ringcentral: {
    ext: (n: string | null) => (n ? `ext ${n}` : "no extension number"),
    none: "not connected",
    reviewed: "reviewed",
    notReviewed: "not reviewed",
    roleWord: {
      sales_rep: "Sales rep",
      service: "Service",
      manager: "Manager",
      dialer: "Dialer",
      shared: "Shared line",
      excluded: "Excluded",
    } as Record<string, string>,
    noRole: "no role yet",
  },
  pay: "not recorded (arrives with Today → Money)",

  /* Sheets */
  sheet: {
    roster: (name: string) => `Roster · ${name}`,
    desk: (name: string) => `Outreach Desk · ${name}`,
    addAgent: "Add an Agent",
    addLogin: "Add a dashboard login",
    addExtension: "Add an extension login",
    editLogin: (email: string) => `Dashboard login · ${email}`,
    editExtension: (email: string) => `Extension login · ${email}`,
    loginGone: "This login no longer exists.",
    login: (name: string) => `Dashboard login · ${name}`,
    extension: (name: string) => `Extension login · ${name}`,
    ringcentral: (name: string) => `RingCentral · ${name}`,
    addPerson: "Add an Agent",
    notFound: "This person is no longer on the roster.",
    cancel: "Cancel",
    saving: "Saving…",
    skip: "Skip this step",
    done: "Done",
  },
  rosterSheet: {
    name: "Display name",
    nameHint: "Renaming keeps the old name as an alias, so past records still match.",
    granot: "Granot username",
    granotHint: "Optional. Must be unique across Agents. Correct a misspelling here so the browser extension matches this Agent. Leave it empty for someone with no Granot login.",
    granotClearNote: "Saving with this empty removes the Granot username. Granot Leads under the old username stop matching this Agent.",
    granotPlaceholder: "e.g. MIKEM",
    reason: "Reason (optional)",
    reasonPlaceholder: "Why you are changing this",
    save: "Save",
    saved: "Roster updated.",
    nameRequired: "Enter a name.",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    reactivated: "Reactivated.",
    deactivated: "Deactivated.",
    previewTitle: "Before you deactivate",
    previewTotal: (n: number) => `${n} ${n === 1 ? "record depends" : "records depend"} on this.`,
    previewNone: "Nothing depends on this.",
    confirmDeactivate: "Confirm deactivation",
    keep: "Keep active",
    deactivationReason: (reason: string) => `Deactivation reason: ${reason}`,
    previewFailed: "Couldn't check what depends on this.",
    create: "Add to the roster",
    created: (name: string) => `${name} is on the roster.`,
    desk: "Outreach Desk",
  },
  deskSheet: {
    intro: "Desk reps get their Leads assigned on the Outreach Desk, can sign in to their own desk with a Rep login, and count toward the daily goals.",
    now: (state: string, why: string) => `Now: ${state} (${why}).`,
    options: {
      auto: { label: "Automatic", hint: "On the desk while active and they have a Granot username or a connected RingCentral sales line." },
      on: { label: "Always on", hint: "On the desk while active, even without a Granot username or RingCentral line." },
      off: { label: "Off", hint: "Never on the desk. Their Leads stay Unassigned there." },
    } as Record<string, { label: string; hint: string }>,
    save: "Save",
    saved: "Outreach Desk setting saved.",
  },
  loginSheet: {
    email: "Email",
    role: "Role",
    agent: "Agent",
    agentFixed: "Linked to this Agent.",
    agentHint: "Required for a rep. Only active Agents not linked to another active rep are listed. Not on the roster yet? Add the Agent below.",
    agentPlaceholder: "Choose an Agent",
    noAgentsFree: "Every active Agent is already linked to an active rep.",
    notRepNote: "An Owner, Admin or Manager login is not linked to an Agent. It is listed under Logins without an Agent.",
    newAgentTitle: "Not on the roster yet?",
    newAgentBody: "Add the Agent here. The Rep login is then linked to them.",
    alsoExtension: "Also give them an extension login?",
    stepTitle: "Login details",
    access: "How they sign in",
    accessInvite: "Send an invite link",
    accessPassword: "Set a password now",
    password: "Password",
    passwordPolicy: "At least 10 characters, up to 72 bytes.",
    active: "Active",
    create: "Add login",
    save: "Save",
    created: (email: string) => `${email} added.`,
    saved: (email: string) => `Saved ${email}.`,
    inviteAfterCreate: (sentence: string) => `The login was added, but the invite wasn't sent: ${sentence}`,
    passwordBlock: "Password and invite",
    setPassword: "Set password",
    setPasswordBody: "This signs them out everywhere. Tell them the new password yourself.",
    passwordDone: (email: string) => `Password set for ${email}. They were signed out everywhere.`,
    sendInvite: "Send invite",
    inviteTitle: "Invite link",
    deactivateBlock: "Deactivate",
    deactivateTitle: (email: string) => `Deactivate ${email}?`,
    deactivateBody: "They're signed out at their next request and can't sign in again until you reactivate them here.",
    deactivateConfirm: "Deactivate login",
    deactivateDone: (email: string) => `${email} is deactivated.`,
    roleHint: {
      owner: "Everything, including logins.",
      admin: "Setup and the operations pages; no Outreach Desk.",
      manager: "Outreach Desk for the whole team and Daily Operations. No other pages.",
      rep: "Their own Outreach Desk queue, linked to their Agent.",
    } as Record<string, string>,
    agentsLoadFailed: "Couldn't load the Agent list.",
    inviteNotSetUp: "Invite links aren't set up on this admin yet. Set a password instead.",
  },
  extensionSheet: {
    email: "Email",
    emailHint: "This is the login used in the browser extension.",
    password: "Password",
    passwordHint: "At least 8 characters.",
    passwordKeep: "Leave blank to keep the current password.",
    roles: "Roles",
    rolesRequired: "Choose at least one role.",
    create: "Create extension login",
    creating: "Creating…",
    save: "Save",
    created: "Extension login created.",
    updated: "Extension login updated.",
    removed: "Extension login removed.",
    remove: "Remove",
    hardDelete: "Removing is a hard delete: the login is erased, not deactivated, and cannot be brought back. Create it again to restore access.",
    removeConfirm: (email: string) => `Remove ${email}? Their extension session ends immediately.`,
    removeConfirmButton: "Remove for good",
    keep: "Keep it",
    agent: "Agent",
    agentNone: "No Agent (for example the Owner's own login)",
    agentFixed: "Connected to this Agent.",
    agentHint: "The roster person this extension login belongs to. It then shows on their card.",
    agentTaken: "Another extension login is already connected to that Agent.",
    newAgentTitle: "Not on the roster yet?",
    newAgentBody: "Add the Agent here. This extension login is then connected to them.",
    connectSaved: "Agent connection saved.",
  },
  ringcentralSheet: {
    connectHint: "Calls on this extension count for the Agent from now on.",
    pick: "RingCentral user",
    pickPlaceholder: "Choose a RingCentral user",
    suggested: (name: string, ext: string | null) => `Suggested: ${name}${ext ? ` · ext ${ext}` : ""}`,
    role: "Role",
    rolePlaceholder: "Keep the current role",
    connect: "Connect",
    saveRole: "Save role",
    disconnect: "Disconnect",
    disconnectConfirm: (agent: string, user: string) => `Disconnect ${agent} from ${user}? Calls on this extension stop counting for ${agent}.`,
    keep: "Keep",
    connected: (agent: string, user: string) => `${agent} is connected to ${user}.`,
    disconnected: (user: string) => `${user} is not connected now.`,
    conflict: "This account changed while you were editing. The latest version is loaded. Check it and try again.",
    failed: (detail: string | null) => (detail ? `Couldn't save this: ${detail}` : "Couldn't save this. Try again."),
    unnamed: "Unnamed user",
    noneFree: "Every RingCentral user in the directory is already connected.",
    directoryMissing: "The RingCentral list isn't loaded. Close this and try again in a minute.",
    connectedNow: "Connected now",
  },
  addPerson: {
    steps: {
      roster: "Who is this?",
      desk: "Outreach Desk",
      login: "Also give them a dashboard login?",
      extension: "Also the Granot extension?",
      ringcentral: "Which RingCentral extension is theirs?",
    },
    cardNote: "Their card is on the page now. The steps below are optional.",
    ownerOnly: "Only the Owner can add people.",
    stepDone: "Done",
  },
  notMatched: {
    title: "Logins without an Agent",
    purpose: "Dashboard and extension logins and RingCentral users that no Agent on the roster claims. Owner, Admin and Manager logins belong here; a Rep or Sales login usually belongs to an Agent.",
    users: "Dashboard logins without an Agent",
    extensionUsers: "Extension logins without an Agent",
    sameEmailExtension: (roles: string) => `Extension login with the same email: ${roles}`,
    accounts: "RingCentral users with no Agent",
    connectTo: "Connect to…",
    connectToLabel: (name: string) => `Connect ${name} to an Agent`,
    connectButton: "Connect",
    connected: "Connected.",
    noAgentRole: (role: string) => `An ${role} login is not linked to an Agent, so there is nothing to connect.`,
    extensionNote: "Connect it to an Agent, or open it to add the Agent.",
    none: "Every login belongs to an Agent.",
    notLoaded: "Not loaded.",
  },
} as const;
