export const GRANOT_LIFECYCLE_HREF = "/granot-lifecycle";
export const GRANOT_LIFECYCLE_RECEIPTS_HREF = "/granot-lifecycle/receipts";
export const GRANOT_LIFECYCLE_HEALTH_HREF = "/granot-lifecycle/health";

export const GRANOT_LIFECYCLE_COPY = {
  pageTitle: "Granot Lifecycle",
  receiptsTab: "Receipts",
  healthTab: "Health",
  receiptsPageTitle: "Granot webhook receipts",
  receiptsPageDescription:
    "Search historical Granot Observation Receipts from the webhook channel.",
  empty: "No matching Granot webhook receipts.",
  loading: "Loading Granot webhook receipts.",
  loadError: "Unable to load Granot webhook receipts.",
  openJobTimeline: "Open Job Timeline",
  openIntake: "Open Intake",
  eventTypeAll: "All",
  eventTypeLeadCreated: "Lead created",
  eventTypePriorityUpdated: "Priority updated",
  eventTypeBookingStatusChanged: "Booking status changed",
  bookingActionAll: "All actions",
  bookingActionBooked: "Booked",
  bookingActionRelease: "Release",
  filterTrackingReference: "Tracking reference",
  filterJobNumber: "Job Number",
  filterLeadName: "Lead name",
  filterPhone: "Phone",
  filterEmail: "Email",
  filterSourceCompany: "Source Company",
  filterEventType: "Event type",
  filterBookingAction: "Booked or Release",
  filterCapturedFrom: "Captured from",
  filterCapturedTo: "Captured to",
  filterProcessingState: "Processing",
  filterLimit: "Rows",
  sourceCompanyAll: "All Source Companies",
  processingStateAll: "All states",
  processingStatePending: "Pending",
  processingStateClaimed: "Claimed",
  processingStateRetryScheduled: "Retry scheduled",
  processingStateCompleted: "Completed",
  processingStateDeadLetter: "Dead letter",
  applyFilters: "Apply filters",
  resetFilters: "Reset",
  nextPage: "Next page",
  columnContact: "Contact",
  columnEventType: "Event type",
  columnBookingAction: "Booking Action",
  columnSourceCompany: "Source Company",
  columnProcessing: "Processing",
  columnRefNo: "Tracking reference",
  columnJobNo: "Job Number",
  columnCaptured: "Captured",
  columnActions: "Actions",
  backToIntakes: "Back to Intakes",
  backToIntakesHref: "/intakes",
} as const;
