/**
 * Owner-visible strings for Bookings to finish (doc 06). "Intake" is not an Owner word any more: a Granot Booking
 * Reconciliation Case is a booking to finish. The older `intake-copy.ts` helpers stay for the pieces that still read
 * them (the Granot statement, the reference drawers, the technical lifecycle pages).
 */
export const TO_FINISH_HREF = "/intakes";

export const TO_FINISH_COPY = {
  title: "Bookings to finish",
  subtitle: "Granot recorded these jobs as booked. Vantage does not have the official booking yet.",
  help: "Open one to check the customer, write the official numbers and file it. Granot's numbers sit beside each field with a Use button; nothing is copied unless you press it. If an official booking already exists and is right, choose No action.",
  refresh: "Refresh",
  refreshing: "Checking…",
  loadFailed: "Could not load the bookings to finish.",
  loadMore: "Loading more…",
  allLoaded: "That is every booking to finish.",
  empty: "Nothing to finish.",
  emptyHint: "When Granot records a Booked job that Vantage has not booked, it shows up here.",
  finish: "Finish",
  review: "Review",
  finishedToday: (count: number) => `Finished today (${count})`,
  finishedTodayEmpty: "Nothing finished yet today.",
  finishedTodayFailed: "Could not load today's finished bookings.",
  updates: (count: number) => (count === 1 ? "1 update" : `${count} updates`),
  twoCustomers: "Two possible customers · pick one",
  customerMatched: "Customer matched",
  rep: "Rep",
  openTimeline: "Job timeline",
  customerFallback: "No customer name yet",
  officialExists: "Vantage already has a booking for this job",
  referral: "Referral booking · no lead",
} as const;

export const FINISH_SHEET_COPY = {
  title: (job: string) => `Finish booking · Job ${job}`,
  titleLoading: "Finish booking",
  loading: "Loading this booking…",
  loadFailed: "Could not load this booking.",
  finishedTitle: "This booking is already finished",
  finishedBody: "Another update closed it. Nothing more to do here.",
  whatGranotSent: "What Granot sent",
  exactMessage: "Exact message",
  exactMessageHint: "Word for word, with passwords and keys removed.",
  messageCustomer: "Customer",
  messageName: "Name",
  messagePhone: "Phone",
  messageEmail: "Email",
  messageMove: "Move",
  messageFrom: "From",
  messageTo: "To",
  messageMoveDate: "Move date",
  messageCubicFeet: "Cubic feet",
  messageMoney: "Money",
  messageEstimate: "Granot estimate",
  messagePayment: "Customer payment",
  messageBalance: "Balance",
  messageGranot: "Granot details",
  messageCalledIt: "Granot called it",
  messagePriority: "Priority",
  messageJob: "Job number",
  messageReference: "Reference",
  messageUser: "Granot user",
  messageSource: "Source",
  messageEveryField: "Every field Granot sent",
  messageValue: "Value",
  messageEmpty: "Granot sent no fields with this update.",
  customerBlock: "Customer",
  officialBlock: "Official booking",
  fileBlock: "File it",
  details: "Details",
  detailsHint: "What Vantage already has, every Granot update, and how this job got here.",
  strongMatch: "Strong match",
  possibleMatch: "Possible match",
  matchedByVantage: "Vantage matched",
  chosenByOwner: "You chose",
  changeCustomer: "Change customer",
  findCustomer: "Find the customer",
  noLead: "No lead",
  noLeadChosen: "No lead · this becomes a Leadless Booking",
  noLeadChosenHint: "It is saved to Master Booked now and a lead can be connected later from Bookings.",
  noStrongMatch: "No strong match. Search for the customer, or file it with no lead and connect one later from Bookings.",
  lookingForCustomer: "Looking for the customer this job belongs to…",
  reasonOnFile: (reason: string) => `Reason on file: ${reason}`,
  referralNoLead: "Referral booking. No lead is searched or attached.",
  reviewExisting: "Vantage already has a booking for this job. Change official numbers only if they are wrong; otherwise choose No action.",
  attached: "Lead attached",
  leadless: "Leadless Booking",
  bookDate: "Book date",
  binder: "Binder",
  deposit: "Deposit",
  agent: "Agent",
  splitWith: "Split with",
  merchant: "Merchant",
  noSplit: "No split",
  chooseAgent: "Choose agent",
  chooseMerchant: "Choose merchant",
  suggested: "suggested",
  lastUsed: "last used",
  use: "Use",
  used: "Used",
  granotSays: (what: string) => `Granot says ${what}`,
  granotEstimate: (what: string) => `Granot estimate ${what}`,
  granotPayment: (what: string) => `Granot customer payment ${what}`,
  granotRep: (username: string, agent?: string) => (agent ? `Granot rep ${username} → ${agent}` : `Granot rep ${username}`),
  noGranotValue: "Granot did not send this",
  splitPreview: (lines: string) => lines,
  catalogLoading: "Loading agents and merchants…",
  noAction: "No action",
  noActionTitle: "Close with no action",
  noActionHint: "Closes this case without changing a lead, a booking or a sheet.",
  noActionReason: "Reason",
  noActionNone: "No reason",
  noActionNote: "Note",
  noActionConfirm: "Close with no action",
  noActionClosing: "Closing…",
  noActionDone: "Closed with no action. No official record changed.",
  fileBooking: "File booking",
  filing: "Filing…",
  updateBooking: "Update booking",
  updating: "Updating…",
  filedWithLead: "Booking filed with the customer attached.",
  filedLeadless: "Booking filed to Master Booked. No lead was attached. Connect one later from Bookings.",
  filedReferral: "Referral booking filed.",
  filedUpdated: "Booking updated.",
  alreadySatisfied: "The official booking already matched this case.",
  correct: "Correct the following",
  commandsOff: "Vantage is not ready to file bookings from this screen. This booking keeps waiting.",
  done: "Done",
  cancelBooking: "Cancel this booking",
} as const;

/** The No action reasons (the same codes the lifecycle No Action form sends). */
export const NO_ACTION_REASONS = [
  { value: "already_handled_elsewhere", label: "Already handled elsewhere" },
  { value: "granot_action_not_authoritative", label: "Granot action is not authoritative" },
  { value: "wrong_customer_or_job", label: "Wrong customer or job" },
  { value: "duplicate_granot_action", label: "Duplicate Granot action" },
  { value: "booking_still_valid", label: "Booking is still valid" },
  { value: "granot_change_only", label: "Granot-only change" },
  { value: "insufficient_information", label: "Insufficient information" },
  { value: "legacy_data", label: "Legacy data" },
  { value: "other", label: "Other" },
] as const;

export const NO_ACTION_NOTE_MAX = 1000;
