export const MANUAL_COPY = {
  pageHint:
    "Create a Form Lead or Call Lead, or attach an existing lead to a booking that has no stored lead.",
  createTitle: "Create a Lead",
  createHint:
    "Choose Form Lead or Call Lead. Source and duplicate rules stay on the server. You cannot choose how the lead was created.",
  kindLabel: "Lead kind",
  formLead: "Form Lead",
  callLead: "Call Lead",
  sourceCompany: "Source Company",
  sourceCompanyPlaceholder: "Choose Source Company",
  sourceGranularity: "Source Granularity",
  sourceGranularityPlaceholder: "Choose Source Granularity",
  sourceGranularityHint: "When this Source Company has more than one stream, pick the exact one.",
  name: "Name",
  phone: "Phone",
  email: "Email",
  pickupZip: "Pickup zip",
  destinationZip: "Delivery zip",
  moveSize: "Move size",
  moveDate: "Move date",
  jobNumber: "Job number",
  postToGranot: "Also send this Form Lead to Granot",
  postToGranotHint: "Skipped automatically when the lead is a Duplicate Lead.",
  createForm: "Create Form Lead",
  createCall: "Create Call Lead",
  creatingForm: "Creating Form Lead…",
  creatingCall: "Creating Call Lead…",
  successForm: "Form Lead created. Master Leads will update.",
  successCall: "Call Lead created. Master Leads will update.",
  duplicateNotice: "This Form Lead was saved as a Duplicate Lead. It will not be posted to Granot.",
  viewLead: "View lead",
  connectTitle: "Connect Booking to Lead",
  connectHint:
    "Find a booking that has no stored lead, then attach a Form Lead or Call Lead that is not already booked.",
  searchBookings: "Job number or customer",
  searchBookingsPlaceholder: "Job number or customer name",
  searchBookingsAction: "Find bookings",
  recentLeadless: "Bookings with no stored lead",
  noLeadless: "No bookings with a missing stored lead match this search.",
  chooseBooking: "Choose this booking",
  changeBooking: "Choose a different booking",
  viewBooking: "View booking",
} as const;
