export const MANUAL_COPY = {
  pageHint: "Create a Form Lead or Call Lead, or connect a booking that has no stored lead.",
  createTab: "Create a Lead",
  attachTab: "Connect Booking to Lead",
  createTitle: "Create a Lead",
  createHint:
    "Choose Form Lead or Call Lead, then the Source Company — Top10 Inbounds, not Top10. Source and duplicate rules stay on the server. You cannot choose how the lead was created.",
  kindLabel: "Form Lead or Call Lead",
  sourceCatalogError: "Source Company list could not be loaded.",
  formLead: "Form Lead",
  callLead: "Call Lead",
  sourceCompany: "Source Company",
  sourceCompanyPlaceholder: "Choose Source Company",
  sourceCompanyHint: "Pick the exact stream, such as Top10 Inbounds.",
  name: "Name",
  phone: "Phone",
  email: "Email",
  pickupZip: "Pickup zip",
  destinationZip: "Delivery zip",
  moveSize: "Move size",
  moveDate: "Move date",
  jobNumber: "Job number",
  refNumber: "Ref number",
  postToGranot: "Also send this Form Lead to Granot",
  postToGranotHint: "Skipped automatically when the lead is a Duplicate Lead.",
  createForm: "Create Form Lead",
  createCall: "Create Call Lead",
  creatingForm: "Creating Form Lead…",
  creatingCall: "Creating Call Lead…",
  successForm: "Form Lead created. Master Leads will update.",
  successCall: "Call Lead created. Master Leads will update.",
  duplicateNotice: "This Form Lead was saved as a Duplicate Lead. It will not be posted to Granot.",
  viewLead: "View lead",
  connectTitle: "Connect Booking to Lead",
  connectHint:
    "Find the booking by job number on the left. Find the lead on the right. Then connect them.",
  findBookingTitle: "Find booking",
  findLeadTitle: "Find lead",
  searchJobNumber: "Job number",
  searchJobNumberPlaceholder: "Job number",
  searchBookingsAction: "Find booking",
  searchLeadsAction: "Find lead",
  findingBookings: "Finding bookings…",
  findingLeads: "Finding leads…",
  noBookingMatch: "No booking with a missing stored lead matches this job number.",
  bookingNotConnectable: "This booking already has a stored lead, is a referral, or is cancelled.",
  enterJobNumber: "Enter a job number to find the booking.",
  enterLeadSearch: "Enter at least one lead field to search.",
  noLeadMatch: "No matching lead.",
  chooseBooking: "Choose this booking",
  chooseLead: "Choose this lead",
  selectedBooking: "Selected booking",
  selectedLead: "Selected lead",
  viewBooking: "View booking",
  reviewTitle: "Review this connection",
  needBoth: "Choose a booking and a lead before connecting.",
  connectLead: "Connect lead",
  connecting: "Connecting…",
  overrideLabel: "Why this customer is the right one even though they came from a different lead source",
  overrideHint: "Write 10–500 characters. Same-source customers do not need this.",
  connectSuccess: "Master Leads and Master Booked will update.",
} as const;
